// Draft distribution assets: no publication, messages, tracking or fabricated menu data.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../..'),out=path.join(root,'docs/growth-release-2026-10-09/distribution');
fs.mkdirSync(path.join(out,'graphics'),{recursive:true});
fs.mkdirSync(path.join(out,'share-previews'),{recursive:true});
fs.mkdirSync(path.join(out,'licenses'),{recursive:true});
for(const file of ['fonts/OFL-Bricolage-Grotesque.txt','fonts/LICENSE-inter.txt'])fs.copyFileSync(path.join(root,file),path.join(out,'licenses',path.basename(file)));
let window={}; for(const file of ['js/meal-data.js','js/meal-provenance.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),{window});
const sourceFiles=['js/meal-data.js','js/meal-provenance.js'].map(file=>({file,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex')}));
const configurations=[
 {id:'01-qdoba-bowl-burrito',chain:'QDOBA',a:'Chicken Queso Bowl',b:'Chicken Queso Burrito',title:'Bowl or burrito?',context:'Compare the two published builds—not a guessed tortilla.',detail:'The burrito has {cal} more kcal and {p} g more protein.',metric:'na',portionA:'One published bowl · 468 g',portionB:'One published burrito · 569 g',destination:'qdoba-burrito-bowl-published-pair.html',character:'egg'},
 {id:'02-qdoba-protein-sodium',chain:'QDOBA',a:'Keto Bowl - Chicken',b:'Keto Bowl - Steak',title:'Protein and sodium differ',context:'“Keto Bowl” is the restaurant’s product name, not our advice.',detail:'Chicken has 8 g more protein; steak has 50 mg less sodium.',metric:'na',portionA:'One published chicken bowl · 340 g',portionB:'One published steak bowl · 340 g',destination:'qdoba-nutrition-guide.html',character:'steak'},
 {id:'03-pollo-corn-flour',chain:'El Pollo Loco',a:'2 pc Breast & Wing Meal w/Corn Tortillas Pinto Beans & Rice',b:'2 pc Breast & Wing Meal w/Flour Tortillas Pinto Beans & Rice',title:'Check the tortilla version',context:'Breast, wing, tortillas, pinto beans and rice are included.',detail:'The flour-tortilla build adds {cal} kcal and {na} mg sodium.',metric:'na',portionA:'Two-piece corn-tortilla meal · 17.9 oz',portionB:'Two-piece flour-tortilla meal · 18.1 oz',destination:'el-pollo-loco-tortilla-complete-chicken-meal.html',character:'chicken'},
 {id:'04-pollo-quesadilla',chain:'El Pollo Loco',a:'Salsa Verde Chicken Quesadilla',b:'Chipotle Chicken Quesadilla',title:'Same protein. Different build.',context:'These are two complete published quesadilla rows.',detail:'Both list 51 g protein; the chipotle version adds {cal} kcal.',metric:'na',portionA:'One published quesadilla · 11.6 oz',portionB:'One published quesadilla · 11.6 oz',destination:'el-pollo-loco-nutrition-guide.html',character:'tomato'},
 {id:'05-noodles-fiber',chain:'Noodles & Company',a:'Japanese Pan Noodles, regular',b:'Pasta Fresca, regular',title:'Regular-size noodle choices',context:'Add-on proteins are excluded unless named in the dish.',detail:'Pasta Fresca lists 5 g more fiber and 770 mg less sodium.',metric:'f',portionA:'One regular dish · no add-on protein',portionB:'One regular dish · no add-on protein',destination:'noodles-regular-noodle-orders-not-addons.html',character:'broccoli'},
 {id:'06-noodles-salads',chain:'Noodles & Company',a:'Mediterranean Chicken Salad, regular',b:'Chicken Caesar Salad, regular',title:'Lower calories ≠ lower sodium',context:'Both are regular-size salads from the same source edition.',detail:'Mediterranean has 240 fewer kcal, but 190 mg more sodium.',metric:'na',portionA:'One regular Mediterranean salad',portionB:'One regular chicken Caesar salad',destination:'noodles-two-chicken-salads.html',character:'avocado'},
 {id:'07-in-n-out-spread',chain:'In-N-Out',a:'Hamburger with onion',b:'Hamburger with onion, mustard and ketchup instead of spread',title:'A published spread swap',context:'Use the restaurant’s listed version—not an estimated edit.',detail:'Mustard and ketchup: 60 fewer kcal, with the same 16 g protein.',metric:'fat',portionA:'One hamburger with onion · 209 g',portionB:'One alternate hamburger · 202 g',destination:'in-n-out-three-published-hamburger-versions.html',character:'egg'},
 {id:'08-in-n-out-protein-style',chain:'In-N-Out',a:'Double-Double with onion',b:'Double-Double with onion, Protein Style (lettuce instead of bun)',title:'Read past “Protein Style”',context:'The lettuce-wrap name does not mean more grams of protein.',detail:'The listed lettuce-wrap version has 150 fewer kcal and 4 g less protein.',metric:'c',portionA:'One Double-Double with onion · 287 g',portionB:'One lettuce-wrap Double-Double · 289 g',destination:'burger-variants-not-nine-base-burgers.html',character:'steak'},
 {id:'09-culvers-chicken',chain:'Culver’s',a:'Grilled Chicken Sandwich',b:'Crispy Chicken Sandwich',title:'Grilled or crispy?',context:'Sandwiches only; fries and drinks are not included.',detail:'Grilled lists 210 fewer kcal and 8 g more protein.',metric:'na',portionA:'One published grilled sandwich',portionB:'One published crispy sandwich',destination:'culvers-chicken-grilled-crispy-spicy.html',character:'chicken'},
 {id:'10-culvers-tenders',chain:'Culver’s',a:'Chicken Tenders, Original - 4 Piece',b:'Chicken Tenders, Buffalo - 4 Piece',title:'Four tenders, two recipes',context:'Use the same piece count before comparing the flavors.',detail:'Both list 39 g protein; buffalo lists 450 mg more sodium.',metric:'na',portionA:'Four original tenders · no extra sides',portionB:'Four buffalo tenders · no extra sides',destination:'culvers-nutrition-guide.html',character:'carrot'},
 {id:'11-taco-johns-western',chain:'Taco John’s',a:'Western Gold Grilled Burrito, Beef',b:'Western Gold Grilled Burrito, Chicken',title:'More protein, more sodium',context:'Two published Western Gold Grilled Burrito builds.',detail:'Chicken lists 7 g more protein and 160 mg more sodium.',metric:'na',portionA:'One published beef burrito',portionB:'One published chicken burrito',destination:'taco-johns-nutrition-guide.html',character:'steak'},
 {id:'12-taco-johns-bound',chain:'Taco John’s',a:'Crispy Taco, Chicken',b:'Crispy Taco, Refried Beans',title:'“Less than 1” is not zero',context:'The chicken taco’s exact fiber value is not published.',detail:'Chicken fiber is <1 g; beans are 4 g. Keep that bound visible.',metric:'f',portionA:'One published crispy chicken taco',portionB:'One published crispy refried-bean taco',destination:'taco-johns-small-fiber-bound.html',character:'beans'},
 {id:'13-del-taco-guac',chain:'Del Taco',a:'Grilled Chicken Street Taco',b:"Grilled Chicken Street Guac'd Up Taco",title:'The named guacamole build',context:'Compare the two listed street tacos—not a guessed scoop.',detail:'The Guac’d Up build adds 20 kcal and lists 2 g more fiber.',metric:'f',portionA:'One chicken street taco · 90 g',portionB:'One Guac’d Up chicken taco · 107 g',destination:'del-taco-nutrition-guide.html',character:'avocado'},
 {id:'14-del-taco-portion',chain:'Del Taco',a:'Grilled Chicken Street Taco',b:'Beer Battered Fish Taco',title:'One taco is not one size',context:'The fish taco is 157 g; the chicken street taco is 90 g.',detail:'Compare actual portions. These are not equal-size samples.',metric:'na',portionA:'One chicken street taco · 90 g',portionB:'One battered fish taco · 157 g',destination:'protein-sort-vs-portion-mass.html',character:'shrimp'},
 {id:'15-arbys-reuben',chain:'Arby’s',a:'Ham & Swiss Melt',b:'Reuben',title:'A sandwich is not a standard unit',context:'One melt is 167 g; one Reuben is 308 g.',detail:'Reuben has 11 g more protein, alongside 300 more kcal.',metric:'na',portionA:'One Ham & Swiss Melt · 167 g',portionB:'One Reuben · 308 g',destination:'arbys-nutrition-guide.html',character:'potato'},
 {id:'16-arbys-two-sliders',chain:'Arby’s',a:'Classic Roast Beef',b:'Roast Beef Slider',bCount:2,title:'Count the whole order',context:'Two sliders are calculated from two published single portions.',detail:'Both are 360 kcal. Two sliders have 1 g less protein and 70 mg more sodium.',metric:'na',portionA:'One Classic Roast Beef · 154 g',portionB:'Two roast beef sliders · 2 × 77 g',destination:'arbys-sliders-count-whole-tray.html',character:'egg'},
 {id:'17-panda-entrees',chain:'Panda Express',a:'String Bean Chicken Breast',b:'Grilled Teriyaki Chicken',title:'Compare the entrée first',context:'Entrées only; rice, noodles and vegetables are not included.',detail:'Teriyaki lists 23 g more protein; string bean chicken has 3 g more fiber.',metric:'f',portionA:'One chicken-and-bean entrée · 5.6 oz',portionB:'One teriyaki chicken entrée · 6.1 oz',destination:'panda-express-chicken-entree-comparison.html',character:'broccoli'},
 {id:'18-panda-add-side',chain:'Panda Express',a:'Grilled Teriyaki Chicken',b:'Grilled Teriyaki Chicken with Super Greens',title:'A side changes the total',context:'Second total: calculated full portions; extra sauce excluded.',detail:'The side adds 180 kcal, 8 g protein, 8 g fiber and 660 mg sodium.',metric:'f',portionA:'One teriyaki entrée · 6.1 oz',portionB:'6.1 oz chicken + 10 oz Super Greens',destination:'panda-express-healthy-meals-macros.html',character:'broccoli'},
 {id:'19-cava-bowls',chain:'CAVA',a:'Greek Salad bowl',b:'Chicken + Rice bowl',title:'Same sodium. Different bowls.',context:'These are the restaurant’s named U.S. bowl recipes.',detail:'Both list 1,830 mg sodium. Chicken + Rice adds 125 kcal and 3 g protein.',metric:'na',portionA:'One complete Greek Salad bowl',portionB:'One complete Chicken + Rice bowl',destination:'cava-healthy-meals-macros.html',character:'tomato'},
 {id:'20-sweetgreen-bowls',chain:'Sweetgreen',a:'Chicken Pesto Parm',b:'Harvest Bowl',title:'Protein is only one number',context:'Use the named bowls and their listed serving recipes.',detail:'Harvest has 2 g more protein and 295 mg less sodium, with 250 more kcal.',metric:'na',portionA:'One complete bowl · 420 g · dressing in',portionB:'One complete bowl · 425 g · dressing in',destination:'sweetgreen-healthy-meals-macros.html',character:'apple'}
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const wrap=(s,n)=>{const words=String(s).split(/\s+/),lines=[];let line='';for(let word of words){if(line && (line+' '+word).length>n){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);return lines;};
const font=(name,file,weight)=>`@font-face{font-family:${name};src:url(data:font/woff2;base64,${fs.readFileSync(path.join(root,file)).toString('base64')}) format('woff2');font-weight:${weight};font-display:block}`;
const fontStyle=font('Bricolage','fonts/bricolage-latin.woff2','500 600')+font('Inter','fonts/inter-latin-400-normal.woff2','400')+font('Inter','fonts/inter-latin-600-normal.woff2','600');
fs.writeFileSync(path.join(out,'brand-fonts.css'),fontStyle);
const characterFile=fs.readFileSync(path.join(root,'images/food-characters.svg'),'utf8');
function character(id){let symbol=characterFile.match(new RegExp(`<symbol id="food-${id}"[^>]*>([\\s\\S]*?)<\\/symbol>`));assert(symbol,`Missing original character ${id}`);return `<g aria-hidden="true" transform="translate(874 67) scale(.83)">${symbol[1]}</g>`;}
const text=(s,x,y,size=30,fill='#233c2c',display=false,weight=400)=>`<text x="${x}" y="${y}" font-family="${display?'Bricolage':'Inter'}" font-size="${size}" font-weight="${weight}" fill="${fill}">${esc(s)}</text>`;
const textLines=(s,x,y,size,n,height,display=false,weight=400)=>wrap(s,n).map((line,i)=>text(line,x,y+i*height,size,'#233c2c',display,weight)).join('');
const format=n=>Number.isInteger(n)?n.toLocaleString('en-US'):String(n);
const units={cal:'kcal',p:'g',c:'g',fat:'g',f:'g',na:'mg'},labels={cal:'Calories',p:'Protein',c:'Carbohydrate',fat:'Fat',f:'Fiber',na:'Sodium'};
function metricValue(m,k){if(m[k]==null){const bound=m.nutrientProvenance?.[k]?.publishedBound;return bound?bound+' '+units[k]:'Unknown';}return format(m[k])+' '+units[k];}
function sum(m,count){if(count===1)return {...m,count:1};let n={...m,count};for(let k of Object.keys(units))n[k]=m[k]==null?null:m[k]*count;return n;}
const manifest=[];
for(const config of configurations){
 const match=name=>{let records=window.GM_MEALS.filter(m=>m.chain===config.chain&&m.name===name);assert.equal(records.length,1,`${config.id}: unambiguous record`);return records[0];};
 const a=match(config.a),b=match(config.b),rows=[sum(a,1),sum(b,config.bCount||1)];
 assert.equal(a.region,'U.S.');assert.equal(b.region,'U.S.');assert.match(a.checked,/^2026-10-0[34]$/);assert.match(b.checked,/^2026-10-0[34]$/);
 const detail=config.detail.replace(/\{(cal|p|na)\}/g,(_,k)=>format(rows[1][k]-rows[0][k]));
 const stats=['cal','p',config.metric],destination='https://getmacros.net/'+config.destination;
 const title=`${config.chain}: ${config.title}`,dates=[...new Set(rows.map(m=>m.checked))].join(' / '),editions=[...new Set(rows.map(m=>m.sourceDate).filter(Boolean))].join(' / ');
 const meta={status:'distribution draft; not posted',created:'2026-10-09',title,destination,sourceChecked:dates,sourceEdition:editions||'not stated',country:'U.S.',records:rows,detail,sourceFiles,currentOfficialRecheckPerformed:false};
 const leftName=a.name,rightName=(config.bCount?'2 × ':'')+b.name;
 const sourceLabel=`Source checked ${dates} · U.S. portions`,editionLabel=`Source edition: ${editions||'not stated'} · verify availability and current recipe`;
 let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350" role="img" aria-labelledby="title desc"><title id="title">${esc(title)}</title><desc id="desc">${esc(detail+' '+sourceLabel+'. '+a.serving+'. '+b.serving+'. Official source URLs and snapshot details are in the metadata and manifest.')}</desc><metadata>${esc(JSON.stringify(meta))}</metadata><style>${fontStyle}text{font-variant-numeric:tabular-nums}</style><rect width="1080" height="1350" fill="#fffdf8"/>`;
 svg+=text('GetMacros',64,68,34,'#2c6443',true,600)+character(config.character)+text(config.chain,64,129,26,'#2c6443',false,600);
 svg+=textLines(config.title,64,211,56,28,62,true,600)+textLines(config.context,64,320,26,69,36);
 svg+='<path d="M64 374H1016" stroke="#dbe4d5" stroke-width="2"/>';
 svg+=textLines(leftName,64,427,31,28,39,true,600)+textLines(rightName,566,427,31,28,39,true,600);
 svg+=textLines(config.portionA,64,556,23,38,29)+textLines(config.portionB,566,556,23,38,29);
 stats.forEach((k,i)=>{let y=662+i*130;svg+=text(labels[k],64,y-48,24,'#56705b')+text(metricValue(rows[0],k),64,y+9,58,'#233c2c',true,600)+text(metricValue(rows[1],k),566,y+9,58,'#233c2c',true,600);if(i<2)svg+=`<path d="M64 ${y+37}H1016" stroke="#e2e9dc"/>`;});
 svg+='<path d="M64 996H1016" stroke="#2c6443" stroke-width="2"/>'+textLines(detail,64,1046,29,61,39,true,500);
 svg+=text(sourceLabel,64,1220,22)+text(editionLabel,64,1251,20,'#56705b');
 svg+=`<a href="${esc(destination)}">${text('Read the comparison → getmacros.net',64,1304,24,'#2c6443',false,600)}</a><a href="${esc(a.source)}">${text('Official source ↗',810,1304,20,'#2c6443')}</a></svg>`;
 const file=`graphics/${config.id}.svg`;fs.writeFileSync(path.join(out,file),svg);
 const shareFile=`share-previews/${config.id}.svg`;
 let share=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630" role="img" aria-labelledby="title desc"><title id="title">${esc(title)}</title><desc id="desc">${esc(detail+' '+sourceLabel+'. Read the full comparison for exact portions and recipe limits.')}</desc><metadata>${esc(JSON.stringify(meta))}</metadata><style>${fontStyle}text{font-variant-numeric:tabular-nums}</style><rect width="1200" height="630" fill="#fffdf8"/>`;
 share+=text('GetMacros · '+config.chain,48,55,27,'#2c6443',true,600)+`<g aria-hidden="true" transform="translate(1095 7) scale(.5)">${characterFile.match(new RegExp(`<symbol id="food-${config.character}"[^>]*>([\\s\\S]*?)<\\/symbol>`))[1]}</g>`;
 share+=textLines(config.title,48,122,47,43,54,true,600)+'<path d="M48 194H1152" stroke="#dbe4d5"/>';
 share+=textLines(leftName,48,234,30,33,35,true,600)+textLines(rightName,634,234,30,33,35,true,600);
 share+=textLines(config.portionA,48,366,21,44,26)+textLines(config.portionB,634,366,21,44,26);
 share+=text(metricValue(rows[0],'cal'),48,449,53,'#233c2c',true,600)+text(metricValue(rows[1],'cal'),634,449,53,'#233c2c',true,600);
 share+=text(metricValue(rows[0],'p')+' protein',48,495,29,'#2c6443')+text(metricValue(rows[1],'p')+' protein',634,495,29,'#2c6443');
 share+='<path d="M48 530H1152" stroke="#dbe4d5"/>'+text(sourceLabel,48,565,21)+text('Exact recipes, sources and limits → getmacros.net',48,600,22,'#2c6443',false,600)+'</svg>';
 fs.writeFileSync(path.join(out,shareFile),share);
 manifest.push({...meta,id:config.id,file,png:file.replace('.svg','.png'),sharePreview:{svg:shareFile,png:shareFile.replace('.svg','.png'),dimensions:[1200,630],nutritionScope:'Calories and protein only; caption and full comparison retain other nutrients and source limits.'},character:`food-${config.character}`,displayedNames:[leftName,rightName],displayedPortions:[config.portionA,config.portionB],metrics:stats.map(k=>({field:k,label:labels[k],left:metricValue(rows[0],k),right:metricValue(rows[1],k)})),caption:`${title}. ${detail} U.S. menu snapshot, source checked ${dates}. Portions differ where stated; not a health rating. Read exact builds and source limits: ${destination}`,publicationGate:'Review current official menu, portion, availability and source edition before posting. Artwork is ingredient character art, not a restaurant order photograph.'});
}
assert.equal(manifest.length,20);assert.equal(new Set(manifest.map(x=>x.destination)).size,20);
fs.writeFileSync(path.join(out,'graphics-manifest.json'),JSON.stringify({created:'2026-10-09',status:'drafts not posted',datasetCountAtCreation:window.GM_MEALS.length,sourceFiles,rights:{art:'Original GetMacros food-character vectors; no restaurant logos or product photos.',fonts:'Self-hosted OFL Bricolage Grotesque and Inter, existing repository licenses.',originalGraphicComposition:'Created in this repository on 2026-10-09.'},sourceFreshness:'Uses the existing inspected Oct 3–4 snapshots, not a new official check on Oct 9. Current recheck is a posting gate.',graphics:manifest},null,2));
const cell=s=>'"'+String(s).replaceAll('"','""')+'"';
const csv=[['id','title','destination','country','recorded_source_check','official_source_urls','order_names','serving_definitions','portrait_svg','portrait_png','share_preview_png','publication_status'],...manifest.map(m=>[m.id,m.title,m.destination,m.country,m.sourceChecked,[...new Set(m.records.map(r=>r.source))].join(' | '),m.records.map(r=>r.count+' × '+r.name).join(' | '),m.records.map(r=>r.serving).join(' | '),m.file,m.png,m.sharePreview.png,m.status])].map(row=>row.map(cell).join(',')).join('\r\n');
fs.writeFileSync(path.join(out,'graphics-manifest.csv'),csv+'\r\n');
const cards=manifest.map(m=>`<article><a href="${m.file}"><img src="${m.file}" alt="${esc(m.title)}" width="1080" height="1350" loading="lazy"/></a><h2>${esc(m.title)}</h2><p>${esc(m.caption)}</p><a href="${esc(m.destination)}">Open existing resource</a><details><summary>Exact source trail and portion limits</summary>${m.records.map(r=>`<p><strong>${esc(r.count+' × '+r.name)}</strong>: ${esc(r.serving)}. Checked ${esc(r.checked)}. ${esc(r.notes||'')} <a href="${esc(r.source)}">Official source</a></p>`).join('')}</details></article>`).join('');
fs.writeFileSync(path.join(out,'preview.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>GetMacros distribution drafts · October 9, 2026</title><link rel="stylesheet" href="brand-fonts.css"><style>*{box-sizing:border-box}body{font-family:Inter,Arial,sans-serif;margin:0;background:#fffdf8;color:#233c2c}main{max-width:1440px;margin:auto;padding:clamp(16px,4vw,64px)}h1,h2{font-family:Bricolage,Arial,sans-serif;font-weight:600}h1{font-size:clamp(32px,4vw,54px);max-width:800px}p{line-height:1.6;overflow-wrap:anywhere}a{color:#2c6443;text-underline-offset:4px}a:focus-visible,summary:focus-visible{outline:3px solid #2c6443;outline-offset:4px}header{margin-bottom:48px;max-width:840px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,320px),1fr));gap:48px 28px}article{min-width:0}img{display:block;width:100%;height:auto;border:1px solid #dbe4d5;border-radius:12px}h2{font-size:25px;line-height:1.2}details{margin-top:20px}summary{cursor:pointer;padding:12px 0}footer{margin-top:64px;border-top:1px solid #dbe4d5;padding-top:24px}@media(prefers-reduced-motion:no-preference){a{transition:color .16s}a:hover{color:#173b27}}</style></head><body><main><header><h1>Comparison graphics, ready for review.</h1><p>20 original graphics based on existing U.S. menu snapshots. These are distribution drafts; none have been posted. Dates below are actual recorded source-check dates, not a claim that menus were rechecked today.</p><p><a href="graphics-manifest.json">Exact data and sources</a> · <a href="drafts.html">Video, newsletter and outreach drafts</a> · <a href="verification.json">Verification results</a></p></header><section class="grid">${cards}</section><footer><p>Original ingredient characters are illustrative brand art, not photographs of the named orders. Menu prices, allergy safety and availability are not inferred. Refresh official source checks before posting.</p></footer></main></body></html>`);
console.log(JSON.stringify({graphics:manifest.length,destinations:new Set(manifest.map(x=>x.destination)).size,records:new Set(manifest.flatMap(x=>x.records.map(r=>r.chain+'||'+r.name))).size,out}));
