// Original distribution writing. This file creates drafts only; it sends nothing.
const fs=require('node:fs'),path=require('node:path');
const out=path.resolve(__dirname,'../../../docs/growth-release-2026-10-09/distribution');
const graphics=JSON.parse(fs.readFileSync(path.join(out,'graphics-manifest.json'),'utf8')).graphics;
const url=route=>'https://getmacros.net/'+route;
const scripts=[
 {id:'video-01',title:'A bowl and burrito are two published builds',graphic:'01-qdoba-bowl-burrito',destination:url('qdoba-burrito-bowl-published-pair.html'),shots:[
  {seconds:'0–5',visual:'Egg character leans toward the two exact order names. No restaurant product photograph.',voice:'Chicken Queso Bowl or Chicken Queso Burrito? Compare the published builds first.'},
  {seconds:'5–14',visual:'Show 750 kcal / 43 g protein on the bowl; 1,050 kcal / 51 g on the burrito. Keep U.S. and portion weights visible.',voice:'The bowl lists 750 calories and 43 grams of protein. The burrito lists 1,050 and 51.'},
  {seconds:'14–22',visual:'Show the exact 468 g and 569 g portions, then the 300 kcal difference.',voice:'That is 300 more calories and eight more grams of protein. It does not tell us what a custom tortilla removal would do.'},
  {seconds:'22–30',visual:'Source checked October 4, 2026. Link to the published pair article.',voice:'See the exact portions and source at GetMacros. These are U.S. menu snapshots; recipes can change.'}]},
 {id:'video-02',title:'Read past the name Protein Style',graphic:'08-in-n-out-protein-style',destination:url('burger-variants-not-nine-base-burgers.html'),shots:[
  {seconds:'0–5',visual:'Steak character points at the words Protein Style, then the actual protein number.',voice:'A menu name is not a protein measurement.'},
  {seconds:'5–15',visual:'Double-Double with onion: 610 kcal, 34 g protein. Lettuce-wrap published version: 460 kcal, 30 g protein.',voice:'These published Double-Double versions list 34 grams of protein with the bun and 30 in the lettuce-wrap version.'},
  {seconds:'15–23',visual:'Show 150 fewer kcal and 4 g less protein. No good/bad color coding.',voice:'The lettuce-wrap version is 150 calories lower. It also lists four fewer grams of protein.'},
  {seconds:'23–30',visual:'U.S. source, January 2026 PDF edition; checked October 4. Link to full variant explanation.',voice:'Use the full recipe and portion, not just the name. The source and edition are linked at GetMacros.'}]},
 {id:'video-03',title:'Lower calories need not mean lower sodium',graphic:'06-noodles-salads',destination:url('noodles-two-chicken-salads.html'),shots:[
  {seconds:'0–5',visual:'Avocado character separates calorie and sodium labels.',voice:'One number cannot answer every ordering question.'},
  {seconds:'5–15',visual:'Regular Mediterranean Chicken Salad: 430 kcal / 1,700 mg sodium. Regular Chicken Caesar: 670 kcal / 1,510 mg.',voice:'These regular salads show the trade-off: Mediterranean has 430 calories and 1,700 milligrams of sodium. Caesar has 670 and 1,510.'},
  {seconds:'15–23',visual:'Show 240 fewer kcal but 190 mg more sodium. Keep regular size visible.',voice:'So the lower-calorie salad is not the lower-sodium salad in this snapshot.'},
  {seconds:'23–30',visual:'Source checked October 4, 2026. Link to exact regular dishes; no added protein assumption.',voice:'Compare the published regular dishes and check current availability. The exact source is in our comparison.'}]},
 {id:'video-04',title:'Two sliders are an order',graphic:'16-arbys-two-sliders',destination:url('arbys-sliders-count-whole-tray.html'),shots:[
  {seconds:'0–5',visual:'Egg character moves two numbered slider labels together. No branded product artwork.',voice:'If you order two, compare two.'},
  {seconds:'5–15',visual:'One Roast Beef Slider: 180 kcal / 11 g protein. Multiply the full row by two.',voice:'The recorded roast beef slider lists 180 calories and 11 grams of protein. Two give a calculated 360 calories and 22 grams.'},
  {seconds:'15–23',visual:'One Classic Roast Beef: 360 kcal / 23 g protein. Sodium: 970 mg versus calculated 1,040 mg.',voice:'The Classic Roast Beef has the same listed calories, one more gram of protein and 70 milligrams less sodium than two sliders.'},
  {seconds:'23–30',visual:'Label slider total calculated from individual portions. Actual source checked October 4; June 2026 printed edition.',voice:'These are individual U.S. portions, with no fries or drink. The source and calculation are linked at GetMacros.'}]},
 {id:'video-05',title:'Keep less-than bounds',graphic:'12-taco-johns-bound',destination:url('taco-johns-small-fiber-bound.html'),shots:[
  {seconds:'0–5',visual:'Bean character holds the exact text <1 g. Do not count up from zero.',voice:'Less than one gram is not the same as zero.'},
  {seconds:'5–15',visual:'Crispy Taco, Chicken: fiber <1 g. Crispy Taco, Refried Beans: fiber 4 g.',voice:'The source lists less than one gram of fiber for this chicken taco, and four grams for the refried-bean version.'},
  {seconds:'15–23',visual:'Do not show a decimal gap or a fake exact total. Explain the bound in one sentence.',voice:'We keep the chicken value as a bound. We cannot honestly calculate an exact fiber gap from that row.'},
  {seconds:'23–30',visual:'U.S. portions, source checked October 4. Link to source-bound explanation.',voice:'See how GetMacros handles missing and bounded menu values. A blank or a bound is not a guessed zero.'}]},
 {id:'video-06',title:'Use your receipt for protein value',destination:url('protein-value-calculator.html'),shots:[
  {seconds:'0–5',visual:'Broccoli character beside the existing protein-value tool. Show a user-entered example labeled illustrative.',voice:'Which order gives more protein for your money? Start with your actual price.'},
  {seconds:'5–14',visual:'Demonstration only: $6, 30 g protein. Then $8, 32 g. Use the same currency and quantity basis.',voice:'In this made-up arithmetic example, six dollars for 30 grams is twenty cents per gram. Eight dollars for 32 grams is twenty-five cents.'},
  {seconds:'14–22',visual:'Show price ÷ total protein. Clearly label example prices not restaurant prices.',voice:'Those are examples, not menu prices. Enter your receipt price and the protein for the exact quantity you bought.'},
  {seconds:'22–30',visual:'Tool URL and reminder to use one currency and a consistent fee basis.',voice:'Try the existing GetMacros protein-value calculator. Keep currency, quantity and included fees consistent.'}]},
 {id:'video-07',title:'Scale the portion you actually use',destination:url('recipe-macro-scaler.html'),shots:[
  {seconds:'0–5',visual:'Egg character divides one illustrated batch into labeled portions. No claimed photographed recipe.',voice:'A batch total is not a portion total.'},
  {seconds:'5–15',visual:'Illustrative arithmetic: batch 800 kcal and 40 g protein; four equal portions.',voice:'For an example batch with 800 calories and 40 grams of protein, four equal portions give 200 calories and 10 grams each.'},
  {seconds:'15–23',visual:'Emphasize equal portions and unchanged included ingredients. No imaginary nutrient loss.',voice:'That assumes the ingredients are evenly distributed and the batch total includes what you actually used.'},
  {seconds:'23–30',visual:'Open the existing recipe scaler and link to unequal-portions explanation.',voice:'Use the GetMacros recipe scaler for your recorded batch. If portions differ, compare actual weights or components.'}]},
 {id:'video-08',title:'Compare the same label basis',destination:url('nutrition-label-comparison-tool.html'),shots:[
  {seconds:'0–5',visual:'Two neutral label diagrams. Strawberry character reads the serving lines.',voice:'Before comparing two labels, read the serving size.'},
  {seconds:'5–15',visual:'Example A: 10 g protein per 100 g. Example B: 8 g per 50 g. Mark hypothetical values.',voice:'In this example, ten grams of protein per hundred grams is not directly comparable with eight grams per fifty grams.'},
  {seconds:'15–23',visual:'Show B multiplied by two: 16 g per 100 g. Preserve label rounding note.',voice:'On a hundred-gram basis, the second example becomes sixteen grams. Published label values may still be rounded.'},
  {seconds:'23–30',visual:'Link to the existing food-label comparison tool. No product names or health claim.',voice:'Use the GetMacros label tool to compare the amounts you actually eat. Match the basis before judging the numbers.'}]}
];
const newsletters=[
 {id:'newsletter-01',subject:'Bowl, burrito, or a different serving?',preheader:'Start with the exact published build.',destinations:[url('qdoba-burrito-bowl-published-pair.html'),url('el-pollo-loco-tortilla-complete-chicken-meal.html'),url('compare-complete-restaurant-orders.html')],body:[
  'A bowl and a burrito can sound like the same lunch in different wrapping. The published rows do not necessarily describe an ingredient-for-ingredient swap.',
  'In our existing U.S. QDOBA snapshot, Chicken Queso Bowl lists 750 kcal and 43 g protein. Chicken Queso Burrito lists 1,050 kcal and 51 g protein. Their recorded portions are 468 g and 569 g. The difference is between those two complete builds; it does not prove the nutrition of a custom burrito with its tortilla removed.',
  'Read the QDOBA published-pair comparison for exact numbers and sources. Our El Pollo Loco tortilla comparison takes another useful case: a complete breast-and-wing meal with corn tortillas versus its published flour-tortilla version.',
  'When comparing your order, keep the entrée, side, sauce, drink, portion and country visible. The complete-order explanation shows why that boundary matters. These are source snapshots, not promises that every location uses an unchanged recipe.'
 ]},
 {id:'newsletter-02',subject:'Protein is useful. It is not the whole comparison.',preheader:'Three ways to read beyond one number.',destinations:[url('noodles-two-chicken-salads.html'),url('burger-variants-not-nine-base-burgers.html'),url('fast-food-protein-and-sodium.html')],body:[
  'A higher protein number can help answer one question. It cannot tell you everything about the size or composition of an order.',
  'The two regular Noodles & Company chicken salads illustrate why. Our recorded Mediterranean Chicken Salad has 430 kcal and 1,700 mg sodium; Chicken Caesar has 670 kcal and 1,510 mg. The lower-calorie dish is not the lower-sodium dish in that source edition.',
  'Menu wording needs the same care. In-N-Out’s published Double-Double with onion lists 34 g protein, while its Protein Style version lists 30 g. Protein Style describes the lettuce-wrap recipe; it is not a claim that the order contains more grams of protein.',
  'The linked comparisons keep portions and source dates beside the values. Our protein-and-sodium guide is a practical next step when both numbers matter to your ordering decision. There is no universal winner or personalized health score here—just enough information to compare the actual choices.'
 ]},
 {id:'newsletter-03',subject:'Your receipt is better than a guessed price',preheader:'A useful protein-value calculation, using your own numbers.',destinations:[url('protein-value-calculator.html'),url('restaurant-protein-cost-receipt-prices.html'),url('protein-cost-currency-comparison.html')],body:[
  'Restaurant prices change by location, delivery service, promotion and quantity. We do not attach a made-up price to a nutrition row.',
  'For a comparison you can use, enter the price you paid and the protein for the exact quantity. Price divided by total protein gives cost per gram. As arithmetic only—not real menu prices—$6 for 30 g protein is $0.20 per gram; $8 for 32 g is $0.25 per gram.',
  'Open the protein-value calculator and replace those examples with your own receipt numbers. Use one currency and the same fee basis on both sides. If one price includes delivery and the other does not, the calculation still works, but you are comparing different purchasing conditions.',
  'The receipt-price guide explains the quantity boundary. The currency guide explains why two currency symbols cannot be treated as interchangeable. You do not need a guessed national price list to make a clear comparison of the order in front of you.'
 ]},
 {id:'newsletter-04',subject:'A missing nutrition value is not zero',preheader:'Keep portions, bounds and source dates visible.',destinations:[url('taco-johns-small-fiber-bound.html'),url('nutrition-label-comparison-tool.html'),url('recipe-macro-scaler.html'),url('saved-meal-source-version-check.html')],body:[
  'Sometimes a source publishes an exact value. Sometimes it gives a bound, and sometimes it leaves a field unavailable. Those are different kinds of information.',
  'Our Taco John’s source snapshot lists less than 1 g fiber for Crispy Taco, Chicken. We preserve that bound instead of displaying an invented zero. The refried-bean version lists 4 g. You can compare the rows without pretending that the chicken’s exact fiber amount is known.',
  'The same habit helps with labels and recipes. Match the serving basis before comparing two labels. Divide a recipe total only when your portion assumption fits what you actually served. The label comparison tool and recipe scaler make those calculations explicit.',
  'If you save a meal for later, revisit its source version too. A saved record is useful as a notebook entry; it is not a guarantee that a menu stays unchanged. The linked saved-meal guide explains what to check when you return.'
 ]}
];
const outreach=[
 {id:'outreach-01',audience:'Food-service or restaurant-decision editor with an existing portion-comparison resource',subject:'A sourced bowl-versus-burrito comparison for your portion guide',destination:url('qdoba-burrito-bowl-published-pair.html'),body:'Hello,\n\nI maintain GetMacros, a restaurant meal comparison resource. Your portion-comparison coverage may find this specific example useful: QDOBA’s published Chicken Queso Bowl and Burrito, with the exact U.S. portions and an explicit warning that the two rows are not proof of a custom tortilla removal.\n\nThe comparison and official source trail are here: '+url('qdoba-burrito-bowl-published-pair.html')+'\n\nIf you cover this topic, you are welcome to review the method and tell me if an assumption needs correcting. I can provide our original comparison graphic with its recorded source date. No link or endorsement is expected.\n\nGetMacros'},
 {id:'outreach-02',audience:'Budget-food writer with a relevant article about variable local restaurant prices',subject:'A receipt-based protein-value tool, without guessed menu prices',destination:url('protein-value-calculator.html'),body:'Hello,\n\nI maintain GetMacros. We have a protein-value calculator that uses the reader’s own price and quantity, so a local receipt can be compared without assuming a national menu price. It shows the cost per gram and makes the currency and quantity basis explicit.\n\nThe existing tool is here: '+url('protein-value-calculator.html')+'\n\nIf this fits your budget-food coverage, please try it and let me know whether the inputs or explanation could be clearer. I would be glad to provide an original example graphic with clearly hypothetical prices. No placement or endorsement is requested.\n\nGetMacros'},
 {id:'outreach-03',audience:'Public food-literacy or label-education program maintaining a tool directory',subject:'A practical label-portion comparison tool for review',destination:url('nutrition-label-comparison-tool.html'),body:'Hello,\n\nI maintain the informational GetMacros website. Our label comparison tool lets readers compare the quantities they actually eat rather than comparing two unequal label servings. We also explain rounding and unavailable values.\n\nHere is the tool for your review: '+url('nutrition-label-comparison-tool.html')+'\n\nIt is not a medical service and has no clinical endorsement. If it would be useful alongside your label-education materials, I would appreciate any feedback on the serving explanation. Please review it independently before deciding whether to include it.\n\nGetMacros'},
 {id:'outreach-04',audience:'Meal-preparation writer discussing uneven recipe portions',subject:'A recipe portion scaler and a clear unequal-serving explanation',destination:url('recipe-macro-scaler.html'),body:'Hello,\n\nI maintain GetMacros. Our recipe portion scaler works from entered batch nutrition and portion counts, with a separate explanation of why equal portions and unequal component servings are different assumptions.\n\nThe calculator is here: '+url('recipe-macro-scaler.html')+'\nThe unequal-portion explanation is here: '+url('unequal-recipe-portions.html')+'\n\nIf that distinction is relevant to your meal-preparation coverage, please review the tool. I can provide an original arithmetic illustration; it would not imply a tested recipe or a clinical recommendation. No reciprocal link or endorsement is expected.\n\nGetMacros'},
 {id:'outreach-05',audience:'Data-transparency or consumer-information writer covering menu-data limits',subject:'An example of retaining a less-than nutrition bound',destination:url('taco-johns-small-fiber-bound.html'),body:'Hello,\n\nI maintain GetMacros. We have a small, concrete explanation of a menu-data problem: a published fiber value of less than 1 g should not silently become zero or an invented decimal. The page links the U.S. source row and describes the limit of comparison.\n\nThe resource is here: '+url('taco-johns-small-fiber-bound.html')+'\n\nIf you cover consumer-data transparency, I would welcome a method review or correction. We can supply an original ingredient-character graphic with the recorded source date. I am not asking for a paid placement, endorsement or reciprocal link.\n\nGetMacros'}
];
const gate='Draft only. Not sent, posted, scheduled or subscribed. Before use: review current official data for numerical claims, confirm destination still works, choose the actual audience and obtain owner approval. Newsletter use also requires a real consented list, sender details and unsubscribe mechanism; no list or subscription feature is implied.';
const result={created:'2026-10-09',status:'all drafts, not distributed',gate,videoScripts:scripts.map(s=>({...s,status:'unproduced script; not posted',sourceGraphic:s.graphic?graphics.find(g=>g.id===s.graphic).file:null,sourceRecords:s.graphic?graphics.find(g=>g.id===s.graphic).records.map(r=>({name:r.name,region:r.region,checked:r.checked,source:r.source})):[],arithmeticExamples:s.id==='video-06'?[{price:6,proteinGrams:30,result:0.2},{price:8,proteinGrams:32,result:0.25}]:s.id==='video-07'?[{batchCalories:800,batchProteinGrams:40,portions:4,caloriesPerPortion:200,proteinPerPortion:10}]:s.id==='video-08'?[{proteinPer50g:8,proteinPer100g:16}]:[]})),newsletterDrafts:newsletters.map(n=>({...n,status:'not sent; no subscriber list assumed'})),outreachDrafts:outreach.map(o=>({...o,status:'unsent; no actual recipient identified or researched',recipientSelection:'Choose only a demonstrably relevant current resource; personalize after inspecting it. Do not bulk-send this draft.'})),graphics:graphics.map(g=>({id:g.id,caption:g.caption,destination:g.destination,file:g.file})),ownerActions:['Review snapshot freshness before distribution.','Select a real, relevant outreach recipient and approve sending.','Use newsletters only with a consented list and valid unsubscribe/address details.','Produce accessible videos with captions and nonessential motion that respects viewer preferences.','Measure actual referrals only through the existing privacy-respecting analytics configuration; no dietary data in events.']};
fs.writeFileSync(path.join(out,'distribution-drafts.json'),JSON.stringify(result,null,2));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const scriptSections=scripts.map(s=>`<article id="${s.id}"><p class="kind">Video script · about 30 seconds</p><h3>${escape(s.title)}</h3>${s.shots.map(shot=>`<section class="shot"><h4>${escape(shot.seconds)} seconds</h4><p><strong>Visual:</strong> ${escape(shot.visual)}</p><p><strong>Voiceover:</strong> ${escape(shot.voice)}</p></section>`).join('')}<p><a href="${escape(s.destination)}">Existing resource</a>${s.graphic?` · <a href="${escape(graphics.find(g=>g.id===s.graphic).file)}">Original graphic</a>`:''}</p></article>`).join('');
const newsletterSections=newsletters.map(n=>`<article id="${n.id}"><p class="kind">Unsent newsletter draft</p><h3>${escape(n.subject)}</h3><p class="muted">${escape(n.preheader)}</p>${n.body.map(p=>`<p>${escape(p)}</p>`).join('')}<p><strong>Links for this draft</strong></p><ul>${n.destinations.map(d=>`<li><a href="${escape(d)}">${escape(d.replace('https://getmacros.net/','').replace('.html','').replaceAll('-',' '))}</a></li>`).join('')}</ul></article>`).join('');
const outreachSections=outreach.map(o=>`<article id="${o.id}"><p class="kind">Unsent outreach draft · no recipient selected</p><h3>${escape(o.subject)}</h3><p><strong>Relevant audience:</strong> ${escape(o.audience)}</p><div class="email">${o.body.split('\n\n').map(p=>`<p>${escape(p)}</p>`).join('')}</div><p><a href="${escape(o.destination)}">Existing resource</a></p></article>`).join('');
fs.writeFileSync(path.join(out,'drafts.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>GetMacros distribution writing · drafts</title><link rel="stylesheet" href="brand-fonts.css"><style>*{box-sizing:border-box}html{scroll-padding:24px}body{margin:0;background:#fffdf8;color:#233c2c;font:17px/1.65 Inter,Arial,sans-serif}main{max-width:880px;margin:auto;padding:clamp(18px,4vw,56px)}h1,h2,h3,h4{line-height:1.2;font-family:Bricolage,Arial,sans-serif}h1{font-size:clamp(32px,5vw,48px)}h2{font-size:32px;margin-top:80px}h3{font-size:26px}h4{font-size:19px;margin-bottom:12px}article{margin-block:48px 64px;padding-top:28px;border-top:1px solid #dbe4d5}.kind,.muted{color:#56705b}.kind{font-size:15px}a{color:#2c6443;text-underline-offset:4px}a:focus-visible{outline:3px solid #2c6443;outline-offset:4px}p,li{overflow-wrap:anywhere}.shot{margin:26px 0}.email{padding-left:22px;border-left:3px solid #dbe4d5}.email p{white-space:pre-line}nav{display:flex;flex-wrap:wrap;gap:12px 24px}</style></head><body><main><a href="preview.html">← Comparison graphics</a><h1>Useful drafts. Nothing sent.</h1><p>${escape(gate)}</p><nav aria-label="Draft sections"><a href="#videos">8 video scripts</a><a href="#newsletters">4 newsletters</a><a href="#outreach">5 outreach drafts</a></nav><h2 id="videos">Video scripts</h2>${scriptSections}<h2 id="newsletters">Newsletter drafts</h2>${newsletterSections}<h2 id="outreach">Targeted outreach drafts</h2>${outreachSections}<footer><p>Menu figures derive from the recorded Oct 3–4 U.S. snapshots. Actual prices in demonstrations are explicitly hypothetical. No claims of clinical review, personal restaurant testing, subscribers, posting or traffic are made.</p></footer></main></body></html>`);
console.log(JSON.stringify({videoScripts:scripts.length,newsletters:newsletters.length,outreach:outreach.length,status:'drafts only'}));
