/* Browser-only bookmarks. No network, account or identifying events. */
(()=>{'use strict';const key='getmacros-food-shelf-v1',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let items=[];try{const data=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(data))items=data.filter(valid).slice(0,500);}catch{}
function valid(item){return item&&['article','game'].includes(item.kind)&&typeof item.url==='string'&&/^[a-z0-9-]+\.html$/.test(item.url)&&typeof item.title==='string'&&item.title.length<250;}
const has=(kind,url)=>items.some(i=>i.kind===kind&&i.url===url);
function persist(){try{localStorage.setItem(key,JSON.stringify(items));return true;}catch{return false;}}
function toggle(item){if(!valid(item))return false;const before=items.slice(),exists=has(item.kind,item.url);items=exists?items.filter(i=>!(i.kind===item.kind&&i.url===item.url)):[item,...items].slice(0,500);if(!persist()){items=before;return false;}paint();return true;}
function paint(){document.querySelectorAll('[data-shelf-save]').forEach(button=>{const active=has(button.dataset.kind,button.dataset.url);button.setAttribute('aria-pressed',String(active));button.textContent=active?'Saved to your shelf':button.dataset.kind==='game'?'Save this game':'Save this guide';});const root=document.querySelector('#food-shelf');if(!root)return;root.innerHTML='<section class="shelf-section"><h2>Meals</h2><p>Saved orders stay with their portions and full nutrition.</p><a class="text-action" href="'+(window.GetMacrosMarket?.route('finder')||'/restaurant-meal-finder.html')+'?view=saved">Open saved meals →</a></section>'+['article','game'].map(kind=>'<section class="shelf-section" data-shelf-kind="'+kind+'"><h2 tabindex="-1">'+ (kind==='article'?'Good reads':'Little games')+'</h2>'+(items.some(i=>i.kind===kind)?'<div class="shelf-list">'+items.filter(i=>i.kind===kind).map(i=>'<div class="shelf-item"><a href="'+i.url+'">'+esc(i.title)+'</a><button class="quiet-button" type="button" data-shelf-remove="'+i.url+'" data-kind="'+kind+'" aria-label="Remove '+esc(i.title)+' from shelf">Remove</button></div>').join('')+'</div>':'<div class="shelf-empty"><p>Nothing saved here yet.</p><a class="text-action" href="'+(kind==='article'?'articles.html':'play.html')+'">'+(kind==='article'?'Find a read':'Find a game')+' →</a></div>')+'</section>').join('');}
document.addEventListener('click',event=>{const button=event.target.closest('[data-shelf-save],[data-shelf-remove]');if(!button)return;const item={kind:button.dataset.kind,url:button.dataset.url||button.dataset.shelfRemove,title:button.dataset.title||items.find(i=>i.kind===button.dataset.kind&&i.url===button.dataset.shelfRemove)?.title};if(!toggle(item)){let status=document.querySelector('#shelf-status');if(!status){status=document.createElement('p');status.id='shelf-status';status.setAttribute('role','status');button.after(status);}status.textContent='This browser could not save that item. Your existing shelf is unchanged.';}else if(button.dataset.shelfRemove)document.querySelector('[data-shelf-kind="'+item.kind+'"] h2')?.focus();});
addEventListener('storage',event=>{if(event.key!==key)return;try{const data=JSON.parse(event.newValue||'[]');items=Array.isArray(data)?data.filter(valid).slice(0,500):[];paint();}catch{}});
window.GetMacrosShelf=Object.freeze({toggle,has});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',paint,{once:true});else paint();
})();
