/* Restaurant meals the finder ranks.
 *
 * These records hold only what is observed or editorial: the chain, the item,
 * its published numbers, whether it suits a diet, whether it is a breakfast
 * item, and why we think it is worth ordering.
 *
 *   diet  - subset of vegetarian | plant | gluten. Hand-assigned, because no
 *           formula can read an ingredient list.
 *   meal  - breakfast | main. When you eat it, not a dietary restriction. An
 *           earlier version filed "breakfast" alongside vegetarian and gluten,
 *           which put an occasion in a list of things people cannot eat.
 *   null  - the chain does not publish that value in a form we would stand
 *           behind. Deliberately not zero.
 *
 * The `t` array of goal tags is generated, not hand-written:
 * tools/build_meal_finder.py derives it from the numbers above and writes it
 * back here. Hand-assigning them drifted badly, with 41 meals tagged high
 * protein while only 36 reached the 25 g the label promised.
 */
window.GM_THRESHOLDS = {protein:25,energy:600,light:400,fibre:5,sodium:600};

window.GM_MEALS = [
/* Chipotle's current High Protein Menu gives the exact build and published
 * calories/protein/fiber. Carbs and sodium are sums of Chipotle's current
 * ingredient values; light brown rice uses half of the standard portion. */
{chain:'Chipotle',name:'High Protein-High Fiber Bowl',cal:540,p:46,c:66,f:14,na:1645,
 t:['protein','fibre','balanced'],diet:['gluten'],meal:'main',size:'medium',
 url:'chipotle-healthy-meals-macros.html',
 why:'Adobo chicken, light brown rice, black beans, fajita vegetables, corn salsa, tomato salsa and romaine. Carbs and sodium are calculated from Chipotle\'s published ingredient values.'},
/* Current official build: chicken, Supergreens, fajita vegetables, fresh
 * tomato salsa and guacamole. Carbs and sodium are summed from the same
 * current ingredient table; Chipotle publishes calories/protein/fiber. */
{chain:'Chipotle',name:'High Protein-Low Calorie Salad',cal:470,p:36,c:20,f:10,na:1395,
 t:['protein','fibre','balanced'],diet:['gluten'],meal:'main',size:'medium',
 url:'chipotle-healthy-meals-macros.html',
 why:'Adobo chicken, Supergreens, fajita vegetables, fresh tomato salsa and guacamole. Carbs and sodium are calculated from Chipotle\'s published ingredient values.'},
/* The four builds below use exact ingredient combinations so every displayed
 * nutrient, including sodium, can be summed from Chipotle's U.S. ingredient
 * nutrition table instead of relying on an undefined "standard bowl." */
{chain:'Chipotle',name:'Chicken Bowl with white rice and black beans',cal:650,p:48,c:88,f:14,na:1900,
 t:['protein','energy','fibre'],diet:['gluten'],meal:'main',size:'large',
 url:'chipotle-healthy-meals-macros.html',
 why:'Adobo chicken, white rice, black beans, fajita vegetables, corn salsa, tomato salsa and romaine. Values are summed from Chipotle\'s published ingredient table.'},
{chain:'Chipotle',name:'Sofritas Bowl with brown rice and black beans',cal:620,p:24,c:93,f:18,na:1990,
 t:['energy','fibre'],diet:['vegetarian','plant','gluten'],meal:'main',size:'large',
 url:'chipotle-healthy-meals-macros.html',
 why:'Sofritas, brown rice, black beans, fajita vegetables, corn salsa, tomato salsa and romaine. Values are summed from Chipotle\'s published ingredient table.'},
{chain:'Chipotle',name:'Veggie Bowl with brown rice, black beans and guacamole',cal:620,p:15,c:76,f:18,na:1470,
 t:['energy','fibre'],diet:['vegetarian','plant','gluten'],meal:'main',size:'large',
 url:'chipotle-healthy-meals-macros.html',
 why:'Brown rice, black beans, fajita vegetables, tomato salsa, guacamole and romaine. Values are summed from Chipotle\'s published ingredient table.'},
{chain:'Chipotle',name:'Steak Salad with black beans, no rice',cal:345,p:31,c:36,f:13,na:1255,
 t:['protein','light','fibre'],diet:['gluten'],meal:'main',size:'medium',
 url:'chipotle-healthy-meals-macros.html',
 why:'Steak, Supergreens, black beans, fajita vegetables, tomato salsa and romaine. Values are summed from Chipotle\'s published ingredient table.'},
{chain:'Sweetgreen',name:'Chicken Pesto Parm',cal:525,p:35,c:44,f:null,na:null,
 t:['protein','balanced'],diet:[],meal:'main',size:'medium',
 url:'sweetgreen-healthy-meals-macros.html',
 why:'Chicken and quinoa with a pesto base. Protein-forward without being enormous.'},
{chain:'Sweetgreen',name:'Harvest Bowl',cal:740,p:32,c:78,f:null,na:null,
 t:['protein','energy'],diet:[],meal:'main',size:'large',
 url:'sweetgreen-healthy-meals-macros.html',
 why:'Chicken, rice, sweet potato, apple, goat cheese and almonds. Substantial and genuinely filling.'},
{chain:'Sweetgreen',name:'Shroomami',cal:635,p:18,c:64,f:null,na:null,
 t:['energy'],diet:['vegetarian','plant'],meal:'main',size:'large',
 url:'sweetgreen-healthy-meals-macros.html',
 why:'Tofu, mushrooms, warm grains and vegetables. The most satisfying plant bowl on the menu.'},
{chain:'Sweetgreen',name:'Super Green Goddess',cal:465,p:12,c:38,f:null,na:null,
 t:[],diet:['vegetarian'],meal:'main',size:'medium',
 url:'sweetgreen-healthy-meals-macros.html',
 why:'Vegetables and chickpeas. Light, but add a protein if it is your main meal.'},
{chain:'Sweetgreen',name:'Guacamole Greens with chicken',cal:600,p:31,c:32,f:null,na:null,
 t:['protein','energy'],diet:['gluten'],meal:'main',size:'medium',
 url:'sweetgreen-healthy-meals-macros.html',
 why:'Avocado does the heavy lifting on fat and satiety here.'},
{chain:'CAVA',name:'Greek Salad bowl',cal:580,p:null,c:null,f:null,na:null,
 t:[],diet:['gluten'],meal:'main',size:'large',
 url:'cava-healthy-meals-macros.html',
 why:'Chicken, greens, vegetables and dips in a standard build.'},
{chain:'CAVA',name:'Falafel Crunch bowl',cal:860,p:null,c:null,f:null,na:null,
 t:['energy'],diet:['vegetarian','plant'],meal:'main',size:'large',
 url:'cava-healthy-meals-macros.html',
 why:'Falafel, lentils and vegetables. A high-calorie plant option for bigger days.'},
{chain:'CAVA',name:'Grilled chicken over greens, light dressing',cal:420,p:38,c:18,f:6,na:null,
 t:['protein','fibre','balanced'],diet:['gluten'],meal:'main',size:'medium',
 url:'cava-healthy-meals-macros.html',
 why:'Build it yourself: greens, grilled chicken, vegetables, dressing on the side.'},
{chain:'CAVA',name:'Harissa Avocado bowl',cal:730,p:28,c:66,f:12,na:null,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'cava-healthy-meals-macros.html',
 why:'Warm grains, avocado and spiced protein. Good when the day has been long.'},
{chain:'Chick-fil-A',name:'Grilled Nuggets, 8 count',cal:130,p:25,c:1,f:0,na:440,
 t:['protein'],diet:['gluten'],meal:'main',size:'small',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'One of the highest protein-per-calorie items in fast food. Rarely a whole meal on its own.'},
{chain:'Chick-fil-A',name:'Grilled Nuggets, 12 count',cal:200,p:38,c:2,f:0,na:660,
 t:['protein'],diet:['gluten'],meal:'main',size:'medium',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'The larger count turns it into a proper protein-led meal.'},
{chain:'Chick-fil-A',name:'Grilled Chicken Sandwich',cal:390,p:28,c:44,f:3,na:770,
 t:['protein','light'],diet:[],meal:'main',size:'medium',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'A multigrain bun and grilled fillet. The reliable everyday order.'},
{chain:'Chick-fil-A',name:'Market Salad with Grilled Nuggets',cal:570,p:32,c:46,f:6,na:1080,
 t:['protein','fibre','balanced'],diet:[],meal:'main',size:'large',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'Fruit, nuts and greens. The dressing decides how big this really is.'},
{chain:'Chick-fil-A',name:'Egg White Grill',cal:290,p:26,c:30,f:1,na:820,
 t:['protein','light'],diet:[],meal:'breakfast',size:'medium',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'A rare fast-food breakfast that clears 25 g protein under 300 calories.'},
{chain:'Chick-fil-A',name:'Kale Crunch Side',cal:170,p:3,c:9,f:2,na:250,
 t:[],diet:['vegetarian','gluten'],meal:'main',size:'small',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'A vegetable side that is not fries. Pair with grilled nuggets.'},
// Checked 2026-08-23 against Chick-fil-A's official item pages and nutrition guide:
// /menu/entrees/chick-fil-a-grilled-chicken-club-sandwich,
// /menu/entrees/chick-fil-a-cool-wrap, and /nutrition-allergens.
{chain:'Chick-fil-A',name:'Grilled Chicken Club Sandwich',cal:520,p:37,c:45,f:3,na:1055,
 t:['protein','balanced'],diet:[],meal:'main',size:'large',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'Grilled chicken, bacon and cheese make this a higher-calorie sandwich with 37 g protein. Sauce is separate.'},
{chain:'Chick-fil-A',name:'Chick-fil-A Cool Wrap',cal:660,p:43,c:32,f:14,na:1420,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'Grilled chicken, cheese and greens in a flaxseed flatbread. High protein and fiber, with sodium as the trade-off.'},
{chain:'Chick-fil-A',name:'Cobb Salad with Spicy Grilled Filet (Cold)',cal:600,p:33,c:16,f:5,na:1610,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'A substantial salad with spicy grilled chicken, egg, cheese, corn and toppings. Dressing choice changes the final total.'},
// Complete orders below are sums of the named standard items. Checked 2026-08-23
// against Chick-fil-A's official nutrition guide and current item pages.
{chain:'Chick-fil-A',name:'High-protein bulking order: Grilled Club, waffle fries and 12-count grilled nuggets',cal:1140,p:80,c:92,f:8,na:1955,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'A real 1,000-calorie-plus order with 80 g protein. The total excludes dipping sauce and drinks; sodium is the main trade-off.'},
{chain:'Chick-fil-A',name:'High-protein bulking order: 30-count grilled nuggets, waffle fries and large fruit cup',cal:1050,p:104,c:77,f:10,na:1950,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'The highest-protein large order in this guide. It is a very large portion, and sauces are not included in the total.'},
{chain:'Subway',name:'6-inch Veggie Delite',cal:320,p:17,c:44,f:4,na:600,
 t:['light','lowsodium'],diet:['vegetarian'],meal:'main',size:'medium',
 url:'subway-healthy-meals-macros.html',
 why:'The lightest standard build. Cheese and sauces change it quickly.'},
{chain:'Subway',name:'6-inch Oven Roasted Turkey',cal:280,p:19,c:41,f:4,na:760,
 t:['light'],diet:[],meal:'main',size:'medium',
 url:'subway-healthy-meals-macros.html',
 why:'A dependable lean order. Ask for extra vegetables at no real calorie cost.'},
{chain:'Subway',name:'6-inch Rotisserie Chicken',cal:320,p:29,c:41,f:4,na:640,
 t:['protein','light'],diet:[],meal:'main',size:'medium',
 url:'subway-healthy-meals-macros.html',
 why:'Better protein than the turkey for a similar calorie total.'},
{chain:'Subway',name:'Footlong Rotisserie Chicken',cal:640,p:58,c:82,f:8,na:1280,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'subway-healthy-meals-macros.html',
 why:'A genuine high-calorie, high-protein option. Sodium is the trade-off.'},
{chain:'Subway',name:'Grilled Chicken Salad',cal:220,p:27,c:12,f:5,na:610,
 t:['protein','fibre'],diet:['gluten'],meal:'main',size:'small',
 url:'subway-healthy-meals-macros.html',
 why:'Very high protein per calorie. Dressing is the variable.'},
// Checked 2026-08-23 against Subway's January 2026 U.S. nutrition sheet,
// which instructs customers to double its six-inch values for a footlong.
{chain:'Subway',name:'Footlong Grilled Chicken',cal:1020,p:62,c:86,f:6,na:1660,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'subway-healthy-meals-macros.html',
 why:'A 1,000-calorie footlong with 62 g protein. This is the standard U.S. build; custom bread, cheese and sauce change it.'},
{chain:'Subway',name:'Footlong Meatball Marinara',cal:1140,p:54,c:106,f:8,na:2740,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'subway-healthy-meals-macros.html',
 why:'A genuinely large bulking option with 54 g protein. It is also very high in sodium, so the guide keeps that trade-off visible.'},
{chain:'Panera',name:'Mediterranean Chicken Greens with Grains, half',cal:330,p:17,c:32,f:4,na:660,
 t:['light'],diet:[],meal:'main',size:'small',
 url:'panera-healthy-meals-macros.html',
 why:'Half portions are the underused trick on this menu.'},
{chain:'Panera',name:'Mediterranean Greens with Grains, whole',cal:540,p:11,c:58,f:7,na:820,
 t:['fibre'],diet:['vegetarian'],meal:'main',size:'large',
 url:'panera-healthy-meals-macros.html',
 why:'A meat-free grain salad with genuinely useful fiber.'},
{chain:'Panera',name:'Ten Vegetable Soup, cup',cal:80,p:3,c:15,f:4,na:590,
 t:[],diet:['vegetarian','plant'],meal:'main',size:'small',
 url:'panera-healthy-meals-macros.html',
 why:'A very light starter that adds volume without much energy.'},
{chain:'Panera',name:'Chicken Caesar Salad, whole',cal:470,p:34,c:16,f:4,na:930,
 t:['protein','balanced'],diet:[],meal:'main',size:'medium',
 url:'panera-healthy-meals-macros.html',
 why:'Protein-led. The dressing and croutons carry most of the calories.'},
{chain:'Panera',name:'Turkey Chili, bowl',cal:340,p:26,c:38,f:11,na:1140,
 t:['protein','light','fibre'],diet:[],meal:'main',size:'medium',
 url:'panera-healthy-meals-macros.html',
 why:'One of the highest-fiber hot options on any chain menu.'},
{chain:'Starbucks',name:'Eggs & Cheddar Protein Box',cal:460,p:22,c:36,f:5,na:450,
 t:['fibre','lowsodium','balanced'],diet:['vegetarian'],meal:'breakfast',size:'medium',
 url:'starbucks-healthy-food-meals-macros.html',
 why:'Portable mix of protein, fruit and carbohydrate. Good travel food.'},
{chain:'Starbucks',name:'Spinach, Feta & Egg White Wrap',cal:290,p:20,c:34,f:3,na:840,
 t:['light'],diet:['vegetarian'],meal:'breakfast',size:'medium',
 url:'starbucks-healthy-food-meals-macros.html',
 why:'The standard lighter breakfast order.'},
{chain:'Starbucks',name:'Turkey Bacon & Egg White Sandwich',cal:230,p:17,c:28,f:3,na:550,
 t:[],diet:[],meal:'breakfast',size:'small',
 url:'starbucks-healthy-food-meals-macros.html',
 why:'Lowest-calorie hot breakfast that still brings real protein.'},
{chain:'Starbucks',name:'Rolled & Steel-Cut Oatmeal',cal:160,p:5,c:28,f:4,na:125,
 t:[],diet:['vegetarian','plant'],meal:'breakfast',size:'small',
 url:'starbucks-healthy-food-meals-macros.html',
 why:'Plain base; the toppings are where the calories arrive.'},
{chain:'Starbucks',name:'Chicken & Quinoa Protein Bowl',cal:420,p:27,c:42,f:6,na:680,
 t:['protein','fibre','balanced'],diet:[],meal:'main',size:'medium',
 url:'starbucks-healthy-food-meals-macros.html',
 why:'A full meal rather than a snack, with fiber from the grains.'},
{chain:'McDonald’s',name:'Hamburger',cal:250,p:12,c:31,f:1,na:510,
 t:[],diet:[],meal:'main',size:'small',
 url:'mcdonalds-healthy-meals-macros.html',
 why:'A known, small standard portion. Useful as a calibration point.'},
{chain:'McDonald’s',name:'Egg McMuffin',cal:310,p:17,c:30,f:2,na:770,
 t:['light'],diet:[],meal:'breakfast',size:'medium',
 url:'mcdonalds-healthy-meals-macros.html',
 why:'Compact breakfast with egg and Canadian bacon.'},
{chain:'McDonald’s',name:'McChicken',cal:400,p:14,c:39,f:2,na:560,
 t:[],diet:[],meal:'main',size:'medium',
 url:'mcdonalds-healthy-meals-macros.html',
 why:'Moderate everywhere. Not a protein play.'},
{chain:'McDonald’s',name:'Quarter Pounder with Cheese',cal:520,p:30,c:42,f:2,na:1140,
 t:['protein','balanced'],diet:[],meal:'main',size:'large',
 url:'mcdonalds-healthy-meals-macros.html',
 why:'Genuinely high protein for the menu. Sodium is the cost.'},
{chain:'McDonald’s',name:'Double Cheeseburger',cal:450,p:25,c:34,f:2,na:1050,
 t:['protein','balanced'],diet:[],meal:'main',size:'medium',
 url:'mcdonalds-healthy-meals-macros.html',
 why:'More protein per calorie than most items here.'},
{chain:'McDonald’s',name:'Apple Slices',cal:15,p:0,c:4,f:0,na:0,
 t:[],diet:['vegetarian','plant','gluten'],meal:'main',size:'small',
 url:'mcdonalds-healthy-meals-macros.html',
 why:'A swap for fries that costs almost nothing.'},
{chain:'Wendy’s',name:'Grilled Chicken Sandwich',cal:370,p:34,c:38,f:2,na:800,
 t:['protein','light'],diet:[],meal:'main',size:'medium',
 url:'wendys-healthy-meals-macros.html',
 why:'One of the better protein-to-calorie sandwiches in the category.'},
{chain:'Wendy’s',name:'Grilled Chicken Wrap',cal:280,p:21,c:26,f:1,na:760,
 t:['light'],diet:[],meal:'main',size:'small',
 url:'wendys-healthy-meals-macros.html',
 why:'A smaller order that still brings 20 g protein.'},
{chain:'Wendy’s',name:'Apple Pecan Salad, half',cal:340,p:19,c:26,f:3,na:570,
 t:['light','lowsodium'],diet:[],meal:'main',size:'small',
 url:'wendys-healthy-meals-macros.html',
 why:'Half sizes make the salads workable as a light meal.'},
{chain:'Wendy’s',name:'Chili, small',cal:240,p:17,c:23,f:6,na:810,
 t:['fibre'],diet:[],meal:'main',size:'small',
 url:'wendys-healthy-meals-macros.html',
 why:'Cheap, filling, high fiber. An underrated fast-food order.'},
{chain:'Wendy’s',name:'Dave’s Single',cal:590,p:30,c:39,f:2,na:1120,
 t:['protein','balanced'],diet:[],meal:'main',size:'large',
 url:'wendys-healthy-meals-macros.html',
 why:'A higher-calorie option that still carries 30 g protein.'},
{chain:'Taco Bell',name:'Chicken Soft Taco',cal:170,p:12,c:17,f:2,na:470,
 t:[],diet:[],meal:'main',size:'small',
 url:'taco-bell-healthy-meals-macros.html',
 why:'Small, cheap, easy to combine into whatever size meal you want.'},
{chain:'Taco Bell',name:'Power Menu Bowl with chicken',cal:470,p:26,c:50,f:8,na:1200,
 t:['protein','fibre','balanced'],diet:[],meal:'main',size:'medium',
 url:'taco-bell-healthy-meals-macros.html',
 why:'Rice, beans, chicken and vegetables. The most complete build on the menu.'},
{chain:'Taco Bell',name:'Veggie Power Menu Bowl',cal:430,p:12,c:56,f:11,na:1010,
 t:['fibre'],diet:['vegetarian'],meal:'main',size:'medium',
 url:'taco-bell-healthy-meals-macros.html',
 why:'Very high fiber from the beans. Add extra beans for more protein.'},
{chain:'Taco Bell',name:'Black Bean Burrito',cal:420,p:13,c:64,f:11,na:1000,
 t:['fibre'],diet:['vegetarian','plant'],meal:'main',size:'medium',
 url:'taco-bell-healthy-meals-macros.html',
 why:'One of the cheapest high-fiber plant-based fast-food items anywhere.'},
{chain:'Taco Bell',name:'Chicken Burrito Supreme',cal:390,p:19,c:50,f:7,na:1090,
 t:['light','fibre'],diet:[],meal:'main',size:'medium',
 url:'taco-bell-healthy-meals-macros.html',
 why:'A middle-of-the-road order with decent fiber.'},
{chain:'Panda Express',name:'Grilled Teriyaki Chicken',cal:275,p:33,c:14,f:0,na:470,
 t:['protein','light','lowsodium'],diet:[],meal:'main',size:'medium',
 url:'panda-express-healthy-meals-macros.html',
 why:'High protein before the side. Sauce and side are counted separately.'},
{chain:'Panda Express',name:'Super Greens side',cal:130,p:9,c:14,f:7,na:370,
 t:['fibre'],diet:['vegetarian','plant','gluten'],meal:'main',size:'small',
 url:'panda-express-healthy-meals-macros.html',
 why:'Swap this for chow mein and the meal changes shape entirely.'},
{chain:'Panda Express',name:'String Bean Chicken Breast',cal:210,p:12,c:13,f:5,na:560,
 t:['fibre'],diet:[],meal:'main',size:'small',
 url:'panda-express-healthy-meals-macros.html',
 why:'A lighter entrée with vegetables built in.'},
{chain:'Panda Express',name:'Grilled Teriyaki Chicken with Super Greens',cal:405,p:42,c:28,f:7,na:840,
 t:['protein','fibre','balanced'],diet:[],meal:'main',size:'medium',
 url:'panda-express-healthy-meals-macros.html',
 why:'The best-value protein plate here once you skip the fried rice.'},
{chain:'Panda Express',name:'Broccoli Beef with white steamed rice',cal:670,p:25,c:130,f:2,na:520,
 t:['protein','energy','lowsodium'],diet:[],meal:'main',size:'large',
 url:'panda-express-healthy-meals-macros.html',
 why:'A current higher-carbohydrate plate built from a full rice side and broccoli beef entrée.'},
// Checked 2026-08-23 against Panda Express's current U.S. nutrition table.
// Bigger Plate totals add one full side and the three named full entrée servings.
{chain:'Panda Express',name:'Bigger Plate: fried rice + 3 grilled teriyaki chicken entrées',cal:1445,p:112,c:143,f:1,na:2410,
 t:['protein','energy'],diet:[],meal:'main',size:'large',
 url:'panda-express-healthy-meals-macros.html',
 why:'A serious bulking plate with 112 g protein. The total uses three full teriyaki servings and excludes extra sauce or drinks.'},
{chain:'Panda Express',name:'Bigger Plate: chow mein + grilled teriyaki + orange chicken + string bean chicken',cal:1595,p:76,c:174,f:14,na:2880,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'panda-express-healthy-meals-macros.html',
 why:'The largest varied meal in the guide: four named current menu components, 76 g protein and enough carbohydrate for a high-calorie day.'},
{chain:'KFC',name:'Original Recipe Drumstick',cal:130,p:12,c:4,f:0,na:430,
 t:[],diet:[],meal:'main',size:'small',
 url:'kfc-healthy-meals-macros.html',
 why:'A small portion you can build a plate around.'},
{chain:'KFC',name:'Original Recipe Breast',cal:390,p:39,c:11,f:1,na:1190,
 t:['protein','light'],diet:[],meal:'main',size:'medium',
 url:'kfc-healthy-meals-macros.html',
 why:'Very high protein, with sodium that deserves attention.'},
{chain:'KFC',name:'Kentucky Grilled Chicken Breast',cal:210,p:38,c:0,f:0,na:710,
 t:['protein'],diet:['gluten'],meal:'main',size:'medium',
 url:'kfc-healthy-meals-macros.html',
 why:'Grilled rather than fried: nearly the same protein for half the calories.'},
{chain:'KFC',name:'Green Beans',cal:25,p:1,c:5,f:2,na:260,
 t:[],diet:['vegetarian','plant','gluten'],meal:'main',size:'small',
 url:'kfc-healthy-meals-macros.html',
 why:'The lightest side on the board by a wide margin.'},
{chain:'KFC',name:'Grilled Breast with green beans and corn',cal:345,p:41,c:34,f:5,na:1040,
 t:['protein','fibre'],diet:[],meal:'main',size:'medium',
 url:'kfc-healthy-meals-macros.html',
 why:'A complete plate built from the lighter half of the menu.'},
{chain:'Popeyes',name:'3 Blackened Tenders',cal:170,p:26,c:2,f:0,na:550,
 t:['protein'],diet:['gluten'],meal:'main',size:'small',
 url:'popeyes-healthy-meals-macros.html',
 why:'Blackened rather than battered. Excellent protein per calorie.'},
{chain:'Popeyes',name:'5 Blackened Tenders',cal:280,p:43,c:3,f:0,na:920,
 t:['protein','light'],diet:['gluten'],meal:'main',size:'medium',
 url:'popeyes-healthy-meals-macros.html',
 why:'A serious protein portion for under 300 calories.'},
{chain:'Popeyes',name:'Red Beans & Rice, regular',cal:230,p:6,c:31,f:5,na:680,
 t:['fibre'],diet:['vegetarian'],meal:'main',size:'small',
 url:'popeyes-healthy-meals-macros.html',
 why:'A side with real fiber. Not vegan in the standard recipe.'},
{chain:'Popeyes',name:'Blackened Tenders with green beans',cal:230,p:28,c:10,f:3,na:850,
 t:['protein'],diet:[],meal:'main',size:'medium',
 url:'popeyes-healthy-meals-macros.html',
 why:'Complete, light and protein-led.'},
{chain:'Jersey Mike’s',name:'Turkey Sub in a Tub',cal:280,p:28,c:12,f:4,na:1220,
 t:['protein','light'],diet:['gluten'],meal:'main',size:'medium',
 url:'jersey-mikes-healthy-subs-macros.html',
 why:'"In a tub" swaps the bread for greens. Big protein, low calories, high sodium.'},
{chain:'Jersey Mike’s',name:'Mini Turkey Sub',cal:390,p:26,c:48,f:3,na:1180,
 t:['protein','light'],diet:[],meal:'main',size:'small',
 url:'jersey-mikes-healthy-subs-macros.html',
 why:'Portion control built into the menu.'},
{chain:'Jersey Mike’s',name:'Regular Chicken Caesar Wrap',cal:640,p:39,c:52,f:4,na:1560,
 t:['protein','energy'],diet:[],meal:'main',size:'large',
 url:'jersey-mikes-healthy-subs-macros.html',
 why:'A high-calorie, high-protein option for bigger days.'},
{chain:'Jersey Mike’s',name:'Veggie Sub, regular',cal:520,p:20,c:64,f:5,na:1090,
 t:['fibre','balanced'],diet:['vegetarian'],meal:'main',size:'large',
 url:'jersey-mikes-healthy-subs-macros.html',
 why:'Cheese-forward rather than vegetable-forward; ask for extra vegetables.'},
{chain:'Dunkin’',name:'Egg & Cheese Wake-Up Wrap',cal:180,p:7,c:14,f:0,na:470,
 t:[],diet:['vegetarian'],meal:'breakfast',size:'small',
 url:'dunkin-healthy-breakfast-macros.html',
 why:'Small enough to pair with something else.'},
{chain:'Dunkin’',name:'Egg & Cheese English Muffin',cal:340,p:14,c:36,f:1,na:650,
 t:[],diet:['vegetarian'],meal:'breakfast',size:'medium',
 url:'dunkin-healthy-breakfast-macros.html',
 why:'A more substantial meat-free breakfast sandwich.'},
{chain:'Dunkin’',name:'Turkey Sausage Wake-Up Wrap',cal:230,p:12,c:14,f:0,na:600,
 t:[],diet:[],meal:'breakfast',size:'small',
 url:'dunkin-healthy-breakfast-macros.html',
 why:'Better protein than the plain egg version for 50 more calories.'},
{chain:'Dunkin’',name:'Sourdough Breakfast Sandwich',cal:490,p:24,c:42,f:2,na:1180,
 t:['balanced'],diet:[],meal:'breakfast',size:'large',
 url:'dunkin-healthy-breakfast-macros.html',
 why:'The largest breakfast option here, and the only one clearing 20 g protein.'}
];
