/* Restaurant meals the finder ranks.
 *
 * These records hold only what is observed or editorial: the chain, the item,
 * its published numbers, whether it suits a diet, whether it is a breakfast
 * item, and why we think it is worth ordering.
 *
 *   diet  - subset of vegetarian | plant | gluten. Hand-assigned, because no
 *           formula can read an ingredient list.
 *   meal  - breakfast | main. When you eat it, not a dietary restriction. An
 *           earlier version filed "breakfast" alongside vegetarian and gluten,
 *           which put an occasion in a list of things people cannot eat.
 *   null  - the chain does not publish that value in a form we would stand
 *           behind. Deliberately not zero.
 *
 * The `t` array of goal tags is generated, not hand-written:
 * tools/build_meal_finder.py derives it from the numbers above and writes it
 * back here. Hand-assigning them drifted badly, with 41 meals tagged high
 * protein while only 36 reached the 25 g the label promised.
 */
window.GM_THRESHOLDS = {protein:25,energy:600,light:400,fibre:5,sodium:600};

window.GM_MEALS = [
/* Chipotle's current High Protein Menu gives the exact build and published
 * calories/protein/fiber. Carbs and sodium are sums of Chipotle's current
 * ingredient values; light brown rice uses half of the standard portion. */
{chain:'Chipotle',name:'High Protein-High Fiber Bowl',cal:540,p:46,c:66,f:14,na:1645,
 t:['protein','fibre','balanced'],diet:['gluten'],meal:'main',size:'medium',
 url:'chipotle-healthy-meals-macros.html',
 why:'Adobo chicken, light brown rice, black beans, fajita vegetables, corn salsa, tomato salsa and romaine. Carbs and sodium are calculated from Chipotle\'s published ingredient values.'},
/* Current official build: chicken, Supergreens, fajita vegetables, fresh
 * tomato salsa and guacamole. Carbs and sodium are summed from the same
 * current ingredient table; Chipotle publishes calories/protein/fiber. */
{chain:'Chipotle',name:'High Protein-Low Calorie Salad',cal:470,p:36,c:20,f:10,na:1395,
 t:['protein','fibre','balanced'],diet:['gluten'],meal:'main',size:'medium',
 url:'chipotle-healthy-meals-macros.html',
 why:'Adobo chicken, Supergreens, fajita vegetables, fresh tomato salsa and guacamole. Carbs and sodium are calculated from Chipotle\'s published ingredient values.'},
/* The four builds below use exact ingredient combinations so every displayed
 * nutrient, including sodium, can be summed from Chipotle's U.S. ingredient
 * nutrition table instead of relying on an undefined "standard bowl." */
{chain:'Chipotle',name:'Chicken Bowl with white rice and black beans',cal:650,p:48,c:88,f:14,na:1900,
 t:['protein','energy','fibre'],diet:['gluten'],meal:'main',size:'large',
 url:'chipotle-healthy-meals-macros.html',
 why:'Adobo chicken, white rice, black beans, fajita vegetables, corn salsa, tomato salsa and romaine. Values are summed from Chipotle\'s published ingredient table.'},
{chain:'Chipotle',name:'Sofritas Bowl with brown rice and black beans',cal:620,p:24,c:93,f:18,na:1990,
 t:['energy','fibre'],diet:['vegetarian','plant','gluten'],meal:'main',size:'large',
 url:'chipotle-healthy-meals-macros.html',
 why:'Sofritas, brown rice, black beans, fajita vegetables, corn salsa, tomato salsa and romaine. Values are summed from Chipotle\'s published ingredient table.'},
{chain:'Chipotle',name:'Veggie Bowl with brown rice, black beans and guacamole',cal:620,p:15,c:76,f:18,na:1470,
 t:['energy','fibre'],diet:['vegetarian','plant','gluten'],meal:'main',size:'large',
 url:'chipotle-healthy-meals-macros.html',
 why:'Brown rice, black beans, fajita vegetables, tomato salsa, guacamole and romaine. Values are summed from Chipotle\'s published ingredient table.'},
{chain:'Chipotle',name:'Steak Salad with black beans, no rice',cal:345,p:31,c:36,f:13,na:1255,
 t:['protein','light','fibre'],diet:['gluten'],meal:'main',size:'medium',
 url:'chipotle-healthy-meals-macros.html',
 why:'Steak, Supergreens, black beans, fajita vegetables, tomato salsa and romaine. Values are summed from Chipotle\'s published ingredient table.'},
{chain:'Sweetgreen',name:'Chicken Pesto Parm',cal:510,p:38,c:30,f:6,na:1560,
 t:['protein','fibre','balanced'],diet:[],meal:'main',size:'medium',
 url:'sweetgreen-healthy-meals-macros.html',
 why:'Chicken, quinoa and vegetables with parmesan, breadcrumbs and pesto vinaigrette. Standard bowl, including dressing.'},
{chain:'Sweetgreen',name:'Harvest Bowl',cal:760,p:40,c:60,f:10,na:1265,
 t:['protein','energy','fibre'],diet:['gluten'],meal:'main',size:'large',
 url:'sweetgreen-healthy-meals-macros.html',
 why:'Chicken and warm grains with sweet potato, apple, goat cheese and almonds. Includes the standard dressing.'},
{chain:'Sweetgreen',name:'Shroomami',cal:665,p:20,c:51,f:11,na:1250,
 t:['energy','fibre'],diet:['vegetarian','plant','gluten'],meal:'main',size:'large',
 url:'sweetgreen-healthy-meals-macros.html',
 why:'Tofu, mushrooms, rice and vegetables with miso sesame ginger dressing. A plant-based bowl with 20 g protein.'},
{chain:'Sweetgreen',name:'Super Green Goddess',cal:465,p:12,c:36,f:13,na:1230,
 t:['fibre'],diet:['vegetarian','gluten'],meal:'main',size:'medium',
 url:'sweetgreen-healthy-meals-macros.html',
 why:'A vegetable and chickpea salad with 13 g fiber. The standard Green Goddess Ranch dressing contains dairy.'},
{chain:'Sweetgreen',name:'Guacamole Greens',cal:555,p:29,c:35,f:12,na:1560,
 t:['protein','fibre','balanced'],diet:['gluten'],meal:'main',size:'medium',
 url:'sweetgreen-healthy-meals-macros.html',
 why:'Chicken, avocado, vegetables and tortilla chips with lime cilantro jalapeño vinaigrette. Includes the standard dressing.'},
{chain:'CAVA',name:'Greek Salad bowl',cal:585,p:37,c:19,f:8,na:1830,
 t:['protein','fibre','balanced'],diet:[],meal:'main',size:'large',
 url:'cava-healthy-meals-macros.html',
 why:'Standard Greek Salad bowl from CAVA’s published nutrition guide. Confirm the current build and availability when ordering.'},
{chain:'CAVA',name:'Falafel Crunch bowl',cal:860,p:24,c:88,f:18,na:2230,
 t:['energy','fibre'],diet:['vegetarian'],meal:'main',size:'large',
 url:'cava-healthy-meals-macros.html',
 why:'Standard Falafel Crunch bowl from CAVA’s nutrition guide. Includes dairy; it is not a vegan build. Availability varies.'},
{chain:'CAVA',name:'Chicken + Rice bowl',cal:710,p:40,c:43,f:7,na:1830,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'medium',
 url:'cava-healthy-meals-macros.html',
 why:'Standard Chicken + Rice bowl from CAVA’s nutrition guide. Custom changes to dips, toppings or dressing change these totals.'},
{chain:'CAVA',name:'Harissa Avocado bowl',cal:840,p:42,c:63,f:12,na:2030,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'cava-healthy-meals-macros.html',
 why:'Standard Harissa Avocado bowl from CAVA’s nutrition guide. Includes the full recipe; check the current menu before ordering.'},
{chain:'Chick-fil-A',name:'Grilled Nuggets, 8 count',cal:130,p:25,c:1,f:0,na:440,
 t:['protein'],diet:['gluten'],meal:'main',size:'small',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'One of the highest protein-per-calorie items in fast food. Rarely a whole meal on its own.'},
{chain:'Chick-fil-A',name:'Grilled Nuggets, 12 count',cal:200,p:38,c:2,f:0,na:660,
 t:['protein'],diet:['gluten'],meal:'main',size:'medium',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'The larger count turns it into a proper protein-led meal.'},
{chain:'Chick-fil-A',name:'Grilled Chicken Sandwich',cal:390,p:28,c:45,f:3,na:765,
 t:['protein','light'],diet:[],meal:'main',size:'medium',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'A multigrain bun and grilled fillet. The reliable everyday order.'},
{chain:'Chick-fil-A',name:'Market Salad with Grilled Nuggets',cal:570,p:32,c:41,f:6,na:1080,
 t:['protein','fibre','balanced'],diet:[],meal:'main',size:'large',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'Market Salad with grilled nuggets and the standard toppings and suggested dressing. Changing the dressing changes the total.'},
{chain:'Chick-fil-A',name:'Egg White Grill',cal:300,p:27,c:29,f:1,na:990,
 t:['protein','light'],diet:[],meal:'breakfast',size:'medium',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'A rare fast-food breakfast that clears 25 g protein under 300 calories.'},
{chain:'Chick-fil-A',name:'Kale Crunch Side',cal:170,p:4,c:13,f:4,na:250,
 t:[],diet:['vegetarian','gluten'],meal:'main',size:'small',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'A vegetable side that is not fries. Pair with grilled nuggets.'},
// Checked 2026-08-23 against Chick-fil-A's official item pages and nutrition guide:
// /menu/entrees/chick-fil-a-grilled-chicken-club-sandwich,
// /menu/entrees/chick-fil-a-cool-wrap, and /nutrition-allergens.
{chain:'Chick-fil-A',name:'Grilled Chicken Club Sandwich',cal:520,p:37,c:45,f:3,na:1055,
 t:['protein','balanced'],diet:[],meal:'main',size:'large',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'Grilled chicken, bacon and cheese make this a higher-calorie sandwich with 37 g protein. Sauce is separate.'},
{chain:'Chick-fil-A',name:'Chick-fil-A Cool Wrap',cal:660,p:43,c:32,f:14,na:1420,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'Standard Cool Wrap with the suggested Avocado Lime Ranch dressing. The dressing is included in the published 660-calorie total.'},
{chain:'Chick-fil-A',name:'Cobb Salad with Spicy Grilled Filet (Cold)',cal:600,p:33,c:16,f:5,na:1610,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'Cobb Salad with a cold spicy grilled filet, standard toppings and suggested dressing. Includes 1,610 mg sodium.'},
// Complete orders below are sums of the named standard items. Checked 2026-08-23
// against Chick-fil-A's official nutrition guide and current item pages.
{chain:'Chick-fil-A',name:'Grilled Club, medium waffle fries and 12 grilled nuggets',cal:1140,p:80,c:92,f:8,na:1955,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'Grilled Club sandwich, medium waffle fries and 12 grilled nuggets: 520 + 420 + 200 calories. No extra sauces or drink.'},
{chain:'Chick-fil-A',name:'30 grilled nuggets, medium waffle fries and large fruit cup',cal:1050,p:104,c:77,f:10,na:1950,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'chick-fil-a-healthy-meals-macros.html',
 why:'30 grilled nuggets, medium waffle fries and a large fruit cup: 510 + 420 + 120 calories. No extra sauce or drink.'},
{chain:'Subway',name:'6-inch Veggie Delite',cal:320,p:17,c:41,f:4,na:600,
 t:['light','lowsodium'],diet:['vegetarian'],meal:'main',size:'medium',
 url:'subway-healthy-meals-macros.html',
 why:'The standard six-inch recipe in Subway’s U.S. nutrition table, including cheese. Custom bread and sauces change the total.'},
{chain:'Subway',name:'6-inch Oven-Roasted Turkey',cal:480,p:26,c:42,f:3,na:1150,
 t:['protein','balanced'],diet:[],meal:'main',size:'medium',
 url:'subway-healthy-meals-macros.html',
 why:'The standard six-inch turkey sandwich with its listed cheese and sauce. This is not a no-cheese, no-mayo build.'},
{chain:'Subway',name:'6-inch Grilled Chicken & Fresh Avocado',cal:450,p:35,c:44,f:6,na:800,
 t:['protein','fibre','balanced'],diet:[],meal:'main',size:'medium',
 url:'subway-healthy-meals-macros.html',
 why:'The Fresh Fit recipe with multigrain bread, deluxe chicken portion, fresh avocado and vegetables.'},
{chain:'Subway',name:'Footlong Grilled Chicken & Fresh Avocado',cal:900,p:70,c:88,f:12,na:1600,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'subway-healthy-meals-macros.html',
 why:'Two six-inch servings of the Fresh Fit recipe. Subway instructs doubling its six-inch values for a footlong.'},
{chain:'Subway',name:'Grilled Chicken Salad',cal:440,p:26,c:12,f:4,na:590,
 t:['protein','lowsodium','balanced'],diet:['gluten'],meal:'main',size:'small',
 url:'subway-healthy-meals-macros.html',
 why:'Standard salad with vegetables, chicken and cheese. Dressing is not included in Subway’s listed salad values.'},
// Checked 2026-08-23 against Subway's January 2026 U.S. nutrition sheet,
// which instructs customers to double its six-inch values for a footlong.
{chain:'Subway',name:'Footlong Grilled Chicken',cal:1020,p:62,c:86,f:6,na:1660,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'subway-healthy-meals-macros.html',
 why:'Two six-inch servings of the standard Grilled Chicken recipe, including its cheese and sauce.'},
{chain:'Subway',name:'Footlong Meatball Marinara',cal:1140,p:54,c:106,f:8,na:2740,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'subway-healthy-meals-macros.html',
 why:'Two six-inch servings of the standard meatball recipe. A large meal with 2,740 mg sodium.'},
{chain:'Panera',name:'Green Goddess Cobb Salad with Chicken, half',cal:290,p:20,c:15,f:4,na:990,
 t:['light'],diet:[],meal:'main',size:'small',
 url:'panera-healthy-meals-macros.html',
 why:'Half of the standard chicken Cobb salad, including dressing. The bread or other side is not included.'},
{chain:'Panera',name:'Greek Salad, whole',cal:630,p:8,c:17,f:5,na:1400,
 t:['energy','fibre'],diet:['vegetarian'],meal:'main',size:'large',
 url:'panera-healthy-meals-macros.html',
 why:'A whole Greek salad with the standard feta and dressing. It has 8 g protein; add another food if you need a higher-protein meal.'},
{chain:'Panera',name:'Homestyle Chicken Noodle Soup, cup',cal:120,p:10,c:14,f:0,na:1050,
 t:[],diet:[],meal:'main',size:'small',
 url:'panera-healthy-meals-macros.html',
 why:'One cup of chicken noodle soup. This is a small side or snack; bread is not included.'},
{chain:'Panera',name:'Caesar with Chicken Salad, whole',cal:670,p:35,c:27,f:4,na:2620,
 t:['protein','energy'],diet:[],meal:'main',size:'medium',
 url:'panera-healthy-meals-macros.html',
 why:'A whole salad with chicken and the standard Caesar dressing. Compare the 2,620 mg sodium as well as protein.'},
{chain:'Panera',name:'Hearty Fireside Chili, bowl',cal:410,p:19,c:49,f:9,na:1730,
 t:['fibre'],diet:[],meal:'main',size:'medium',
 url:'panera-healthy-meals-macros.html',
 why:'One bowl of the current chili, without a bread bowl or separate side. Provides 9 g fiber.'},
{chain:'Starbucks',name:'Egg White & Roasted Red Pepper Egg Bites',cal:170,p:12,c:11,f:0,na:470,
 t:[],diet:['vegetarian'],meal:'breakfast',size:'small',
 url:'starbucks-healthy-food-meals-macros.html',
 why:'Two egg-white bites with roasted red pepper, spinach and cheese. A small breakfast portion; drinks and other food are separate.'},
{chain:'Starbucks',name:'Spinach, Feta & Egg White Wrap',cal:290,p:20,c:34,f:3,na:840,
 t:['light'],diet:['vegetarian'],meal:'breakfast',size:'medium',
 url:'starbucks-healthy-food-meals-macros.html',
 why:'One egg-white wrap with spinach and feta. Includes the standard spread.'},
{chain:'Starbucks',name:'Turkey Bacon, Cheddar & Egg White Sandwich',cal:260,p:17,c:30,f:2,na:600,
 t:['light','lowsodium'],diet:[],meal:'breakfast',size:'small',
 url:'starbucks-healthy-food-meals-macros.html',
 why:'One breakfast sandwich with turkey bacon, cheddar and egg white. Coffee and other drinks are separate.'},
{chain:'Starbucks',name:'Rolled & Steel-Cut Oatmeal',cal:160,p:5,c:28,f:4,na:125,
 t:[],diet:['vegetarian','plant'],meal:'breakfast',size:'small',
 url:'starbucks-healthy-food-meals-macros.html',
 why:'Plain oatmeal before optional toppings. Add the calories for any nuts, dried fruit or sugar you use.'},
{chain:'Starbucks',name:'Cheese Trio Protein Box',cal:520,p:20,c:59,f:5,na:710,
 t:['fibre','balanced'],diet:['vegetarian'],meal:'main',size:'medium',
 url:'starbucks-healthy-food-meals-macros.html',
 why:'One complete box with three cheeses, crackers and dried fruit.'},
{chain:'McDonald’s',name:'Hamburger',cal:250,p:12,c:30,f:1,na:510,
 t:[],diet:[],meal:'main',size:'small',
 url:'mcdonalds-healthy-meals-macros.html',
 why:'One standard U.S. menu item. Extra sides, sauces and drinks are not included.'},
{chain:'McDonald’s',name:'Egg McMuffin',cal:310,p:17,c:30,f:2,na:770,
 t:['light'],diet:[],meal:'breakfast',size:'medium',
 url:'mcdonalds-healthy-meals-macros.html',
 why:'One standard U.S. menu item. Extra sides, sauces and drinks are not included.'},
{chain:'McDonald’s',name:'McChicken',cal:390,p:14,c:38,f:1,na:560,
 t:[],diet:[],meal:'main',size:'medium',
 url:'mcdonalds-healthy-meals-macros.html',
 why:'One standard U.S. menu item. Extra sides, sauces and drinks are not included.'},
{chain:'McDonald’s',name:'Quarter Pounder with Cheese',cal:520,p:30,c:42,f:2,na:1140,
 t:['protein','balanced'],diet:[],meal:'main',size:'large',
 url:'mcdonalds-healthy-meals-macros.html',
 why:'One standard U.S. menu item. Extra sides, sauces and drinks are not included.'},
{chain:'McDonald’s',name:'Double Cheeseburger',cal:440,p:25,c:34,f:2,na:1120,
 t:['protein','balanced'],diet:[],meal:'main',size:'medium',
 url:'mcdonalds-healthy-meals-macros.html',
 why:'One standard U.S. menu item. Extra sides, sauces and drinks are not included.'},
{chain:'McDonald’s',name:'Apple Slices',cal:15,p:0,c:4,f:0,na:0,
 t:[],diet:['vegetarian','plant','gluten'],meal:'main',size:'small',
 url:'mcdonalds-healthy-meals-macros.html',
 why:'One standard U.S. menu item. Extra sides, sauces and drinks are not included.'},
{chain:'Wendy’s',name:'Classic Chicken Sandwich',cal:550,p:28,c:55,f:3,na:1630,
 t:['protein','balanced'],diet:[],meal:'main',size:'medium',
 url:'wendys-healthy-meals-macros.html',
 why:'Breaded chicken on a bun with the standard mayo, lettuce, tomato and pickles. Fries and drinks are separate.'},
{chain:'Wendy’s',name:'Grilled Chicken Ranch Wrap',cal:420,p:28,c:41,f:1,na:1100,
 t:['protein','balanced'],diet:[],meal:'main',size:'small',
 url:'wendys-healthy-meals-macros.html',
 why:'One wrap with grilled chicken, cheddar, romaine and ranch. Includes the standard sauce.'},
{chain:'Wendy’s',name:'Apple Pecan Salad with one dressing packet',cal:510,p:30,c:43,f:5,na:1170,
 t:['protein','fibre','balanced'],diet:[],meal:'main',size:'small',
 url:'wendys-healthy-meals-macros.html',
 why:'A full salad plus one Pomegranate Vinaigrette packet: 420 + 90 calories. Includes chicken, blue cheese and pecans.'},
{chain:'Wendy’s',name:'Chili, small',cal:280,p:19,c:24,f:3,na:1050,
 t:['light'],diet:[],meal:'main',size:'small',
 url:'wendys-healthy-meals-macros.html',
 why:'One small chili. Cheese, crackers and other extras are not included.'},
{chain:'Wendy’s',name:'Dave’s Single',cal:560,p:31,c:37,f:2,na:1170,
 t:['protein','balanced'],diet:[],meal:'main',size:'large',
 url:'wendys-healthy-meals-macros.html',
 why:'One burger with the standard cheese, toppings and sauces. Add sides and drinks separately.'},
{chain:'Taco Bell',name:'Cantina Chicken Soft Taco',cal:260,p:null,c:null,f:null,na:null,
 t:[],diet:[],meal:'main',size:'small',
 url:'taco-bell-healthy-meals-macros.html',
 why:'One standard Cantina Chicken Soft Taco. Current calories are confirmed; check Taco Bell for the remaining nutrition.'},
{chain:'Taco Bell',name:'Cantina Chicken Bowl',cal:520,p:25,c:null,f:null,na:null,
 t:['protein','balanced'],diet:[],meal:'main',size:'medium',
 url:'taco-bell-healthy-meals-macros.html',
 why:'The current chicken bowl with rice, black beans and standard toppings. Taco Bell lists 520 calories and 25 g protein.'},
{chain:'Taco Bell',name:'Veggie Bowl',cal:410,p:null,c:null,f:null,na:null,
 t:[],diet:['vegetarian'],meal:'main',size:'medium',
 url:'taco-bell-healthy-meals-macros.html',
 why:'Standard bowl with rice, black beans, vegetables, cheese and sauces. Vegetarian, with dairy and egg ingredients.'},
{chain:'Taco Bell',name:'Bean Burrito',cal:360,p:null,c:null,f:null,na:null,
 t:[],diet:['vegetarian'],meal:'main',size:'medium',
 url:'taco-bell-healthy-meals-macros.html',
 why:'The standard bean burrito, including cheese. Vegetarian, not vegan. Check the official menu for other nutrients.'},
{chain:'Taco Bell',name:'Cantina Chicken Burrito',cal:570,p:null,c:null,f:null,na:null,
 t:[],diet:[],meal:'main',size:'medium',
 url:'taco-bell-healthy-meals-macros.html',
 why:'One standard Cantina Chicken Burrito.'},
{chain:'Panda Express',name:'Grilled Teriyaki Chicken',cal:275,p:33,c:14,f:0,na:470,
 t:['protein','light','lowsodium'],diet:[],meal:'main',size:'medium',
 url:'panda-express-healthy-meals-macros.html',
 why:'One standard chicken entree. A side, drink and extra sauce are separate.'},
{chain:'Panda Express',name:'Super Greens side',cal:130,p:9,c:14,f:7,na:370,
 t:['fibre'],diet:['vegetarian','plant'],meal:'main',size:'small',
 url:'panda-express-healthy-meals-macros.html',
 why:'A full side of broccoli, kale and cabbage. Pair with an entree when you want a larger meal.'},
{chain:'Panda Express',name:'String Bean Chicken Breast',cal:210,p:12,c:13,f:5,na:560,
 t:['fibre'],diet:[],meal:'main',size:'small',
 url:'panda-express-healthy-meals-macros.html',
 why:'One standard chicken-and-vegetable entree. Rice or another side is separate.'},
{chain:'Panda Express',name:'Grilled Teriyaki Chicken with Super Greens',cal:405,p:42,c:28,f:7,na:840,
 t:['protein','fibre','balanced'],diet:[],meal:'main',size:'medium',
 url:'panda-express-healthy-meals-macros.html',
 why:'One grilled teriyaki chicken entree and one full Super Greens side: 275 + 130 calories. Extra sauce and drinks are separate.'},
{chain:'Panda Express',name:'Broccoli Beef with white steamed rice',cal:670,p:25,c:130,f:2,na:520,
 t:['protein','energy','lowsodium'],diet:[],meal:'main',size:'large',
 url:'panda-express-healthy-meals-macros.html',
 why:'One broccoli beef entree and a full white-rice side: 150 + 520 calories.'},
// Checked 2026-08-23 against Panda Express's current U.S. nutrition table.
// Bigger Plate totals add one full side and the three named full entrée servings.
{chain:'Panda Express',name:'Bigger Plate: fried rice + 3 grilled teriyaki chicken entrées',cal:1445,p:112,c:143,f:1,na:2410,
 t:['protein','energy'],diet:[],meal:'main',size:'large',
 url:'panda-express-healthy-meals-macros.html',
 why:'Fried rice and three full grilled teriyaki chicken entrees. This very large order has 2,410 mg sodium before extra sauce or drinks.'},
{chain:'Panda Express',name:'Bigger Plate: chow mein + grilled teriyaki + orange chicken + string bean chicken',cal:1595,p:76,c:174,f:14,na:2880,
 t:['protein','energy','fibre'],diet:[],meal:'main',size:'large',
 url:'panda-express-healthy-meals-macros.html',
 why:'A full chow mein side with grilled teriyaki chicken, orange chicken and string bean chicken. This very large order has 2,880 mg sodium before extra sauce or drinks.'},
{chain:'KFC',name:'Original Recipe Drumstick',cal:130,p:12,c:4,f:1,na:430,
 t:[],diet:[],meal:'main',size:'small',
 url:'kfc-healthy-meals-macros.html',
 why:'One breaded drumstick. This small portion is an add-on rather than a full meal.'},
{chain:'KFC',name:'Original Recipe Breast',cal:390,p:39,c:11,f:2,na:1190,
 t:['protein','light'],diet:[],meal:'main',size:'medium',
 url:'kfc-healthy-meals-macros.html',
 why:'One breaded chicken breast. Sides, biscuit and sauces are separate.'},
{chain:'KFC',name:'Kentucky Grilled Chicken Breast',cal:210,p:38,c:0,f:0,na:710,
 t:['protein'],diet:['gluten'],meal:'main',size:'medium',
 url:'kfc-healthy-meals-macros.html',
 why:'One grilled breast from KFC’s nutrition list. Grilled chicken availability varies; check your restaurant.'},
{chain:'KFC',name:'Green Beans, individual',cal:25,p:1,c:5,f:3,na:300,
 t:[],diet:['vegetarian','plant','gluten'],meal:'main',size:'small',
 url:'kfc-healthy-meals-macros.html',
 why:'One individual side from KFC’s nutrition list. Availability varies by restaurant.'},
{chain:'KFC',name:'Grilled Breast with green beans and corn',cal:305,p:41,c:21,f:5,na:1010,
 t:['protein','light','fibre'],diet:[],meal:'main',size:'medium',
 url:'kfc-healthy-meals-macros.html',
 why:'One grilled breast plus individual green beans and sweet kernel corn: 210 + 25 + 70 calories. Check local availability.'},
{chain:'Popeyes',name:'3 Blackened Tenders',cal:170,p:28,c:2,f:1,na:860,
 t:['protein'],diet:[],meal:'main',size:'small',
 url:'popeyes-healthy-meals-macros.html',
 why:'Three blackened tenders, without a biscuit, side or dipping sauce. A small protein portion.'},
{chain:'Popeyes',name:'5 Blackened Tenders',cal:280,p:47,c:4,f:1,na:1430,
 t:['protein','light'],diet:[],meal:'main',size:'medium',
 url:'popeyes-healthy-meals-macros.html',
 why:'Five blackened tenders, without sides or sauces. High in protein, with 1,430 mg sodium.'},
{chain:'Popeyes',name:'Red Beans & Rice, regular',cal:260,p:7,c:29,f:6,na:580,
 t:['fibre'],diet:[],meal:'main',size:'small',
 url:'popeyes-healthy-meals-macros.html',
 why:'One regular side. Do not treat this as a vegetarian option; confirm ingredients with Popeyes.'},
{chain:'Popeyes',name:'3 Blackened Tenders with regular red beans and rice',cal:430,p:35,c:31,f:7,na:1440,
 t:['protein','fibre','balanced'],diet:[],meal:'main',size:'medium',
 url:'popeyes-healthy-meals-macros.html',
 why:'Three blackened tenders plus one regular red beans and rice: 170 + 260 calories. Biscuit and sauce are not included.'},
{chain:'Jersey Mike’s',name:'Turkey and Provolone Bowl, Mike’s Way',cal:490,p:30,c:8,f:2,na:1125,
 t:['protein','balanced'],diet:[],meal:'main',size:'medium',
 url:'jersey-mikes-healthy-subs-macros.html',
 why:'Standard bowl with cheese, oil, vinegar and Mike’s Way vegetables and seasoning. No extra add-ons. Nutrients rounded from the official builder.'},
{chain:'Jersey Mike’s',name:'Mini Turkey and Provolone, Mike’s Way',cal:480,p:26,c:44,f:3,na:1153,
 t:['protein','balanced'],diet:[],meal:'main',size:'small',
 url:'jersey-mikes-healthy-subs-macros.html',
 why:'Standard mini with cheese, oil, vinegar and Mike’s Way vegetables and seasoning. White bread. Nutrients rounded from the official builder.'},
{chain:'Jersey Mike’s',name:'Turkey and Provolone Wrap, Mike’s Way',cal:780,p:38,c:56,f:4,na:1695,
 t:['protein','energy'],diet:[],meal:'main',size:'large',
 url:'jersey-mikes-healthy-subs-macros.html',
 why:'Standard wrap with cheese, oil, vinegar and Mike’s Way vegetables and seasoning. No extra add-ons. Nutrients rounded from the official builder.'},
{chain:'Jersey Mike’s',name:'Regular Veggie Sub, Mike’s Way',cal:950,p:39,c:69,f:5,na:1310,
 t:['protein','energy','fibre'],diet:['vegetarian'],meal:'main',size:'large',
 url:'jersey-mikes-healthy-subs-macros.html',
 why:'Standard regular with cheese, oil, vinegar and Mike’s Way vegetables and seasoning. White bread. Nutrients rounded from the official builder.'},
{chain:'Dunkin’',name:'Egg & Cheese Wake-Up Wrap',cal:180,p:7,c:14,f:0,na:470,
 t:[],diet:['vegetarian'],meal:'breakfast',size:'small',
 url:'dunkin-healthy-breakfast-macros.html',
 why:'One small egg-and-cheese wrap. It has 7 g protein, so treat it as a light breakfast or add-on.'},
{chain:'Dunkin’',name:'Egg & Cheese English Muffin',cal:340,p:14,c:38,f:1,na:650,
 t:[],diet:['vegetarian'],meal:'breakfast',size:'medium',
 url:'dunkin-healthy-breakfast-macros.html',
 why:'One egg-and-cheese sandwich on an English muffin. Drinks and hash browns are separate.'},
{chain:'Dunkin’',name:'Turkey Sausage Wake-Up Wrap',cal:230,p:11,c:15,f:0,na:660,
 t:[],diet:[],meal:'breakfast',size:'small',
 url:'dunkin-healthy-breakfast-macros.html',
 why:'One small wrap with turkey sausage, egg and cheese. Add other food if this is not enough for your appetite.'},
{chain:'Dunkin’',name:'Sourdough Breakfast Sandwich',cal:630,p:30,c:58,f:3,na:1300,
 t:['protein','energy'],diet:[],meal:'breakfast',size:'large',
 url:'dunkin-healthy-breakfast-macros.html',
 why:'One standard sourdough breakfast sandwich. A larger breakfast with 30 g protein; coffee and sides are separate.'}
];
