/* Shared static/interactive meal presentation; no nutrition calculations. */
(function(global){'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=(v,u='')=>Number.isFinite(v)?v.toLocaleString('en-US')+(u?' '+u:''):'Not verified';
const paths={arrow:'M5 12h14m-5-5 5 5-5 5',save:'M6 4h12v17l-6-4-6 4Z',compare:'M5 5v14m14-14v14M2 8h6m8 8h6',filter:'M4 6h16M4 12h16M4 18h16M9 3v6m6 0v6M9 15v6',search:'M15 15l6 6',close:'m6 6 12 12M18 6 6 18'};
const icon=name=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(name==='search'?'<circle cx="10" cy="10" r="6.5"/>':'')+'<path d="'+paths[name]+'"/></svg>';
function card(m,id,{saved=false,selected=false,state={},home=false}={}){
const title=m.name.replace('High-protein bulking order: ',''),portion=m.serving||'1 listed order',market=m.country==='CA'||m.market==='CA'?'Canadian menu':'U.S. menu';
const missing=[['cal','calories'],['p','protein'],['c','carbs'],['fat','fat']].filter(([k])=>!Number.isFinite(m[k])).map(([,label])=>label);
const missingNote=missing.length?'<p class="macro-missing">Macro information missing: '+esc(missing.join(', '))+'. Known values remain usable.</p>':'';
const reasons=[];if(state.maxCal!=null)reasons.push('Within your calorie limit');if(state.minProtein!=null)reasons.push('Meets your protein target');if(state.minFiber!=null)reasons.push('Meets your fiber target');if(state.maxSodium!=null)reasons.push('Within your sodium limit');
const provenance=m.nutrientProvenance?'<details class="meal-provenance"><summary>How these figures were checked</summary>'+(m.sourceReview?'<p>All core macros, fiber and sodium rechecked '+esc(m.sourceReview.reviewedAt)+' in the <a href="'+esc(m.sourceReview.source)+'">official full table</a>. Original checks below remain part of the history.</p>':'')+'<ul>'+[['cal','Calories'],['p','Protein'],['c','Carbs'],['fat','Fat'],['f','Fiber'],['na','Sodium']].map(([k,l])=>{const p=m.nutrientProvenance[k];return p?'<li>'+l+': '+esc(p.method)+' · '+esc(p.retrieved)+(p.source?' · <a href="'+esc(p.source)+'">Source</a>':'')+'</li>':'';}).join('')+'</ul></details>':'';
return `<article class="meal-row order-ticket" data-meal-id="${id}"><header class="order-identity"><a href="${esc(m.url)}">${esc(m.chain)}</a>${home?'':'<button class="icon-action" type="button" data-save="'+id+'" aria-pressed="'+saved+'" aria-label="'+(saved?'Unsave ':'Save ')+esc(title)+'">'+icon('save')+'<span>'+(saved?'Saved':'Save')+'</span></button>'}</header><div class="order-heading"><h2>${esc(title)}</h2><p>${portion.length<85?esc(portion):'Listed ingredient portions'} · ${market}</p></div><dl class="meal-numbers"><div><dd>${number(m.cal)}<span> kcal</span></dd><dt>Calories</dt></div><div><dd>${number(m.p)}${Number.isFinite(m.p)?'<span> g</span>':''}</dd><dt>Protein</dt></div></dl>${missingNote}${reasons.length?'<p class="match-facts">'+esc(reasons.join(' · '))+'</p>':''}${home?'<a class="text-action" href="restaurant-meal-finder.html?chain='+encodeURIComponent(m.chain)+'">Browse '+esc(m.chain)+icon('arrow')+'</a>':`<div class="meal-actions"><details class="meal-detail"><summary>View meal ${icon('arrow')}</summary><div class="meal-detail-body"><p class="meal-full-portion">${esc(portion)} · ${market}</p><dl class="full-nutrition">${[['cal','Calories','kcal'],['p','Protein','g'],['c','Carbs','g'],['fat','Fat','g'],['f','Fiber','g'],['na','Sodium','mg']].map(([k,l,u])=>'<div><dt>'+l+'</dt><dd>'+number(m[k],u)+'</dd></div>').join('')}</dl><p>${esc(m.why)}</p>${m.source?'<p class="source-note"><a href="'+esc(m.source)+'">Official nutrition source</a> · Source inspected '+esc(m.checked)+'. '+esc(m.notes)+'</p>':'<p>Source unavailable.</p>'}${provenance}<p class="source-note">Extras are separate unless listed. Unknown values are not zero.</p><a href="${esc(m.url)}">Restaurant guide</a><button class="quiet-button" type="button" data-order-card="${id}">Download order card</button></div></details><label class="compare-choice"><input type="checkbox" data-compare="${id}"${selected?' checked':''}>${icon('compare')}<span>Compare</span></label></div>`}</article>`;
}
function filters(meals,s,E){const chains=[...new Set(meals.map(m=>m.chain))].sort((a,b)=>a.localeCompare(b));const choices=(k,items)=>items.map(([v,l])=>'<label class="finder-choice"><input type="checkbox" name="'+k+'" value="'+esc(v)+'"'+(s[k].includes(v)?' checked':'')+'><span>'+esc(l)+'</span></label>').join('');const field=k=>'<label>'+E.limits[k][2]+'<input type="number" name="'+k+'" min="'+E.limits[k][0]+'" max="'+E.limits[k][1]+'" step="1" inputmode="numeric" placeholder="Any" value="'+(s[k]??'')+'"></label>';
const hasDiet=meals.some(m=>(m.diet||[]).length),hasSize=meals.some(m=>m.size);
let markup=`<form id="finder-filters"><div class="filter-panel-head"><h2>Filters</h2><button type="button" data-close-filters>Done</button></div><details class="restaurant-picker"><summary><span>Restaurant</span></summary><div class="restaurant-checks">${choices('chain',chains.map(c=>[c,c]))}</div></details><div class="filter-primary"><fieldset><legend class="sr-only">Nutrition limits</legend>${field('maxCal')}${field('minProtein')}</fieldset></div><details class="diet-picker"><summary>Dietary preferences</summary><fieldset><legend class="sr-only">Ingredient preferences</legend>${choices('diet',[['vegetarian','Vegetarian'],['plant','Plant-based']])}<p class="filter-note">Confirm allergens with the restaurant. These filters do not check allergy safety.</p></fieldset></details><details class="filter-more"><summary>More filters</summary><div class="filter-expanded"><fieldset><legend>Priorities</legend>${choices('goal',[['protein','More protein'],['light','Fewer calories'],['energy','A bigger meal'],['fibre','More fiber'],['lowsodium','Lower sodium']])}<p class="filter-note">Priorities sort results. Limits exclude meals.</p></fieldset><fieldset><legend>Meal time</legend>${choices('meal',[['main','Lunch or dinner'],['breakfast','Breakfast']])}</fieldset><fieldset><legend>Other nutrients</legend>${field('minFiber')}${field('maxSodium')}<label>Preferred size<select name="size"><option value="">Any</option>${[['small','Small'],['medium','Regular'],['large','Large']].map(([v,l])=>'<option value="'+v+'"'+(s.size[0]===v?' selected':'')+'>'+l+'</option>').join('')}</select></label><label class="finder-choice"><input type="checkbox" name="incomplete"${!s.complete?' checked':''}><span>Include items with missing macros</span><small>Complete macros means calories, protein, carbs and fat. Fiber and sodium are checked separately when filtered.</small></label></fieldset></div></details><button class="quiet-button filter-reset" type="reset">Reset filters</button></form>`;if(!hasDiet)markup=markup.replace(/<details class="diet-picker">[\s\S]*?<\/details>/,'<details class="diet-picker"><summary>Ingredient information</summary><p class="filter-note">Dietary classifications are not verified for this selection. Read the restaurant source and confirm ingredients locally.</p></details>');if(!hasSize)markup=markup.replace(/<label>Preferred size[\s\S]*?<\/label>/,'');return markup;}
function shell(meals,s,E,{rows='',count=0,savedOnly=false}={}){return `<div class="discovery-paths"><button class="text-action" type="button" data-open-guide>Try the meal quiz ${icon('arrow')}</button><div class="discovery-path-actions"><button class="quiet-button" type="button" data-browse aria-pressed="${!savedOnly}">All meals</button><button class="quiet-button" type="button" data-show-saved aria-pressed="${savedOnly}">Saved meals</button></div></div><div class="discovery-product"><aside class="finder-sidebar">${filters(meals,s,E)}</aside><div class="finder-results"><div class="finder-toolbar"><p class="results-count" role="status" aria-live="polite">${count} ${s.market==='CA'?'items':'meals'} match</p><button class="filter-launch" type="button" data-open-filters>${icon('filter')}Filters <span data-filter-count></span></button><label class="sort-label">Sort<select name="sort"><option value="match">Preference order</option><option value="calories">Lowest calories</option><option value="protein">Most protein</option></select></label></div><div class="active-preferences" aria-label="Active filters"></div><button class="text-action" type="button" data-surprise>Surprise me ${icon('arrow')}</button><div class="results-grid">${rows}</div><button class="text-action results-more" type="button" data-more>Show more meals ${icon('arrow')}</button><div class="finder-end"><a class="home-all-results" href="restaurant-meal-finder.html" hidden>All matching meals</a><p>${meals[0]?.country==='CA'?'Canadian selection':'U.S. menus'}. Listed portions; local orders can vary. <a href="/sources.html">Sources</a></p><button class="quiet-button" type="button" data-share>Share results</button><button class="quiet-button" type="button" data-print>Print</button><p data-share-status role="status"></p></div></div></div><div class="compare-tray" hidden><span data-compare-count></span><button class="btn btn-primary" type="button" data-open-compare>Compare meals</button><button class="quiet-button" type="button" data-clear-compare>Clear</button></div><dialog class="compare-dialog" aria-labelledby="compare-title"><div class="dialog-heading"><h2 id="compare-title">Compare meals</h2><button class="quiet-button" type="button" data-close-compare>Close</button></div><div class="comparison-output" tabindex="0" role="region" aria-label="Meal comparison"></div></dialog><dialog class="filter-dialog" aria-label="Meal filters"></dialog><dialog class="guided-dialog" aria-labelledby="guide-title"></dialog>`;}
global.GetMacrosMealView={esc,number,icon,card,filters,shell};
})(typeof window==='undefined'?globalThis:window);
