/* Optional workspaces load menu data only after an explicit request. */
(function(){'use strict';const C=window.GetMacrosOrderCore;if(!C)return;let pending;
function script(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>{s.remove();reject(new Error('Menu file unavailable'));};document.head.append(s);});}
function catalogueRecord(r){const n=r.nutrients;return {id:r.id,chain:r.restaurant||r.chain,name:r.name,region:r.country==='US'?'U.S.':r.country,serving:r.portion.label,checked:r.source.checkedAt,source:r.source.url,sourceDate:null,category:r.category,temperature:r.temperature,size:r.size,notes:Array.isArray(r.notes)?r.notes.join(' '):r.notes||r.build||'',url:'chick-fil-a-healthy-meals-macros.html',cal:n.calories,p:n.proteinG,c:n.carbsG,fat:n.fatG,f:n.fiberG,na:n.sodiumMg,sugar:n.totalSugarG,bounds:r.bounds,why:''};}
async function records(){if(pending)return pending;pending=(async()=>{if(!window.GM_MEALS)await script('js/meal-data.js');if(!window.GM_MEALS[0]?.checked)await script('js/meal-provenance.js');const response=await fetch('js/order-catalogue.json',{cache:'no-cache'});if(!response.ok)throw new Error('Additional menu file unavailable');const data=await response.json();if(!Array.isArray(data.records)||!data.records.length)throw new Error('No verified components available');const baseline=window.GM_MEALS.map(m=>({...m,category:'Recorded order'}));for(const r of data.records.filter(r=>!r.isNew&&r.baselineKey)){const at=baseline.findIndex(m=>C.key(m)===r.baselineKey);if(at>=0)baseline[at]={...baseline[at],...catalogueRecord(r),id:r.baselineKey};}return [...baseline,...data.records.filter(r=>r.isNew).map(catalogueRecord)];})().catch(error=>{pending=null;throw error;});return pending;}
window.GetMacrosOrderTools=Object.freeze({records,catalogueRecord});
function sourceNote(m){return '<p class="source-note">'+C.esc(m.serving)+' · '+C.esc(m.region)+' · Checked '+C.esc(m.checked||'not established')+' · Snapshot '+C.version(m)+'. <a href="'+C.esc(m.source)+'">Official source</a></p><p class="clarity-hint">'+C.esc(m.notes||m.why||'Extras are separate unless the recorded build includes them.')+'</p>';}
function options(rows,empty='Choose an exact menu item'){return '<option value="">'+empty+'</option>'+rows.map(m=>'<option value="'+C.esc(C.key(m))+'">'+C.esc(m.chain+' — '+m.name+' · '+m.serving)+'</option>').join('');}
function rowLookup(rows,id){return rows.find(m=>C.key(m)===id);}
async function mount(root){const mode=root.dataset.orderTool,button=root.querySelector('[data-order-load]'),status=root.querySelector('[data-order-status]'),workspace=root.querySelector('[data-order-workspace]');let rows=[];
 async function start(){button.disabled=true;status.textContent='Loading source-linked menu records…';try{rows=await records();if(mode==='drink')rows=rows.filter(m=>['drinks','drink','coffee'].includes(m.category.toLowerCase()));if(!rows.length)throw new Error('No verified drinks');workspace.hidden=false;button.hidden=true;status.textContent='';paint();}catch{workspace.hidden=true;button.hidden=false;status.textContent='Menu records could not load. Try again, or use the source-linked table above.';button.disabled=false;}}
 function paint(){if(mode==='builder')builder();else comparator();}
 function comparator(){workspace.innerHTML='<form class="order-selector"><label>First '+(mode==='drink'?'drink':'order')+'<select name="a" required>'+options(rows)+'</select></label><label>Second '+(mode==='drink'?'drink':'order')+'<select name="b" required>'+options(rows)+'</select></label><button class="btn btn-primary" type="submit">Compare exact portions</button></form><div data-order-output aria-live="polite"></div>';const form=workspace.querySelector('form'),out=workspace.querySelector('[data-order-output]');const q=new URLSearchParams(location.search).getAll('item').slice(0,2);q.forEach((id,i)=>{if(rowLookup(rows,id))form.elements[i?'b':'a'].value=id;});form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const selected=[rowLookup(rows,form.elements.a.value),rowLookup(rows,form.elements.b.value)];if(selected.some(m=>!m)){out.textContent='A selected record is no longer available. Choose a current menu item.';return;}out.innerHTML=C.comparisonTable(selected,new URLSearchParams(location.search).getAll('snapshot'))+(mode==='drink'?'<p>Temperature and size follow the exact published name. An unnamed temperature is not inferred. Added sugars are not established by the total-sugars line.</p>':'')+'<button class="quiet-button" type="button" data-order-link>Copy this comparison link</button><p data-order-link-status role="status"></p>';out.querySelector('[data-order-link]').addEventListener('click',async()=>{const url=new URL(location.href);url.search='';selected.forEach(m=>{url.searchParams.append('item',C.key(m));url.searchParams.append('snapshot',C.version(m));});url.hash=root.id;const target=out.querySelector('[data-order-link-status]');try{await navigator.clipboard.writeText(url.href);target.textContent='Comparison link copied.';}catch{target.textContent='Copy this link: '+url.href;}});});if(q.length&&q.some(id=>!rowLookup(rows,id)))out.textContent='A linked record is no longer available. Choose two current menu items.';else if(q.length===2&&form.elements.a.value&&form.elements.b.value)form.requestSubmit();}
 function builder(){let lines=[];workspace.innerHTML='<form class="order-selector"><label>Exact menu item<select name="item" required>'+options(rows)+'</select></label><label>Whole listed portions<input name="quantity" type="number" min="1" max="20" step="1" value="1" required></label><label class="extra-packet-confirm" hidden><input type="checkbox" name="extraPacket"> This is a separate extra packet. The listed build may already include sauce or dressing.</label><button class="btn btn-primary" type="submit">Add to order</button></form><p class="clarity-hint">Choose the published build first. A sandwich or salad may already include a sauce or dressing. Check its source notes before adding a separate packet. Removing a row removes that whole item; it does not subtract an assumed ingredient.</p><div data-order-lines></div><div data-order-output aria-live="polite"></div><button class="quiet-button" type="button" data-order-clear>Clear order</button>';const form=workspace.querySelector('form'),list=workspace.querySelector('[data-order-lines]'),out=workspace.querySelector('[data-order-output]');form.elements.namedItem('item').addEventListener('change',()=>{const m=rowLookup(rows,form.elements.namedItem('item').value),packet=m&&['sauce','dressing'].includes(m.category);form.querySelector('.extra-packet-confirm').hidden=!packet;form.elements.extraPacket.required=!!packet;form.elements.extraPacket.checked=false;});function render(){list.innerHTML=lines.map((line,i)=>'<article class="order-line"><h3>'+C.esc(line.record.name)+' × '+line.quantity+'</h3>'+sourceNote(line.record)+'<button class="quiet-button" type="button" data-order-remove="'+i+'">Remove '+C.esc(line.record.name)+'</button></article>').join('');if(!lines.length){out.innerHTML='<p>No components added yet.</p>';return;}const totals=C.subtotal(lines);out.innerHTML='<h3>Your assembled order</h3>'+C.warnings(lines.map(l=>l.record)).map(note=>'<p class="comparison-context">'+C.esc(note)+'</p>').join('')+'<dl class="order-totals">'+Object.entries(C.fields).map(([k,[label,unit]])=>'<div><dt>'+label+'</dt><dd>'+(totals[k].complete?totals[k].known.toLocaleString('en-US')+' '+unit:'Unknown total')+(totals[k].complete?'':' <small>'+(totals[k].missing.length===lines.length?'':'Known subtotal: '+totals[k].known.toLocaleString('en-US')+' '+unit+'; ')+totals[k].missing.length+' component value'+(totals[k].missing.length===1?'':'s')+' unknown</small>')+'</dd></div>').join('')+'</dl><p class="clarity-hint">Calculated from your selected whole portions. This is a GetMacros component sum, not a restaurant-published combo. It does not verify the ingredients or safety of a customised order.</p><button class="quiet-button" type="button" data-order-save aria-pressed="false">Save this exact order</button>';}
 form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;if(lines.length>=12){status.textContent='An order can contain up to 12 rows. Remove a row to add another.';return;}const record=rowLookup(rows,form.elements.namedItem('item').value);if(!record){status.textContent='Choose a current menu item.';return;}lines.push({record,quantity:Number(form.elements.quantity.value)});status.textContent=record.name+' added.';render();});workspace.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-order-save')&&lines.length){const saved=GetMacrosNotebook.toggle(C.assembled(lines));if(saved){const active=saved.includes(C.key(C.assembled(lines)));b.setAttribute('aria-pressed',String(active));b.textContent=active?'Order saved':'Save this exact order';status.textContent=active?'Exact components saved in this browser.':'Order removed from the notebook.';}else status.textContent='This browser could not save the order. Existing saves are unchanged.';}if(b.dataset.orderRemove!==undefined){lines.splice(Number(b.dataset.orderRemove),1);render();form.elements.namedItem('item').focus();}if(b.hasAttribute('data-order-clear')){lines=[];render();status.textContent='Order cleared.';form.elements.namedItem('item').focus();}});render();}
 button.addEventListener('click',start);if(new URLSearchParams(location.search).has('item')&&location.hash==='#'+root.id)start();
}
function init(){document.querySelectorAll('[data-order-tool]').forEach(mount);const snapshot=document.querySelector('#component-snapshot');if(snapshot){const input=snapshot.querySelector('input[type=search]'),count=snapshot.querySelector('[data-snapshot-count]'),rows=[...snapshot.querySelectorAll('tbody tr')];input?.addEventListener('input',()=>{const term=input.value.toLowerCase().trim();let n=0;for(const row of rows){row.hidden=!row.textContent.toLowerCase().includes(term);if(!row.hidden)n++;}count.textContent=n+' component records shown';});}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
