/* The game library is loaded on Play pages only. No timer, audio or account. */
(function(){'use strict';
const R=window.GetMacrosPlayRules,meta=window.GM_PLAY_META,records=window.GM_PLAY_RECORDS||[];const foods=R?.foods||[];
if(!R||!meta)return;
const host=document.querySelector('[data-play-stage]'),live=document.querySelector('[data-play-feedback]');if(!host)return;const sprite=(document.querySelector('use[href*="food-characters.svg"]')?.getAttribute('href')||'images/food-characters.svg').split('#')[0];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.search);let seed=Math.abs(parseInt(params.get('seed'),10)||1);let g=R.create(meta.id,seed,records),cross=false;
const button=(text,action,extra='')=>`<button type="button" data-play-action='${esc(JSON.stringify(action))}' ${extra}>${text}</button>`;
const art=(food,label=true)=>`<svg class="play-food" viewBox="0 0 160 160" aria-hidden="true"><use href="${esc(sprite)}#food-${esc(food)}"/></svg>${label?`<span>${esc(food)}</span>`:''}`;
const choice=(text,i,selected=false,extra='')=>button(text,{type:'pick',index:i},`class="play-choice ${selected?'is-picked':''}" aria-pressed="${selected}" data-play-focus="pick-${i}" ${extra}`);
const check=()=>button('Check answer',{type:'check'},'class="btn btn-primary" data-play-focus="check"');
const clear=()=>button('Clear choices',{type:'clear'},'class="quiet-button" data-play-focus="clear"');
const basket=()=>'<svg class="play-basket" viewBox="0 0 100 80" aria-hidden="true"><path d="M25 24C25 0 75 0 75 24" fill="none" stroke="var(--green)" stroke-width="5"/><path d="M10 24h80L80 70H20Z" fill="var(--gold)" stroke="var(--green)" stroke-width="3"/><path d="M15 39h70M18 54h64M34 26l4 43m28-43-4 43" stroke="var(--green)" stroke-width="2" fill="none"/></svg>';
const paddle=()=>'<svg class="play-basket" viewBox="0 0 100 80" aria-hidden="true"><rect x="8" y="29" width="84" height="17" rx="8" fill="var(--green)"/><path d="M50 45v26" stroke="var(--green)" stroke-width="8" stroke-linecap="round"/></svg>';
const beat=(label)=>`<svg class="play-beat" viewBox="0 0 60 60" aria-hidden="true">${label==='Tap'?'<circle cx="30" cy="30" r="18" fill="currentColor"/>':label==='Hold'?'<rect x="9" y="23" width="42" height="14" rx="7" fill="currentColor"/>':'<circle cx="30" cy="30" r="18" stroke="currentColor" stroke-width="3" fill="none"/>'}</svg><span>${esc(label)}</span>`;
const wall=()=>'<svg class="play-garden-wall" viewBox="0 0 60 60" aria-hidden="true"><path d="M30 56V20M30 40C5 42 5 17 28 25M30 34C54 33 56 12 33 21" fill="var(--fresh)" stroke="var(--green)" stroke-width="3"/></svg>';
const parcel=()=>'<svg class="play-parcel" viewBox="0 0 60 60" aria-hidden="true"><rect x="8" y="15" width="44" height="36" rx="5" fill="var(--gold)"/><path d="M30 15v36M8 30h44M30 15C8 15 14 2 30 15C49 1 51 17 30 15" fill="none" stroke="var(--green)" stroke-width="3"/></svg>';
const directions=()=>`<div class="play-directions" aria-label="Movement">${['Up','Left','Right','Down'].map((x,i)=>button(x,{type:'move',index:g.pos+[-g.size,-1,1,g.size][i]},`data-play-focus="move-${i}"`)).join('')}</div>`;
function selectedLine(){return `<div class="play-selection" aria-label="Your sequence">${g.selected.length?g.selected.map((i,j)=>`<span><small>${j+1}</small>${esc(typeof g.options[i]==='object'?g.options[i].text:g.options[i])}</span>`).join(''):'Your sequence will appear here.'}</div>`;}
function field(x,i){return `<label class="play-field">${esc(x.label)}<input data-play-input="${i}" data-play-focus="input-${i}" value="${esc(x.value)}" ${g.kind==='crossword'?'type="text" maxlength="4" autocomplete="off" spellcheck="false"':'type="number" step="any" inputmode="decimal"'}></label>`;}
function board(cells,size,render){return `<div class="play-board play-board-${size}" style="--play-cols:${size}">${cells.map(render).join('')}</div>`;}
function gridButton(text,index,type='cell',extra=''){const custom=extra.match(/class="([^"]*)"/);return button(text,{type,index},`class="${custom?custom[1]:'play-cell'}" data-play-focus="cell-${index}" ${extra.replace(/class="[^"]*"/,'')}`);}
function mascot(values){const colors={egg:'#f3e5b4',strawberry:'#d47168',broccoli:'#78a36c',avocado:'#bbce7e',potato:'#d8b881',banana:'#efd16c',carrot:'#dc9958',tomato:'#d77365'},paths={egg:'M80 20C49 20 30 81 30 111C30 148 130 148 130 111C130 81 111 20 80 20Z',banana:'M35 30C26 85 57 126 128 114C76 101 50 67 35 30Z',broccoli:'M56 90H104L111 144H49L56 90ZM42 96C4 83 7 36 46 35C48 1 105 1 113 32C155 20 158 80 124 96C105 116 57 115 42 96Z',carrot:'M42 40H118L80 148Z',strawberry:'M35 46C10 70 50 136 80 147C110 136 150 70 125 46C104 20 56 20 35 46Z'};const body=paths[values.body]?`<path d="${paths[values.body]}"/>`:'<ellipse cx="80" cy="83" rx="55" ry="61"/>';const eyes=values.eyes==='sleepy'?'<path d="M59 77h9m24 0h9" stroke="#304632" stroke-width="3"/>':values.eyes==='bright'?'<circle cx="64" cy="76" r="6"/><circle cx="96" cy="76" r="6"/><circle cx="65" cy="74" r="2" fill="#fff"/><circle cx="97" cy="74" r="2" fill="#fff"/>':'<circle cx="64" cy="76" r="3"/><circle cx="96" cy="76" r="3"/>';const mouth=values.mouth==='surprised'?'<ellipse cx="80" cy="96" rx="4" ry="6"/>':values.mouth==='grin'?'<path d="M68 92H92Q80 111 68 92Z"/>':'<path d="M71 93q9 10 18 0" fill="none" stroke="#304632" stroke-width="3"/>';return `<svg viewBox="0 0 160 160" role="img" aria-label="${esc(values.body+' with '+values.eyes+' eyes and '+values.mouth)}"><g fill="${colors[values.body]}">${body}</g><g fill="#304632" stroke-linecap="round">${eyes}${mouth}</g></svg>`;}
function content(){
switch(g.kind){
case 'number':case 'crossword':return `${g.kind==='crossword'?`<p class="play-crossing">Shared letter: position ${g.cross+1} in both words.</p>`:''}<div class="play-fields">${g.inputs.map(field).join('')}</div>${check()}`;
case 'balance':case 'mix':return `<div class="play-counter-row">${g.counts.map((c,i)=>`<div class="play-counter">${g.kind==='mix'?art(['strawberry','banana','avocado'][i]):`<span class="play-weight">${g.weights[i]} g / portion</span>`}<strong>${c}</strong><div>${button('−',{type:'count',index:i,value:c-1},`aria-label="Remove one ${g.kind==='mix'?g.options[i]:'portion from plate '+(i+1)}" data-play-focus="less-${i}"`)}${button('+',{type:'count',index:i,value:c+1},`aria-label="Add one ${g.kind==='mix'?g.options[i]:'portion to plate '+(i+1)}" data-play-focus="more-${i}"`)}</div>${g.kind==='balance'?`<small>Total: ${c*g.weights[i]} g</small>`:''}</div>`).join('')}</div>${check()}`;
case 'pairs':case 'assign':return `<div class="play-match-list">${(g.left||['Left compartment','Middle-left','Middle-right','Right compartment']).map((x,i)=>`<label>${esc(x)}<select data-play-pair="${i}" data-play-focus="pair-${i}"><option value="">Choose…</option>${g.options.map((v,j)=>`<option value="${j}" ${String(g.values[i])===String(j)?'selected':''}>${esc(v.text||v)}</option>`).join('')}</select></label>`).join('')}</div>${check()}`;
case 'choice':case 'select':case 'order':case 'groups':case 'domino':return `${g.meal?`<details class="play-order-reference"><summary>Order reference &amp; source</summary><p>${esc(g.meal.portion)} · U.S. menu</p><ul>${g.meal.ingredients.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><a href="${esc(g.meal.source)}" target="_blank" rel="noopener">Official source</a></details>`:''}${g.kind==='order'||g.kind==='domino'?selectedLine():''}<div class="play-choices ${g.id==='ingredient-anagrams'?'play-letter-choices':g.id==='kitchen-connections'?'play-word-choices':''}">${g.options.map((v,i)=>g.kind==='domino'?`<div class="play-domino">${choice(esc(g.flipped[i]?g.tiles[i].slice().reverse().join(' → '):v),i,g.selected.includes(i))}${button('Turn tile',{type:'flip',index:i},`class="quiet-button" aria-label="Turn tile ${i+1}" ${g.selected.includes(i)?'disabled':''}`)}</div>`:choice(esc(v),i,g.selected.includes(i),(g.kind==='order'&&g.selected.includes(i))?'disabled':'')).join('')}</div><div class="play-actions">${check()}${clear()}</div>${g.kind==='groups'?`<p>${g.found.length} of 2 groups found</p>`:''}`;
case 'maze':return `<div class="play-garden-scene">${board(Array.from({length:25}),5,(_,i)=>gridButton(g.pos===i?art(meta.character,false):g.walls.includes(i)?wall():i===g.goal?'<span class="play-gate">End</span>':g.required.includes(i)?`<span class="play-stop">${g.collected.includes(i)?'<svg class="play-collected" viewBox="0 0 40 40" aria-hidden="true"><path d="m8 20 8 8 17-19" fill="none" stroke="var(--green)" stroke-width="4"/></svg>':parcel()+`<small>${g.required.indexOf(i)+1}</small>`}</span>`:'',i,'move',`aria-label="Row ${Math.floor(i/5)+1}, column ${i%5+1}${g.pos===i?', current position':''}${g.walls.includes(i)?', garden hedge':''}${g.required.includes(i)?', stop '+(g.required.indexOf(i)+1):''}${i===g.goal?', finish':''}" ${g.walls.includes(i)?'disabled':''} ${g.pos===i?'aria-current="true"':''}`))}</div>`+directions()+`<p class="play-hint">${g.collected.length} of ${g.required.length} stops collected · Arrow keys work while the board has focus.</p>`;
case 'catch':case 'bounce':return `<div class="play-catch-scene"><svg class="play-canopy" viewBox="0 0 500 50" preserveAspectRatio="none" aria-hidden="true"><path d="M0 0H500V24Q475 48 450 24Q425 48 400 24Q375 48 350 24Q325 48 300 24Q275 48 250 24Q225 48 200 24Q175 48 150 24Q125 48 100 24Q75 48 50 24Q25 48 0 24Z" fill="var(--fresh)"/></svg><div class="play-lanes">${Array.from({length:5},(_,i)=>`<div class="play-lane ${g.lane===i?'is-picked':''}">${(g.kind==='catch'?g.targets[g.round]===i:g.ball===i)?`<span class="play-dropping-fruit">${art(g.kind==='catch'?g.options[g.round%5]:'strawberry',false)}</span>`:'<span class="play-lane-space"></span>'}${g.justCaught?.lane===i?`<span class="play-caught-fruit" aria-hidden="true">${art(g.justCaught.food,false)}</span>`:''}<span class="play-basket-position">${g.lane===i?(g.kind==='catch'?basket():paddle()):''}</span>${button(`Lane ${i+1}`,{type:'lane',index:i},`aria-pressed="${g.lane===i}" aria-label="Move ${g.kind==='catch'?'basket':'paddle'} to lane ${i+1}" data-play-focus="lane-${i}"`)}</div>`).join('')}</div></div><p>${g.kind==='catch'?`Requested fruit: ${esc(g.options[g.round%5])}. Move the basket underneath it.`:'Berry direction: '+(g.direction===1?'right':'left')+'. It reflects at the edge.'} ${g.round} of ${g.kind==='catch'?5:6} returns.</p>${button(g.kind==='catch'?'Catch':'Advance bounce',{type:'advance'},'class="btn btn-primary" data-play-focus="advance"')}`;
case 'orbit':return `<div class="play-orbit" aria-label="Orange at position ${g.pos+1}; target ${g.targets[g.round]+1}"><span class="play-orbit-center">${art('orange',false)}</span>${Array.from({length:8},(_,i)=>`<span style="--orbit-angle:${i*45}deg;--orbit-inverse:${-i*45}deg" class="play-orbit-slot ${i===g.targets[g.round]?'is-target':''}">${i===g.pos?art('orange',false):i+1}</span>`).join('')}</div><p>Target position ${g.targets[g.round]+1} · ${g.round} of 3 landings</p><div class="play-actions">${button('Turn one step',{type:'advance'},'data-play-focus="advance"')}${button('Land',{type:'land'},'class="btn btn-primary" data-play-focus="land"')}</div>`;
case 'stack':return `<div class="play-stack" aria-label="${g.selected.length} beans stacked">${g.selected.map((i,j)=>`<span style="--bean-lane:${i}">${art('beans',false)}<small>Layer ${j+1} · lane ${i}</small></span>`).reverse().join('')}<div class="play-support">Support: lanes 1.5–2.5</div></div><div class="play-choices">${g.options.map((x,i)=>choice(x,i)).join('')}</div><p>${g.selected.length} of 5 beans · ${g.selected.length?'Center: '+(g.selected.reduce((t,x)=>t+x,0)/g.selected.length).toFixed(2):'Start over the center.'}</p>`;
case 'pack':return `<div class="play-piece-controls">${g.shapes.map((shape,i)=>button(`<svg viewBox="0 0 80 80" aria-hidden="true">${shape.map(([y,x])=>`<rect x="${x*18+4}" y="${y*18+4}" width="16" height="16" rx="2"/>`).join('')}</svg>Piece ${i+1}`,{type:'piece',index:i},`aria-pressed="${g.piece===i}" data-play-focus="piece-${i}"`)).join('')}${button('Rotate selected',{type:'rotate'},'data-play-focus="rotate"')}</div><p>Selected piece ${g.piece+1} · rotation ${g.rotation*90}° · choose its top-left grid position.</p>${board(g.cells,4,(v,i)=>gridButton(v<0?'':`Piece ${v+1}`,i,'place',`class="play-cell ${g.target[i]?'play-target':''}" aria-label="Row ${Math.floor(i/4)+1} column ${i%4+1}${v>=0?', piece '+(v+1):''}${g.target[i]?', silhouette':''}"`))}${check()}`;
case 'pipes':return `${board(Array.from({length:9}),3,(_,i)=>{const p=g.path.indexOf(i);return p<0?'<span class="play-cell play-unused" aria-hidden="true"></span>':gridButton(`<svg viewBox="0 0 60 60" aria-hidden="true" style="transform:rotate(${g.rotations[p]*90}deg)"><path d="${[0,1,3].includes(p)?'M30 0v60':'M30 0v30h30'}"/></svg>`,p,'rotate',`aria-label="Pipe at row ${Math.floor(i/3)+1} column ${i%3+1}, rotation ${g.rotations[p]*90} degrees"`);})}<p>Inlet: left of top-left pipe. Outlet: right of bottom-right pipe.</p>${check()}`;
case 'slide':return board(g.cells,3,(v,i)=>gridButton(v?`<span>${v}</span>${art(foods[(v-1)%8],false)}`:'Gap',i,'slide',`aria-label="${v?'Tile '+v:'Empty space'} at row ${Math.floor(i/3)+1} column ${i%3+1}" ${v===0?'disabled':''}`));
case 'grid':return `<div class="play-nonogram"><div class="play-column-clues">${g.cols.map(x=>`<span>${x.join(' ')}</span>`).join('')}</div><div class="play-nonogram-body"><div class="play-row-clues">${g.rows.map(x=>`<span>${x.join(' ')}</span>`).join('')}</div>${board(g.cells,4,(v,i)=>gridButton(v===1?'●':v===2?'×':'',i,'cell',`aria-pressed="${v===1}" aria-label="Row ${Math.floor(i/4)+1}, column ${i%4+1}, ${v===1?'filled':v===2?'marked empty':'unmarked'}"`))}</div></div><div class="play-actions">${button(cross?'Cross tool on':'Mark empty squares', {type:'cross'},`aria-pressed="${cross}"`)}${check()}</div>`;
case 'hunt':return `${board(g.cells,6,(v,i)=>gridButton(v,i,'cell',`aria-label="${v}, row ${Math.floor(i/6)+1} column ${i%6+1}" aria-pressed="${g.selected.includes(i)}"`))}<p>Find: ${g.words.map((x,i)=>g.found.includes(i)?`<s>${x}</s>`:x).join(' · ')}</p>`;
case 'numeric-grid':return `<div class="play-totals">Column totals: ${g.cols.join(' · ')} g</div>${board(g.cells,3,(v,i)=>i%4?`<span class="play-cell">${v} g</span>`:`<label class="play-cell"><span class="sr-only">Row ${Math.floor(i/3)+1}, column ${i%3+1}, grams</span><input type="number" inputmode="decimal" data-play-input="${i}" data-play-focus="input-${i}" value="${esc(v)}"></label>`)}<p>Row totals: ${g.rows.join(' · ')} g</p>${check()}`;
case 'fractions':return `<div class="play-fraction-plates">${[g.cells.slice(0,4),g.cells.slice(4)].map((a,k)=>`<div><p>Plate ${k+1}: ${a.filter(x=>x===1).length}/${a.length}</p>${board(a,k?3:2,(v,i)=>gridButton(v?'Shaded':'Shade',i+(k?4:0),'cell',`aria-pressed="${v===1}" aria-label="Plate ${k+1}, slice ${i+1}, ${v?'shaded':'empty'}"`))}</div>`).join('')}</div>${check()}`;
case 'sequence':case 'recall':case 'chef':return `${g.revealed?`<div class="play-sequence-display" aria-label="Sequence to remember">${g.target.slice(0,g.kind==='chef'?g.round:g.target.length).map(i=>`<span>${g.kind==='sequence'?beat(g.options[i]):art(g.options[i])}</span>`).join('')}</div>`:selectedLine()}${button(g.revealed?'Hide & answer':'Study again',{type:'study'},'data-play-focus="study"')}<div class="play-choices play-recall-choices">${g.options.map((x,i)=>choice(g.kind==='sequence'?beat(x):art(x),i,false,g.revealed?'disabled':'')).join('')}</div><div class="play-actions">${check()}${clear()}</div>`;
case 'peek':return `${g.revealed?`<div class="play-pantry-scene">${g.options.map(x=>`<span>${art(x)}</span>`).join('')}</div>`:''}${button(g.revealed?'Hide pantry':'Study again',{type:'study'},'data-play-focus="study"')}${g.revealed?'':g.inputs.map(field).join('')+check()}`;
case 'memory':return `${board(g.options,4,(v,i)=>choice((g.found.includes(i)||g.selected.includes(i))?art(v):'<span class="play-card-back">?</span>',i,g.selected.includes(i),`aria-label="Tile ${i+1}, ${g.found.includes(i)?'matched '+v:g.selected.includes(i)?v:'hidden'}" ${g.found.includes(i)?'disabled':''}`))}${g.selected.length===2?button('Continue',{type:'clear'},'data-play-focus="clear"'):''}<p>${g.found.length/2} of 4 pairs found · ${g.turns} moves</p>`;
case 'spot':return `<div class="play-scene-pair"><div><h3>Before</h3><div class="play-pantry-scene">${g.left.map((x,i)=>`<span>${art(x)}<small>${i+1}</small></span>`).join('')}</div></div><div><h3>After</h3><div class="play-pantry-scene">${g.options.map((x,i)=>choice(art(x),i,g.selected.includes(i),`aria-label="After scene position ${i+1}, ${x}"`)).join('')}</div></div></div>${check()}`;
case 'silhouette':return `<div class="play-silhouette" aria-label="Food silhouette"><svg viewBox="0 0 160 160" aria-hidden="true"><path d="${{pear:'M80 16C65 18 72 47 57 61C24 86 28 133 80 143C132 133 136 86 103 61C88 47 95 18 80 16Z',banana:'M35 30C26 85 57 126 128 114C76 101 50 67 35 30Z',egg:'M80 20C50 20 28 82 30 111C32 148 128 148 130 111C132 82 110 20 80 20Z',broccoli:'M56 90H104L111 144H49L56 90ZM42 96C4 83 7 36 46 35C48 1 105 1 113 32C155 20 158 80 124 96C105 116 57 115 42 96Z'}[g.options[g.answer[0]]]}"/></svg></div><details><summary>Describe the shape</summary><p>${{pear:'A small narrow top widening to a rounded bottom, with a short stem.',banana:'A long curved crescent that tapers toward one end.',egg:'A smooth oval, narrower at the top and rounder at the bottom.',broccoli:'A branching stem with a broad, bumpy crown.'}[g.options[g.answer[0]]]}</p></details><div class="play-choices">${g.options.map((x,i)=>choice(esc(x),i,g.selected.includes(i))).join('')}</div>${check()}`;
case 'art':return `<div class="play-stamps">${g.options.map((x,i)=>button(art(x),{type:'piece',index:i},`aria-pressed="${g.piece===i}" data-play-focus="piece-${i}"`)).join('')}</div>${board(g.cells,3,(v,i)=>gridButton(v<0?'Place here':art(g.options[v],false),i,'place',`aria-label="Plate position ${i+1}${v>=0?', '+g.options[v]:', empty'}"`))}${button('Save my plate',{type:'save'},'class="btn btn-primary" data-play-focus="save"')}`;
case 'mascot':return `<div class="play-mascot-preview">${mascot(g.values)}<span>${esc(g.values.eyes)} eyes · ${esc(g.values.mouth)}</span></div><div class="play-fields">${[['body','Ingredient',foods],['eyes','Eyes',['calm','bright','sleepy']],['mouth','Expression',['smile','grin','surprised']]].map(([key,label,options])=>`<label>${label}<select data-play-custom="${key}" data-play-focus="custom-${key}">${options.map(x=>`<option ${g.values[key]===x?'selected':''}>${x}</option>`).join('')}</select></label>`).join('')}</div>${button('Save my mascot',{type:'save'},'class="btn btn-primary" data-play-focus="save"')}`;
case 'mystery':return `<ul class="play-clues">${g.clues.slice(0,g.clue+1).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${button('Reveal next clue',{type:'clue'},`data-play-focus="clue" ${g.clue===g.clues.length-1?'disabled':''}`)}<div class="play-choices">${g.options.map((x,i)=>choice(`<strong>${esc(x.chain)}</strong><span>${esc(x.name)}</span>`,i,g.selected.includes(i))).join('')}</div>${check()}`;
case 'route':return `<svg class="play-route-map" viewBox="0 0 240 240" aria-hidden="true"><path d="M40 40H200V200H40Z"/>${g.coords.map((p,i)=>`<circle cx="${40+p[0]*160/3}" cy="${40+p[1]*160/3}" r="10"/><text x="${40+p[0]*160/3}" y="${25+p[1]*160/3}">${String.fromCharCode(65+i)}</text>`).join('')}</svg>${selectedLine()}<div class="play-choices">${g.options.map((x,i)=>choice(esc(x),i,g.selected.includes(i))).join('')}</div><div class="play-actions">${check()}${clear()}</div>${g.distance!==undefined?`<p>Your route: ${g.distance} grid units</p>`:''}`;
case 'conveyor':return `<div class="play-conveyor-target">${art(['carrot','tomato','potato'][g.targets[g.round]])}<strong>Requested bin: ${g.targets[g.round]+1}</strong></div><div class="play-choices">${g.options.map((x,i)=>choice(`${x}<small>Currently leads to bin ${g.routes[g.round][i]+1}</small>`,i)).join('')}</div><p>${g.round} of 4 dispatches</p>`;
default:return '<p>This game could not start. Please try a fresh puzzle.</p>';
}}
function creation(v){return v.kind==='mascot'?mascot(v.values):board(v.cells,3,(x,i)=>`<span class="play-cell">${x<0?'':art(foods[x],false)}</span>`);}
function review(){if(['number','crossword','peek'].includes(g.kind))return `<dl class="play-answer-review">${g.inputs.map(x=>`<div><dt>${esc(x.label)}</dt><dd>${esc(x.value)}</dd></div>`).join('')}</dl>`;if(g.kind==='balance')return `<p>${g.counts.map((x,i)=>`${x} × ${g.weights[i]} g = ${x*g.weights[i]} g`).join(' · ')}</p>`;if(g.kind==='pairs')return `<ul>${g.left.map((x,i)=>`<li>${esc(x)} → ${esc(g.options[g.values[i]].text)}</li>`).join('')}</ul>`;if(['choice','select','order'].includes(g.kind))return `<p><strong>Your answer</strong><br>${g.selected.map(i=>esc(g.options[i])).join(g.kind==='order'?' → ':' · ')}</p>`;if(g.kind==='numeric-grid')return `<p>${g.rows.map((x,i)=>`${g.cells.slice(i*3,i*3+3).join(' + ')} = ${x} g`).join('<br>')}</p>`;return '';}
function render(){const focus=document.activeElement?.dataset.playFocus;host.innerHTML=g.blocked?`<p>${esc(g.blocked)}</p>`:g.done?`<div class="play-complete">${art(meta.character,false)}<h2>Nicely done.</h2>${g.kind==='art'||g.kind==='mascot'?creation(g):''}<p>${esc(meta.explanation)}</p>${review()}${g.meal?`<p><strong>${esc(g.meal.chain)} · ${esc(g.meal.name)}</strong><br>${esc(g.meal.portion)} · U.S. menu<br>${g.meal.cal} kcal · ${g.meal.p} g protein</p><a href="${esc(g.meal.source)}" target="_blank" rel="noopener">Official nutrition source</a>`:''}<p class="play-hint">${g.kind==='art'||g.kind==='mascot'?'Your creation is saved on this device.':'Finished in '+g.turns+' actions. There is no time penalty.'}</p><button type="button" class="btn btn-primary" data-play-new>Another puzzle</button><a class="text-action" href="play.html">Back to the market</a></div>`:`<p class="play-objective">${esc(g.prompt)}</p>${content()}`;
host.hidden=g.paused;document.querySelector('[data-play-paused]').hidden=!g.paused;
live.textContent=g.error||g.feedback||'';live.classList.toggle('is-error',Boolean(g.error));
if(focus){const el=host.querySelector(`[data-play-focus="${CSS.escape(focus)}"]`);el?.focus({preventScroll:true});}
document.querySelector('[data-play-seed]').textContent=String(seed);
}
function doAction(a){if(a.type==='cross'){cross=!cross;render();return;}if(a.type==='cell'&&cross&&g.kind==='grid'){g.cells[a.index]=g.cells[a.index]===2?0:2;render();return;}const was=g.done;g.justCaught=null;if(a.type==='advance'&&g.kind==='catch'&&g.lane===g.targets[g.round])g.justCaught={lane:g.lane,food:g.options[g.round%5]};R.act(g,a);if(g.done&&!was){try{let p=JSON.parse(localStorage.getItem('getmacros-play-progress-v1')||'{}');p[meta.id]={completed:(p[meta.id]?.completed||0)+1,lastSeed:seed};localStorage.setItem('getmacros-play-progress-v1',JSON.stringify(p));if(g.kind==='art'||g.kind==='mascot')localStorage.setItem('getmacros-play-art-'+meta.id,JSON.stringify({kind:g.kind,values:g.values,cells:g.cells}));}catch{}live.textContent='Puzzle complete.'; }render();}
host.addEventListener('click',e=>{const b=e.target.closest('[data-play-action]');if(b)doAction(JSON.parse(b.dataset.playAction));if(e.target.closest('[data-play-new]'))reset(true);});
host.addEventListener('input',e=>{if(e.target.matches('[data-play-input]'))R.act(g,{type:'input',index:Number(e.target.dataset.playInput),value:e.target.value});});
host.addEventListener('change',e=>{if(e.target.matches('[data-play-pair]'))doAction({type:'pair',row:Number(e.target.dataset.playPair),index:e.target.value===''?null:Number(e.target.value)});if(e.target.matches('[data-play-custom]'))doAction({type:'custom',key:e.target.dataset.playCustom,value:e.target.value});});
host.addEventListener('keydown',e=>{if(g.kind==='maze'&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const offsets={ArrowUp:-g.size,ArrowDown:g.size,ArrowLeft:-1,ArrowRight:1};doAction({type:'move',index:g.pos+offsets[e.key]});}if(['catch','bounce'].includes(g.kind)&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();doAction({type:'lane',index:Math.max(0,Math.min(4,g.lane+(e.key==='ArrowLeft'?-1:1)))});}});
function reset(next){if(next)seed++;g=R.create(meta.id,seed,records);cross=false;const u=new URL(location.href);u.searchParams.set('seed',seed);history.replaceState(null,'',u);document.querySelector('[data-play-pause]').textContent='Pause';render();host.querySelector('button,input,select')?.focus({preventScroll:true});}
document.querySelector('[data-play-restart]').addEventListener('click',()=>reset(false));document.querySelector('[data-play-new]').addEventListener('click',()=>reset(true));
document.querySelector('[data-play-pause]').addEventListener('click',e=>{g.paused=!g.paused;e.target.textContent=g.paused?'Resume':'Pause';render();});document.querySelector('[data-play-resume]').addEventListener('click',()=>{g.paused=false;document.querySelector('[data-play-pause]').textContent='Pause';render();host.querySelector('button,input,select')?.focus();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&!g.done){g.paused=true;document.querySelector('[data-play-pause]').textContent='Resume';render();}});
window.GetMacrosPlay={getState:()=>R.clone(g)};render();
if(['art','mascot'].includes(g.kind)){try{const saved=JSON.parse(localStorage.getItem('getmacros-play-art-'+meta.id)||'null');if(saved){const previous=document.createElement('details');previous.className='play-creation-shelf';previous.innerHTML='<summary>Your saved creation</summary>'+creation(saved);host.after(previous);}}catch{}}

})();
