const fs=require('node:fs'),assert=require('node:assert/strict');
const {chromium,webkit}=require('C:/Users/slowf/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {localAssets}=require('../browser-fixture.cjs');
const out='docs/international-release-2026-10-09/journeys';fs.mkdirSync(out,{recursive:true});
const live=process.argv.includes('--live'),origin=live?'https://getmacros.net':'https://127.0.0.1:4187',report={production:live,time:new Date().toISOString(),checks:[],failures:[],clipboard:'Mocked clipboard writes; link content and navigation verified.'};
if(live)fs.mkdirSync(out+'/live',{recursive:true});
const ca=JSON.parse(fs.readFileSync('js/canada-meals.json')).records;
async function run(p,engine,theme,width){const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>window.__copied=text}}));
 const visit=async route=>{await p.goto(origin+route);await p.evaluate(()=>document.fonts.ready);if(await p.locator('#meal-quiz').count())await p.locator('#meal-quiz[data-ready=true]').waitFor();};
 const shot=async name=>p.screenshot({path:out+(live?'/live':'')+'/'+name+'-'+engine+'-'+theme+'-'+width+'.png',fullPage:true});
 const country=async value=>{await p.locator('.country-picker summary').click();await p.locator('[data-country-select]').selectOption(value);const target=await p.evaluate(v=>GetMacrosMarket.switchURL(v).href,value);await Promise.all([p.waitForURL(target),p.locator('[data-country-form] button').click()]);await p.locator('#meal-quiz[data-ready=true]').waitFor();};
 await visit('/restaurant-meal-finder.html?chain=Chipotle&maxCal=700&minProtein=20&size=small&diet=plant');await country('CA');assert(new URL(p.url()).pathname==='/ca/en/find-a-meal/');const q=new URL(p.url()).searchParams;assert.equal(q.get('maxCal'),'700');assert.equal(q.get('minProtein'),'20');for(const k of ['chain','size','diet'])assert.equal(q.has(k),false);assert.match(await p.locator('.market-notice').innerText(),/cleared/);assert.equal(await p.locator('[data-country-name]').innerText(),'Canada');assert(await p.evaluate(()=>GM_MEALS.every(m=>m.country==='CA')));
 await p.goBack();await p.locator('#meal-quiz[data-ready=true]').waitFor();assert.equal(await p.locator('[data-country-name]').innerText(),'United States');assert.equal(new URL(p.url()).searchParams.get('chain'),'Chipotle');await visit('/ca/en/find-a-meal/');assert.equal(await p.locator('[data-country-name]').innerText(),'Canada');await country('US');assert.equal(new URL(p.url()).pathname,'/restaurant-meal-finder.html');await visit('/ca/en/find-a-meal/');
 // Header controls must be separate hit targets, and open panels stay on-screen.
 const icons=await p.locator('.appearance-picker>summary,.nav-search>summary,.nav-toggle').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().width).map(e=>{const r=e.getBoundingClientRect();return {x:r.x,right:r.right,y:r.y,bottom:r.bottom}}));if(width<600)for(let i=0;i<icons.length;i++)for(let j=i+1;j<icons.length;j++)assert(icons[i].right<=icons[j].x+1||icons[j].right<=icons[i].x+1,'Header hit targets overlap');
 for(const picker of ['country-picker','language-picker','nav-search']){const summary=p.locator('.'+picker+'>summary');if(!await summary.isVisible())continue;await summary.focus();await p.keyboard.press('Enter');const panel=p.locator('.'+picker+'[open] > div,.'+picker+'[open] > form');const bounds=await panel.first().boundingBox();assert(bounds&&bounds.x>=-1&&bounds.x+bounds.width<=width+1,picker+' clipped');await shot('open-'+picker);await p.keyboard.press('Escape');assert.equal(await p.locator('.'+picker).getAttribute('open'),null);}
 if(width<901){await p.locator('.nav-toggle').click();assert.equal(await p.locator('.full-nav-links').isVisible(),true);await shot('mobile-menu');await p.keyboard.press('Escape');assert.equal(await p.locator('.nav-toggle').getAttribute('aria-expanded'),'false');}
 // A direct Canadian URL must carry its country into global tools and saving.
 await p.evaluate(()=>localStorage.setItem('gm-market-v1','US'));await visit('/ca/en/find-a-meal/');const savedNav=p.locator('.full-nav-links a').filter({hasText:/^Saved$/});assert.equal(new URL(await savedNav.getAttribute('href'),origin).searchParams.get('market'),'CA');
 // A deliberate U.S. guide wins a stored Canadian preference; switching clears it visibly.
 await p.evaluate(()=>localStorage.setItem('gm-market-v1','CA'));await visit('/starbucks-healthy-food-meals-macros.html');assert.equal(await p.locator('[data-country-name]').innerText(),'United States');await p.locator('.country-picker summary').click();await p.locator('[data-country-select]').selectOption('CA');await Promise.all([p.waitForURL(u=>u.pathname==='/ca/en/'),p.locator('[data-country-form] button').click()]);assert.match(await p.locator('.market-notice').innerText(),/selection was cleared/);await visit('/ca/en/find-a-meal/');
 // Country-specific quiz starts empty and exposes only supported choices.
 await visit('/ca/en/find-a-meal/');await p.locator('[data-open-guide]').click();assert.equal(await p.locator('.guided-dialog input:checked').count(),0);await p.locator('[data-guide-step="0"] input[value=breakfast]').check();await p.locator('[data-guide-next]').click();assert.match(await p.locator('[data-guide-step="1"]').innerText(),/Canadian menus/);await p.locator('[data-guide-step="1"] input[value="Tim Hortons"]').check();await p.locator('[data-guide-next]').click();await p.locator('[data-guide-step="2"] input[value=protein]').check();await p.locator('[data-guide-next]').click();assert.equal(await p.locator('.guided-dialog input[name=diet]').count(),0);assert(await p.locator('.guided-dialog use').evaluateAll(es=>es.every(e=>e.getAttribute('href').startsWith('/images/'))));await p.locator('.guided-dialog input[name=maxCal]').fill('900');await p.locator('.guided-dialog input[name=minProtein]').fill('10');await shot('canadian-quiz');await p.locator('[data-guide-next]').click();assert.equal(new URL(p.url()).searchParams.get('chain'),'Tim Hortons');assert.equal(new URL(p.url()).searchParams.get('meal'),'breakfast');assert((await p.locator('.meal-row').count())>0);
 // Exact results, comparison, share, download, local save and source metadata.
 await visit('/ca/en/find-a-meal/?chain=Tim%20Hortons&minProtein=10');assert((await p.locator('.meal-row').count())>0);assert(await p.locator('.meal-row').evaluateAll(es=>es.every(e=>/Canadian menu|Canada/.test(e.textContent)&&!e.textContent.includes('U.S.'))));await p.locator('[data-share]').click();const shared=await p.evaluate(()=>window.__copied);assert.equal(new URL(shared).pathname,'/ca/en/find-a-meal/');await visit(new URL(shared).pathname+new URL(shared).search);
 await p.locator('[data-compare]').nth(0).check();await p.locator('[data-compare]').nth(1).check();await p.locator('[data-open-compare]').click();assert.match(await p.locator('.compare-dialog').innerText(),/Canada/);await p.locator('[data-share-comparison]').click();const pair=await p.evaluate(()=>window.__copied);assert.equal(new URL(pair).searchParams.getAll('compare').length,2);await p.keyboard.press('Escape');await visit(new URL(pair).pathname+new URL(pair).search);assert.equal(await p.locator('.compare-dialog').evaluate(d=>d.open),true);await p.keyboard.press('Escape');
 await p.locator('.meal-detail summary').first().click();const dl=p.waitForEvent('download');await p.locator('[data-order-card]').first().click();const downloaded=await dl;const target=out+(live?'/live':'')+'/order-card-'+engine+'-'+theme+'-'+width+'.svg';await downloaded.saveAs(target);const svg=fs.readFileSync(target,'utf8');assert(svg.includes('Canada')&&svg.includes('2026-07'));await p.locator('[data-save]').first().click();const saved=await p.evaluate(()=>Object.values(GetMacrosNotebook.read().entries)[0]);assert.equal(saved.country,'CA');assert(saved.source&&saved.serving&&saved.checked);
 await visit('/food-shelf.html?market=CA#order-notebook');await p.locator('[data-note]').first().fill('Private Canadian lunch');await p.locator('[data-note-save]').first().click();await p.reload();assert.equal(await p.locator('[data-note]').first().inputValue(),'Private Canadian lunch');assert.equal(new URL(await p.locator('#food-shelf a').first().getAttribute('href'),origin).pathname,'/ca/en/find-a-meal/');await p.locator('[data-notebook-load]').click();await p.locator('[data-notebook-refresh]').first().waitFor();await p.locator('[data-notebook-refresh]').first().click();assert.equal(await p.locator('[data-note]').first().inputValue(),'Private Canadian lunch');await p.locator('[data-notebook-remove]').first().click();assert.equal(await p.locator('[data-note]').count(),0);
 await visit('/restaurant-meal-finder.html?chain=McDonald%E2%80%99s&maxCal=500&minProtein=12');assert.equal(await p.locator('.meal-row').count(),0);await p.locator('[data-allow-incomplete]').click();assert.equal(await p.locator('.meal-row').count(),4);assert(await p.locator('.macro-missing').evaluateAll(es=>es.every(e=>e.textContent.includes('fat'))));assert.equal(new URL(p.url()).searchParams.get('maxCal'),'500');assert.equal(new URL(p.url()).searchParams.get('minProtein'),'12');
 await visit('/ca/en/find-a-meal/?maxCal=150&minProtein=200');assert.equal(await p.locator('.meal-row').count(),0);assert.match(await p.locator('.finder-empty').innerText(),/unchanged/);assert.equal(new URL(p.url()).searchParams.get('minProtein'),'200');
 await visit('/ca/en/tools/complete-order/');await p.locator('[data-order-load]').click();await p.locator('[data-order-workspace] select').waitFor();const form=p.locator('#order-builder form');const values=await form.locator('option').evaluateAll(es=>es.slice(1).map(e=>e.value));assert(values.every(v=>v.startsWith('CA|')));assert.equal(values.length,74);for(const slug of ['teen-burger','russet-thick-cut-fries-regular','aw-root-beer-small']){const r=ca.find(m=>m.officialDataUrl?.endsWith('/'+slug+'/default'));await form.locator('[name=item]').selectOption(r.id);await form.locator('[type=submit]').click();}assert.match(await p.locator('.order-totals').innerText(),/1,000 kcal/);assert.match(await p.locator('.order-totals').innerText(),/32 g/);assert.match(await p.locator('.order-totals').innerText(),/1,305 mg/);await shot('canadian-complete-order');await p.locator('[data-order-save]').click();assert.equal(await p.evaluate(()=>Object.values(GetMacrosNotebook.read().entries)[0].country),'CA');await p.locator('[data-order-clear]').click();assert.equal(await p.locator('.order-line').count(),0);
 await visit('/ca/en/tools/drink-comparison/');await p.locator('[data-order-load]').click();await p.locator('[name=a]').waitFor();for(const [name,key] of [['Latte - Medium','a'],['Protein Latte - Medium','b']])await p.locator('[name='+key+']').selectOption(ca.find(m=>m.name===name).id);await p.locator('[data-order-workspace] [type=submit]').click();assert.match(await p.locator('[data-order-output]').innerText(),/140 kcal/);assert.match(await p.locator('[data-order-output]').innerText(),/170 kcal/);assert.match(await p.locator('[data-order-output]').innerText(),/Canada/);
 await visit('/protein-value-calculator.html?market=CA');assert.equal(await p.locator('#receipt-currency').inputValue(),'CAD');await p.locator('#ap').fill('12');await p.locator('#aq').fill('2');await p.locator('#as').fill('4');await p.locator('#ag').fill('20');assert.match(await p.locator('#ra').innerText(),/0\.075/);
 await visit('/search.html?market=CA&q=latte');await p.locator('.search-meal-hit').first().waitFor();assert(await p.locator('.search-meal-hit').evaluateAll(es=>es.every(e=>e.href.includes('/ca/en/'))));assert.equal(await p.locator('.search-hit[data-market=US]:visible').count(),0);
 await p.evaluate(()=>document.documentElement.style.fontSize='200%');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'Search text enlargement overflow');
 await visit('/calculators.html?market=CA');await p.locator('#age').fill('10');await p.locator('[data-calc-next]').click();assert.equal(await p.locator('#age').isVisible(),true);await p.locator('#age').fill('30');await p.locator('[data-calc-next]').click();assert.equal(await p.locator('#activity').isVisible(),true);await p.locator('[data-calc-next]').click();await p.locator('#macro-form [type=submit]').click();assert.match(await p.locator('#macro-results').innerText(),/2,668/);await p.locator('[data-calc-switch]').click();await p.locator('[data-weight-unit=kg]').first().click();await p.locator('[data-height-unit=cm]').click();await p.locator('#macro-form [type=submit]').click();assert(Math.abs(Number((await p.locator('#macro-results .num').innerText()).replace(/,/g,''))-2668)<=1);assert.equal(new URL(p.url()).search,'?market=CA');assert.match(await p.locator('[data-current-market-label]').innerText(),/Canadian selection/);assert.equal(new URL(await p.locator('.footer-primary [data-market-route=finder]').getAttribute('href'),origin).pathname,'/ca/en/find-a-meal/');await shot('calculator');
 await visit('/index.html');const character=p.locator('.food-ensemble [data-food-character] button').first();await character.focus();assert.equal(await character.getAttribute('aria-expanded'),'true');assert.equal(await character.locator('..').evaluate(e=>e.getAnimations({subtree:true}).length),0);await p.keyboard.press('Escape');assert.equal(await character.getAttribute('aria-expanded'),'false');assert.deepEqual(errors,[]);report.checks.push({engine,theme,width,result:'pass',scope:'country navigation/history; Canadian quiz and supported choices; calculator validation/units; all header panels; mobile nav; exact results/filter/share/compare/save/download; notes/refresh/removal; empty results; Canadian builder/drinks; local currency; market search; reduced motion; 200% text'});
}
(async()=>{for(const engine of live?[chromium]:[chromium,webkit]){const b=await engine.launch(engine===chromium?{channel:'msedge'}:{});try{for(const theme of ['light','dark'])for(const width of [390,1440]){process.env.GM_TEST_THEME=theme;const p=await b.newPage({viewport:{width,height:950},reducedMotion:'reduce',acceptDownloads:true});p.setDefaultTimeout(9000);if(!live)await localAssets(p);else await p.addInitScript(t=>localStorage.setItem('gm-theme',t),theme);try{await run(p,engine.name(),theme,width);console.log('PASS',engine.name(),theme,width);}catch(e){report.failures.push({engine:engine.name(),theme,width,error:e.stack});console.error('FAIL',engine.name(),theme,width,e.message);await p.screenshot({path:out+(live?'/live':'')+'/failure-'+engine.name()+'-'+theme+'-'+width+'.png',fullPage:true});}finally{await p.close();}}}finally{await b.close();}}fs.writeFileSync(out+(live?'/live':'')+'/checks.json',JSON.stringify(report,null,2));assert.equal(report.failures.length,0);})().catch(e=>{console.error(e);process.exitCode=1});
