"""Evidence-led handoff, inventories and exact limitations for this release."""
from pathlib import Path
from html import escape
from collections import Counter
import csv,json,tarfile,re,hashlib
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'docs/international-release-2026-10-09'
def write(name,value):
 (OUT/name).write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
routes=json.loads((ROOT/'tools/international/routes.json').read_text(encoding='utf-8'))
registry=json.loads((ROOT/'js/order-registry.json').read_text(encoding='utf-8'))['records'];ca=[r for r in registry if r['country']=='CA']
gaps=[{'country':r['country'],'restaurant':r['chain'],'order':r['name'],'id':r.get('id',r['chain']+'||'+r['name']),'missing_macros':[k for k in ['cal','p','c','fat'] if r.get(k) is None],'missing_other_nutrients':[k for k in ['f','na','sugar'] if r.get(k) is None],'source':r['source'],'source_checked':r.get('checked'),'verification_status':r['verificationStatus']} for r in registry if any(r.get(k) is None for k in ['cal','p','c','fat','f','na'])]
write('data-gaps.json',gaps)
with (OUT/'release-links.csv').open('w',encoding='utf-8',newline='') as f:
 w=csv.DictWriter(f,fieldnames=['url','type','market','purpose','live_status']);w.writeheader()
 for r in routes:w.writerow({'url':'https://getmacros.net'+r['route'],'type':r['template'],'market':'CA','purpose':r['description'],'live_status':'pending verification'})
 for r in ['index.html','calculators.html','sources.html','fast-food-nutrition-data-report.html','breakfast-dataset-not-opening-hours.html','exact-fiber-coverage-denominator.html','menu-pdf-filename-not-edition-date.html','restaurant-search-result-count-scope.html','same-restaurant-name-different-market-data.html','menu-average-chain-weighting.html','published-vs-calculated-restaurant-rows.html','burger-variants-not-nine-base-burgers.html']:
  w.writerow({'url':'https://getmacros.net/'+('' if r=='index.html' else r),'type':'improved existing','market':'global or US','purpose':'Copy, task clarity or country context','live_status':'pending verification'})
guidance=[{'url':'https://developers.google.com/search/docs/specialty/international/managing-multi-regional-sites','implementation':'Separate crawlable Canadian URLs, explicit country choice, no IP redirects, U.S. URLs retained.'},{'url':'https://developers.google.com/search/docs/specialty/international/localized-versions','implementation':'Self canonicals; reciprocal en-CA/en-US only for equivalent homepage, directory and finder. No French or unrelated-guide alternates.'}]
research=[
 {'query':'Tim Hortons Canada protein latte nutrition breakfast calories','locale':'Canada intended; search engine locale not forced','sources':['https://www.timhortons.ca/nutrition-and-allergens','https://timhortons-menus.ca/wp-content/uploads/2025/11/Tim-Hortons-Nutrition-Guide.pdf','https://menupricetoday.com/ca/brands/tim-hortons/menu/latte-proteine'],'observation':'Results mix official navigation, a third-party older PDF and product/price pages. Third-party values/prices were not imported. Exact current linked PDF edition and named size improve the answer.','implemented':['/ca/en/tools/drink-comparison/','/ca/en/restaurants/tim-hortons/','/ca/en/collections/breakfast/']},
 {'query':'A&W Canada Teen Burger meal calories fries root beer','locale':'Canada intended; search engine locale not forced','sources':['https://web.aw.ca/en/our-menu','https://awmenu.ca/calculator','https://awmenu.ca/teen-burger','https://www.dwlz.com/Restaurants/awrootbeer.html'],'observation':'Results include complete-order calculators, item pages and old calorie tables with differing values. We used current official serving drawers, explicit drink/fries sizes and a transparent three-component sum. No local prices or competitor numbers were reused.','implemented':['/ca/en/tools/complete-order/','/ca/en/restaurants/a-w-canada/']},
 {'query':"Harvey's Canada grilled chicken sandwich nutrition sodium",'locale':'Canada intended; search engine locale not forced','sources':['https://www.harveys.ca/en/nutrition.html','https://www.harveys.ca/en/menu/pickup/i106059/grilled-chicken-sandwich.html?s=1924','https://rippedrestaurants.com/ca/chains/harveys/grilled-chicken'],'observation':'Results can describe the chicken component instead of the complete sandwich. Our guide identifies the sandwich serving, includes sodium and keeps separately selected garnishes distinct.','implemented':['/ca/en/restaurants/harvey-s/','/ca/en/collections/protein-meals/']}
]
write('seo-research.json',{'date':'2026-10-09','first_party_access':'No authorized Search Console/analytics export or session was available. Visitor uplift and demand were not measured.','search_volume':None,'keyword_difficulty':None,'traffic_forecast':None,'guidance':guidance,'observed_search_results':research,'scope':'Qualitative research, not measured demand, ranking or competitor traffic. Official sources establish nutrition; search results establish observed page types only.'})
future=[{'market':'CA','restaurant':'McDonald’s Canada','sources':['https://www.mcdonalds.com/ca/en-ca/full-menu.html','https://www.mcdonalds.com/ca/en-ca/product/egg-mcmuffin.html'],'status':'Held: browser/direct access denied and available page extraction omitted full nutrition numbers. No U.S. substitutions.'},{'market':'GB','restaurant':'Greggs','sources':['https://www.greggs.com/nutrition','https://www.greggs.com/menu/product/sausage-roll-1000446/'],'status':'Research queue; no UK pages/records published.'},{'market':'GB','restaurant':'Nando’s','sources':['https://www.nandos.co.uk/food/menu/','https://www.nandos.co.uk/food/allergens/'],'status':'Research queue; serving/build verification required.'},{'market':'AU','restaurant':'Guzman y Gomez','sources':['https://www.guzmanygomez.com.au/wp-content/uploads/2026/02/260128_NUTRITION_ALLERGEN_GUIDE_420X297MM.pdf'],'status':'Official Australian guide found; no Australian records or pages published.'},{'market':'JP','restaurant':'McDonald’s Japan','sources':['https://www.mcdonalds.co.jp/quality/allergy_Nutrition/nutrient/','https://www.mcdonalds.co.jp/products/nutrition_balance_check/'],'status':'Official Japanese sources found. Salt-equivalent grams require explicitly proven conversions; no Japanese records published.'}]
write('market-research-queue.json',future)
with (OUT/'query-to-page.csv').open('w',encoding='utf-8',newline='') as f:
 w=csv.DictWriter(f,fieldnames=['route','country','intent','unique_value','next_action','maintenance']);w.writeheader()
 for r in routes:w.writerow({'route':r['route'],'country':'CA','intent':r['title'],'unique_value':r['description'],'next_action':'Canadian finder, exact component builder or official source','maintenance':'Recheck current official recipe/portion and source edition when the linked source changes; do not merely refresh review dates.'})
copy=json.loads((OUT/'copy-audit.json').read_text(encoding='utf-8'))
for r in copy['repeated_paragraphs']:
 r['review_decision']='Retain factual portion/source or safety disclosure where it applies; not marketing copy. Repetition inside independently usable source details is deliberate.'
for r in copy['internal_language_candidates']:
 r['review_decision']='Read in context: retain applicable source/portion limits, mathematical definitions or scientific terminology. Technical wording on the coverage report is deliberate; no automatic synonym replacement.'
write('copy-audit.json',copy)
write('copy-review-decisions.json',{'method':'All active routes scanned; eight help guides rewritten individually, all 25 U.S. restaurant lead paragraphs read in context, repeated introductory comparisons removed when repeated below. Necessary shared safety and source disclosures retained. Not every article body was substantively rewritten.','implemented':['Removed repeated homepage lunch messaging.','Removed layered macro-calculator headings and introduced a direct task label.','Rewrote eight guides around breakfast availability, missing fiber, PDF currency, result counts, country choice, exact burger variants, calculated orders and menu averages; retained useful tables, citations and URLs.','Removed internal content-addition/release notes from 20 existing comparison sections; source dates remain in their source lists.','Replaced the stale initial-dataset paragraph on Sources with current U.S./Canadian coverage links.','Removed duplicated restaurant comparison paragraphs from the masthead when the detailed comparison already explains them.','Changed the common restaurant input heading to Choose your limits.'],'consolidations':'No articles deleted or redirected. Useful worked examples and established links were retained; no authorized search-performance evidence supported bulk deletion.'})
tests={}
for label,file in [('route_rendering','routes/checks.json'),('representative_rendering','browser/checks.json'),('journeys','journeys/checks.json')]:
 p=OUT/file
 if p.exists():
  j=json.loads(p.read_text(encoding='utf-8'));tests[label]={'checks':len(j if isinstance(j,list) else j['checks']),'failures':sum(bool(r.get('overflow') or r.get('errors')) for r in j) if isinstance(j,list) else len(j['failures']),'evidence':file}
write('release-status.json',{'date':'2026-10-09','deployment':'pending','markets_published_locally':['US','CA'],'new_canadian_records':len(ca),'canadian_restaurants':dict(Counter(r['chain'] for r in ca)),'new_canadian_routes':len(routes),'existing_macro_gaps_resolved':2,'unresolved_US_macro_records':sum(r['country']=='US' and any(r.get(k) is None for k in ['cal','p','c','fat']) for r in registry),'withheld_conflicting_records':['A&W Canada regular Mango Passionfruit Shake: 94 g sugars within 91 g carbohydrates.'],'blocked_markets':['McDonald’s Canada full values unavailable','French editorial review unavailable','UK/Australia/Japan are researched, not launched'],'source_date_limit':'Tim Hortons current official link points to July 2026 Canadian PDF; current retrieval does not make the recipe edition October 2026.','analytics':'Unavailable; no traffic, indexing or revenue claim. Sitemap submission and indexing are not verified.','verification':tests,'expert_review':'No dietitian or medical review claimed. No new disease-treatment content.','licensing':'Original existing food characters retained. No new third-party imagery or PDFs redistributed.'})
inventory=json.loads((OUT/'inventory.json').read_text(encoding='utf-8'))
manual={
 '/':'browser/-index-html-dark-390.png',
 '/index.html':'browser/-index-html-dark-390.png',
 '/ca/en/':'browser/-ca-en--light-390.png; browser/-ca-en--dark-1440.png',
 '/ca/en/find-a-meal/':'browser/-ca-en-find-a-meal--light-390.png; journeys/open-country-picker-chromium-dark-390.png; journeys/canadian-quiz-webkit-light-390.png',
 '/calculators.html':'journeys/calculator-chromium-light-390.png',
 '/ca/en/restaurants/tim-hortons/':'browser/-ca-en-restaurants-tim-hortons--dark-1440.png',
 '/ca/en/tools/complete-order/':'journeys/canadian-complete-order-chromium-dark-390.png',
 '/same-restaurant-name-different-market-data.html':'additional/same-restaurant-name-different-market-data-dark-1440.png',
 '/contact.html':'additional/contact-light-390.png',
 '/nutrition-label-comparison-tool.html':'additional/nutrition-label-comparison-tool-dark-1440.png',
 '/privacy.html':'additional/privacy-dark-390.png',
 '/sources.html':'additional/sources-light-1440.png',
 '/recipe-macro-scaler.html':'additional/recipe-macro-scaler-light-390.png',
}
rewritten={('/'+name+'.html') for name in ['breakfast-dataset-not-opening-hours','exact-fiber-coverage-denominator','menu-pdf-filename-not-edition-date','restaurant-search-result-count-scope','same-restaurant-name-different-market-data','menu-average-chain-weighting','published-vs-calculated-restaurant-rows','burger-variants-not-nine-base-burgers']}
journey_routes={'/','/index.html','/restaurant-meal-finder.html','/ca/en/find-a-meal/','/ca/en/','/starbucks-healthy-food-meals-macros.html','/ca/en/restaurants/tim-hortons/','/calculators.html','/search.html','/food-shelf.html','/ca/en/tools/complete-order/','/ca/en/tools/drink-comparison/','/protein-value-calculator.html'}
all_pages=inventory['pages']+[dict(next(r for r in inventory['pages'] if r['route']=='/'),route='/index.html')]
with (OUT/'coverage.csv').open('w',encoding='utf-8',newline='') as f:
 w=csv.DictWriter(f,fieldnames=['route','template','market','visual_status','copy_status','SEO_status','responsive_status','interaction_status','verification_performed','remaining_issues']);w.writeheader()
 for p in all_pages:
  route=p['route'];family=p['family'];remaining=[]
  if family in ['finder','restaurant','reference-index'] and p['market_scope']!='CA':remaining.append('40 U.S. finder records still have missing core macros; see data-gaps.json. Not all U.S. data reverified this release.')
  if route.startswith('/ca/'):remaining.append('Tracked selection, not a full-menu or local-availability audit. McDonald’s Canada withheld; English only.')
  copy_status=('New individually reviewed Canadian copy and official source/portion trail' if route.startswith('/ca/') else 'Individually improved; examples, source links and URL retained' if route in rewritten else 'Lead paragraphs read; duplicate comparison introductions removed where repeated below' if family=='restaurant' else 'Task copy or methodology corrected' if route in ['/','/index.html','/calculators.html','/sources.html','/fast-food-nutrition-data-report.html'] else 'Automated repetition/terminology scan; necessary disclosures retained. Body not substantively rewritten.')
  w.writerow({'route':route,'template':family,'market':p['market_scope'],'visual_status':('Manual screenshot review of stated files: '+manual[route] if route in manual else 'Automated rendering only; not manually visually inspected'),'copy_status':copy_status,'SEO_status':'Canonical/indexability, title/description, links, heading and reciprocal-equivalent hreflang checks passed','responsive_status':'Edge render: 320, 390, 768, 1280, 1440 px; both themes; no detected horizontal page overflow','interaction_status':('Journey exercised in Edge/WebKit, both themes, 390/1440; see journeys/checks.json' if route in journey_routes else 'Game rules tested; representative keyboard/touch game journeys tested, not every game manually played' if family=='game' else 'Runtime, assets, IDs and form-label render checks; links/anchors checked, not every action manually exercised'),'verification_performed':'routes/checks.json; inventory.json; test-results.json; '+manual.get(route,'automated render only'),'remaining_issues':'; '.join(remaining) or 'No detected route/render failure. Manual and assistive-technology review is not exhaustive.'})
write('completion-checklist.json',{
 'baseline':{'status':'done','evidence':['baseline.json','baseline-active-files.tar.gz','baseline-build.log','baseline/']},
 'copy':{'status':'done for stated targeted scope','evidence':['copy-audit.json','copy-review-decisions.json'],'limits':'No bulk article deletion or claim that all 182 article bodies were rewritten.'},
 'country_data':{'status':'done for 3 Canadian chains / 74 verified components','evidence':['../../tools/international/records.json','data-gaps.json'],'held':'McDonald’s Canada; A&W conflicting regular mango shake; French and future markets.'},
 'country_interface':{'status':'done','evidence':['journeys/checks.json'],'behavior':'Country and language separate; explicit URLs win; supported filters persist; incompatible selections explained; no IP redirect.'},
 'tools':{'status':'done','evidence':['test-results.json','journeys/checks.json'],'features':'Country-safe comparator, exact component builder, drink comparison, saved notebook, public order card, explicit local-price currency; calculator unit/validation and quiz submit fixes.'},
 'seo':{'status':'done for implementation; indexing unavailable','evidence':['seo-research.json','query-to-page.csv','inventory.json'],'limits':'No authorized Search Console or analytics access; no verified submission/indexing/traffic.'},
 'verification':{'status':'done locally','evidence':['routes/checks.json','browser/checks.json','additional/checks.json','journeys/checks.json','publish-test-results.json','publish-build.log']},
 'publication':{'status':'pending actual live checks','workflow':'Existing normal atomic push to main and Pages branch; no DNS changes.'}
})
report='''<!doctype html><html lang="en"><meta charset="utf-8"><title>GetMacros international release — verification report</title><style>body{font:16px/1.6 system-ui,sans-serif;color:#173b27;background:#fafbf7;max-width:880px;margin:3rem auto;padding:0 1.25rem}h1{line-height:1.15}h2{margin-top:2.3rem}a{color:#267044}li{margin:.5rem 0}table{border-collapse:collapse;width:100%}td,th{text-align:left;border-bottom:1px solid #dce4d8;padding:.6rem}code{overflow-wrap:anywhere}</style><main><h1>Canada, clearer copy and trustworthy order tools</h1><p>Release dated October 9, 2026. The existing green identity, original food characters, public U.S. URLs and working formulas are preserved. Publication status is recorded separately in <a href="release-status.json">release-status.json</a> and <a href="release-links.csv">the exact link manifest</a>.</p>
<h2>Implemented</h2><ul><li>Separate country and language header controls; Canada and U.S. coverage only, English only. Explicit country URLs take precedence over remembered settings. Incompatible chain, dietary or comparison selections are cleared with an explanation.</li><li>Eleven crawlable Canadian pages: home, directory, finder, three restaurant guides, two collections, complete-order builder, drink comparator and source history.</li><li>74 verified Canadian items/components: A&amp;W Canada 31, Tim Hortons 24, Harvey’s 19. This is a tracked selection, not 74 complete orders or a full-menu audit.</li><li>Market/serving/source identity retained through finder, comparison, saving, private notes, export and public SVG order cards. Unknown nutrients stay unknown; cards exclude private notes and body inputs.</li><li>Complete macros now means known calories, protein, carbs and fat. Filtered nutrients must be known. Two existing U.S. calculated fat totals resolved; 40 U.S. records remain incomplete.</li><li>Repeated homepage messaging and restaurant introductions reduced; eight existing help guides improved individually; release/project notes removed from 20 comparison sections. Useful tables, citations and established URLs retained.</li><li>Calculator labels/units/results made more direct; quiz submit behavior fixed in WebKit; Canada omits unsupported dietary classifications. Privacy notebook disclosure now sits inside its reading column.</li></ul>
<h2>Sources and limits</h2><p>A&amp;W current Canadian source drawers were reviewed. Tim Hortons’ currently linked official Canadian PDF is the <strong>July 2026 edition</strong>, retrieved October 9; it was not relabeled as an October recipe. Harvey’s official table was reviewed through the available primary-source extraction after its dynamic browser table failed. Country provenance, units, original verification dates and calculated component sums are retained.</p><p>McDonald’s Canada is held because the available interface did not provide verifiable full values. One A&amp;W shake is withheld because its reported sugar exceeded carbohydrate. No French, UK, Australian or Japanese pages are launched. French needs reviewed content; future markets have a documented source queue. Existing U.S. data is not all reverified for this launch. No new stock imagery, third-party PDFs or medical credentials are claimed.</p>
<h2>SEO actually researched and applied</h2><p>Read current Google guidance on multi-regional sites and localized annotations; searched specific Tim Hortons, A&amp;W and Harvey’s questions and inspected observed official/third-party result types. Findings and URLs are in <a href="seo-research.json">the research log</a>; intent and maintenance are in <a href="query-to-page.csv">the route map</a>. Canadian pages have self canonicals, crawlable links and accurate visible content. Reciprocal en-CA/en-US annotations are used only for equivalent home, directory and finder pages; stale unrelated article/game alternates removed. Sitemap includes only published canonical pages with substantive-change dates.</p><p>No authorized Search Console or analytics data was available. Keyword volume, visitor uplift, sitemap submission, indexing and traffic are not measured or claimed.</p>
<h2>Actual verification</h2><ul><li>Maintained full build passed in the isolated publication candidate; <a href="publish-build.log">build log</a>. Fourteen existing/international test commands passed; <a href="publish-test-results.json">commands/results</a> and <a href="publish-tests.log">output</a>. Includes calculator formulas/units, unknowns, country isolation, source consistency, saving/export, 2,240 game rule cases, metadata/links and cache stamps.</li><li>All 303 public render routes (302 physical pages plus index alias) checked at 320, 390, 768, 1280 and 1440 px in both themes: 3,030 Edge checks with zero detected failures. This is automated rendering, <strong>not manual visual inspection of all pages</strong>. <a href="routes/checks.json">Route evidence</a>; <a href="coverage.csv">per-route coverage</a>.</li><li>Eight Edge/WebKit journey cohorts passed at 390/1440, both themes: country switching/history, quiz, filters/empty states, comparison/share/download, saved notes/deletion, builder/drinks, local currency, calculator valid/invalid/units, search, keyboard menus, reduced motion and enlarged text. <a href="journeys/checks.json">Journey results</a>.</li><li>Representative actual screenshots captured in <a href="browser/">browser/</a>, <a href="additional/">additional/</a> and <a href="journeys/">journeys/</a>. Specific manually viewed files are named in coverage.csv. The final privacy placement was reviewed after its fix.</li></ul><p>Browser source fixture blocked external requests. Clipboard writing was mocked, while shared state and downloaded card contents were checked. Screen-reader testing, exhaustive manual article review, field performance and real-user traffic are not claimed. No Lighthouse score is presented as field performance. Live verification is a separate post-publication record.</p>
<h2>Remaining work</h2><p>The exact <a href="data-gaps.json">nutrient gaps</a> and <a href="market-research-queue.json">market/source queue</a> remain visible. Resolve the unavailable Canadian sources and contradictory shake before adding them; obtain actual French editorial review before enabling French. Search Console access is needed to inspect indexing and acquisition, not to finish the shipped Canadian product.</p></main></html>'''
(OUT/'report.html').write_text(report,encoding='utf-8')
print('Release evidence, country research, copy decisions, query map and exact remaining data gaps recorded.')
