/* Actual local rendering across every published route; no production/field claim. */
const fs=require('node:fs'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/slowf/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {localAssets}=require('../browser-fixture.cjs');
const out='docs/international-release-2026-10-09/routes';fs.mkdirSync(out,{recursive:true});
const routes=['/',...fs.readdirSync('.').filter(f=>f.endsWith('.html')).map(f=>'/'+f),...JSON.parse(fs.readFileSync('tools/international/routes.json')).map(r=>r.route)];
const report={fixture:'Local interception, external requests blocked. All routes rendered in Edge, both themes, five widths. Not manual visual inspection.',time:new Date().toISOString(),checks:[],failures:[]};
const save=()=>fs.writeFileSync(out+'/checks.json',JSON.stringify(report,null,2));
(async()=>{const b=await chromium.launch({channel:'msedge'});try{for(const theme of ['light','dark']){process.env.GM_TEST_THEME=theme;const p=await b.newPage({viewport:{width:320,height:1000},reducedMotion:'reduce'});await localAssets(p);let errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&new URL(r.url()).hostname==='127.0.0.1')requests.push(r.url());});for(const [i,route] of routes.entries()){errors=[];requests=[];try{await p.goto('https://127.0.0.1:4187'+route);await p.evaluate(()=>document.fonts.ready);if(await p.locator('#meal-quiz').count())await p.locator('#meal-quiz[data-ready=true]').waitFor({timeout:7000});for(const width of [320,390,768,1280,1440]){await p.setViewportSize({width,height:1000});const row={route,theme,width,errors:[...errors],requests:[...requests],...await p.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return{overflow:document.documentElement.scrollWidth>innerWidth+1,h1:document.querySelectorAll('main h1').length,footer:document.querySelectorAll('.market-footer').length,theme:document.documentElement.dataset.theme,duplicateIds:ids.filter((id,i)=>ids.indexOf(id)!==i),unlabelled:[...document.querySelectorAll('input:not([type=hidden]),select,textarea')].filter(e=>!e.labels?.length&&!e.getAttribute('aria-label')&&!e.getAttribute('aria-labelledby')).map(e=>e.id||e.name),missingImages:[...document.images].filter(i=>i.complete&&!i.naturalWidth).map(i=>i.src)};})};report.checks.push(row);if(row.overflow||row.h1!==1||row.footer!==1||row.theme!==theme||row.errors.length||row.requests.length||row.duplicateIds.length||row.unlabelled.length||row.missingImages.length)report.failures.push(row);}}catch(e){report.failures.push({route,theme,error:e.stack});}if((i+1)%30===0){save();console.log(theme,i+1,'/',routes.length,'routes');}}await p.close();}}finally{await b.close();save();}console.log(report.checks.length,'render checks;',report.failures.length,'failures');assert.equal(report.failures.length,0);})().catch(e=>{console.error(e);save();process.exitCode=1});
