const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const E=require('../../js/meal-engine.js'),C=require('../../js/order-tools-core.js');
const ca=JSON.parse(fs.readFileSync('js/canada-meals.json')).records,registry=JSON.parse(fs.readFileSync('js/order-registry.json')).records;
assert.equal(ca.length,74);assert.equal(new Set(ca.map(E.key)).size,ca.length);
for(const r of registry){assert(['US','CA'].includes(r.country));assert.equal(r.country,r.market);assert(r.restaurantMarketId.startsWith(r.country+'|'));assert.equal(r.nutrientBasis,'per named serving');assert(r.verificationStatus);}
for(const r of ca){assert.equal(r.country,'CA');assert.equal(r.market,'CA');assert(r.source.startsWith('https://'));assert(r.serving&&r.checked&&r.retrievedAt);assert.equal(r.units.na,'mg');assert.equal(r.units.cal,'kcal');assert.deepEqual(r.conversions,[]);for(const k of Object.keys(C.fields))assert(r[k]===null||C.finite(r[k]));if(r.sugar!==null&&r.c!==null)assert(r.sugar<=r.c,`${r.id}: sugars exceed carbs`);}
assert(!ca.some(r=>r.name.includes('Mango Passionfruit')));
const a=ca.find(r=>r.officialDataUrl?.endsWith('/teen-burger/default')),fries=ca.find(r=>r.officialDataUrl?.endsWith('/russet-thick-cut-fries-regular/default')),drink=ca.find(r=>r.officialDataUrl?.endsWith('/aw-root-beer-small/default'));
const total=C.subtotal([a,fries,drink].map(record=>({record,quantity:1})));assert.equal(total.cal.known,1000);assert.equal(total.p.known,32);assert.equal(total.na.known,1305);assert(Object.values(total).every(v=>v.complete));
const tim=ca.find(r=>r.name==='Egg & Cheese English Muffin'),latte=ca.find(r=>r.name==='Protein Latte - Medium');assert.equal(tim.sourceDate,'2026-07');assert.equal(C.subtotal([tim,latte].map(record=>({record,quantity:1}))).p.known,34);
const missing={...tim,fat:null,f:null,na:null};assert.equal(E.complete(missing),false);assert.equal(E.eligible(missing,E.normalize({complete:false,market:'CA'},ca)),true);assert.equal(E.eligible(missing,E.normalize({complete:false,market:'CA',minFiber:1},ca)),false);assert.equal(C.subtotal([{record:missing,quantity:1}]).fat.complete,false);
for(const market of ['US','CA']){const state=E.normalize({market,complete:false,minProtein:10},registry);assert(E.results(registry,state).every(r=>r.country===market));}
const pair=[{chain:'Same chain',name:'Same item',country:'US',cal:400,p:20,c:40,fat:10},{chain:'Same chain',name:'Same item',country:'CA',cal:410,p:21,c:41,fat:11}];assert.notEqual(E.key(pair[0]),E.key(pair[1]));assert.equal(E.key(pair[0]),'Same chain||Same item');
let inputs=E.fromSearch('?chain=Tim%20Hortons&minProtein=20&maxSodium=1000',ca);assert.equal(inputs.market,'CA');assert.deepEqual(E.fromSearch('?'+E.toSearch(inputs),ca),inputs);
const s={window:{GetMacrosOrderCore:C}};vm.createContext(s);vm.runInContext(fs.readFileSync('js/order-share.js','utf8'),s);const card=s.window.GetMacrosOrderShare.svg({...tim,note:'PRIVATE SECRET',maxCal:999});assert(card.includes('Canada'));assert(card.includes('2026-07'));assert(!card.includes('PRIVATE SECRET'));assert(!card.includes('999'));assert(!card.includes('undefined'));const longURL='https://example.com/'+('a'.repeat(220))+'/nutrition.pdf';const lines=require('../../js/order-share.js').wrap(longURL,78);assert(lines.every(x=>x.length<=78));assert.equal(lines.join(''),longURL);
const baseline={window:{}};vm.createContext(baseline);for(const f of ['meal-data','meal-provenance'])vm.runInContext(fs.readFileSync('js/'+f+'.js','utf8'),baseline);for(const m of baseline.window.GM_MEALS){const current=registry.find(r=>E.key(r)===E.key(m));assert(current, E.key(m));for(const k of ['cal','p','c','fat','f','na'])assert.equal(current[k]??null,m[k]??null,`${E.key(m)} ${k}: finder and builder disagree`);}
const rechecked=baseline.window.GM_MEALS.filter(m=>m.sourceReview);assert.equal(rechecked.length,6);for(const m of rechecked){assert.equal(m.checked,m.sourceReview.reviewedAt);assert.equal(m.sourceReview.reviewedAt,'2026-10-09');assert.deepEqual(Array.from(m.sourceReview.fields),['cal','p','c','fat','f','na']);assert(m.nutrientProvenance);}
const sources=fs.readFileSync('sources.html','utf8');assert(sources.includes('Complete macros means known calories, protein, carbs and fat'));assert(!sources.includes('This release inspected 41'));assert(!sources.includes('Fat or carbohydrate values can still be unverified'));
console.log('PASS: Canadian source fields, exact order sums, editions, market isolation, missing macros/nutrients, stable U.S. keys, share state, private-card exclusion and finder/builder equality.');
