"""Reconcile current route scope without carrying forward old visual-review claims."""
from pathlib import Path
from html import unescape
import csv,json,re
from redesign_inventory import family,plain
from normalize_calculator_layouts import Document
root=Path(__file__).resolve().parents[1];out=root/'docs/redesign'
viewed=set('index.html restaurant-meal-finder.html calculators.html chipotle-healthy-meals-macros.html how-much-protein-can-your-body-absorb.html search.html blog.html articles.html restaurant-meal-guides.html healthy-fast-food.html high-protein-foods-list.html recipe-macro-scaler.html nutrition-label-comparison-tool.html protein-value-calculator.html budget-meal-builder.html sodium-label-comparison-tool.html carbohydrate-label-portion-tool.html weight-goal-timeline-calculator.html sweat-rate-calculator.html about.html sources.html editorial-policy.html corrections.html contact.html accessibility.html privacy.html terms.html 404.html'.split())
checks=json.loads((out/'reset/render-checks.json').read_text(encoding='utf-8'))
rows=[];queries=[]
for p in sorted(root.glob('*.html')):
 text=p.read_text(encoding='utf-8');doc=Document(text);kind=family(p.name,text);h1=next(n for n in doc.nodes if n['tag']=='h1');title=plain(text[h1['inner']:h1['close']]);problems=[r for r in checks['failures'] if r['file']==p.name]
 rows.append(dict(route='/'+p.name,template=kind,visual_status='Inspected page-family / outlier screenshots; see reset report for exact viewport scope' if p.name in viewed else 'Automated rendering only; shared template visually inspected',copy_status='Headings and introductions reviewed; shared repetition report reviewed; factual bodies retained',SEO_status='Metadata, canonical, links and sitemap checked; established URL retained',responsive_status='10 Chromium route renders: five widths × two themes',interaction_status='Representative family flows tested; not every individual control manually tested',verification_performed='DOM, overflow, images, labels and runtime checks; '+('screenshots inspected' if p.name in viewed else 'screenshots captured, not individually inspected'),remaining_issues='Render failures: '+str(len(problems)) if problems else 'No automated route failures; no fresh medical or restaurant-data re-verification'))
 heads=[plain(text[n['inner']:n['close']]) for n in doc.nodes if n['tag']=='h2' and 'close' in n][:5]
 queries.append(dict(route='/'+p.name,primary_query_or_topic=title,primary_intent={'home':'Find a fast-food order by restaurant and nutrient limits','finder':'Filter, inspect and compare recorded restaurant orders','restaurant':'Understand this restaurant’s tracked orders and portions','calculator-hub':'Estimate daily calorie and macro targets','calculator':'Calculate the specific labeled quantity','article':'Answer the question in the title','legal':'Read site terms or commitments','trust':'Understand the publisher and methods'}.get(kind,'Navigate the named resource'),supporting_questions='; '.join(heads),unique_value='Existing sourced article body' if kind=='article' else 'Actual tool, data or site-specific information',next_action='Use related source/tool links on this page',indexability='noindex' if p.name=='404.html' else 'indexable',evidence='Repository content and qualitative research in reset/seo-research.md; no volume estimate'))
home=dict(next(r for r in rows if r['route']=='/index.html'));home['route']='/';rows.append(home)
for p in root.glob('design/*.dc.html'):rows.append(dict(route='/'+p.relative_to(root).as_posix(),template='development preview',visual_status='Not a public route',copy_status='Excluded',SEO_status='Excluded by _config.yml',responsive_status='Not applicable',interaction_status='Not applicable',verification_performed='Deployment config inspected',remaining_issues='None; development-only asset'))
for filename,data in [('coverage.csv',rows),('query-to-page.csv',queries)]:
 with (out/filename).open('w',encoding='utf-8',newline='') as f:w=csv.DictWriter(f,fieldnames=list(data[0]));w.writeheader();w.writerows(data)
print('Coverage reconciled:',len(rows),'scope records;',len(viewed),'visually reviewed family/outlier pages.')
