from pathlib import Path
p=Path('tools/market_presentation.py');s=p.read_text(encoding='utf-8');s=s.replace("text=text.replace('data-design=\"edition\"','data-design=\"market\"')", "text=re.sub(r'\\sdata-design=\"[^\"]*\"','',text)\n text=text.replace('<body','<body data-design=\"market\"',1)")
s=s.replace("if hero and 'end' in hero:","if hero and 'end' in hero and name!='contact.html':")
s=s.replace(" if name=='about.html'", " if name=='contact.html' and 'data-copy-address' not in text:\n  text=text.replace('<p class=\"contact-hint\">Opens your mail service in a new tab. Sign in if needed.</p>',CONTACT)\n if name=='search.html' and 'search-entry' not in text:\n  text=re.sub(r'(<h1>.*?</h1>)(\\s*)(<label class=\"search-box\".*?<p id=\"search-status\".*?</p>)',r'<div class=\"search-title\"><span class=\"eyebrow\">The GetMacros directory</span>\\1</div><div class=\"search-entry\">\\3</div>',text,count=1,flags=re.S)\n if name=='about.html'")
s += '''\nCONTACT='''+repr('''<div class="contact-direct"><span class="eyebrow">Email me directly</span><a class="contact-address" href="mailto:getmacros.net@outlook.com">getmacros.net@outlook.com</a><div class="contact-direct-actions"><button class="btn btn-secondary" type="button" data-copy-address>Copy email address</button><a class="btn btn-primary" href="#contact-draft" data-contact-topic="idea">Suggest an improvement</a><a class="btn btn-quiet" href="#contact-draft" data-contact-topic="problem">Report a problem</a></div></div>''')+'\n'
p.write_text(s,encoding='utf-8')
p=Path('js/calculators.js');s=p.read_text(encoding='utf-8');s=s.replace("'<div class=\"result-total\">' +\n          '<div class=\"num\" data-count=", "'<div class=\"daily-estimate\"><div class=\"result-total\"><span class=\"eyebrow\">Your daily estimate</span>' +\n          '<div class=\"num\" data-count=",1)
s=s.replace("        macroRow(\"protein\",", "        '<div class=\"estimate-macros\">' + macroRow(\"protein\",",1)
s=s.replace('macroRow("carbs", "Carbohydrate", r.carbG, r.carbCals, cPct) +','macroRow("carbs", "Carbohydrate", r.carbG, r.carbCals, cPct) + \'</div></div>\' +',1)
s=s.replace("return '<div class=\"macro-result-row\">' +", "return '<div class=\"estimate-nutrient\">' +")
s=s.replace("'<span><span class=\"dot ' + cls + '\"></span>' + label + ' (' + pct + '%)</span>' +", "'<span class=\"estimate-label\">' + label + '</span>' +")
s=s.replace("'<span class=\"cals\">' + fmt(cals) + ' cal</span></span>' +", "'<span class=\"cals\">' + pct + '% · ' + fmt(cals) + ' cal</span></span>' +")
p.write_text(s,encoding='utf-8')
p=Path('tools/market-system.css');s=p.read_text(encoding='utf-8');s+='''\n/* Contact, formulas and the daily estimate have dedicated compositions. */
.contact-direct{margin-top:28px;padding-block:24px;border-block:1px solid var(--line)}.contact-address{display:block;font-size:clamp(1.1rem,2.2vw,1.8rem);font-weight:600;margin:12px 0 22px;overflow-wrap:anywhere}.contact-direct-actions{display:flex;gap:12px;flex-wrap:wrap}.guide-formula{display:flex;flex-wrap:wrap;align-items:center;gap:10px;margin-block:24px}.guide-formula span{min-width:0;overflow-wrap:anywhere}.daily-estimate{display:grid;grid-template-columns:1fr 2fr;gap:30px;align-items:center;margin-bottom:28px}.daily-estimate .result-total{margin:0;padding:0;text-align:left}.daily-estimate .num{font-size:clamp(3rem,5vw,4.5rem);line-height:1.15;font-weight:600}.daily-estimate .macro-bar{grid-column:1/-1;grid-row:2;margin:0}.estimate-macros{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.estimate-nutrient{display:flex;flex-direction:column;gap:12px;border-left:1px solid var(--line);padding-left:20px}.estimate-label{font-weight:600}.estimate-nutrient .grams{font-size:clamp(1.5rem,3vw,2.5rem);font-weight:600;font-variant-numeric:tabular-nums;white-space:nowrap}.estimate-nutrient .cals{font-size:.8rem;color:var(--muted)}.search-entry{min-width:0}.search-entry .search-box{margin:0}.search-title .eyebrow{margin-bottom:18px;display:block}.search-title h1{max-width:14ch}.search-entry .search-suggestions{margin-block:18px}.search-entry #search-status{font-size:.85rem;color:var(--muted)}
@media(max-width:640px){.daily-estimate{grid-template-columns:1fr;gap:24px}.daily-estimate .macro-bar{grid-row:3}.estimate-macros{gap:10px}.estimate-nutrient{padding:0;border:0;font-size:.75rem}.estimate-nutrient .grams{font-size:1.5rem}.estimate-nutrient .cals{font-size:.65rem}.search-entry{margin-top:28px}.contact-direct-actions>*{width:100%}}
''';p.write_text(s,encoding='utf-8')
