#!/usr/bin/env python3
"""Apply the same browser-side protections to every page.

GitHub Pages serves static files and cannot set HTTP response headers, so the
defenses available are a meta CSP, a referrer policy, and a frame-buster for
clickjacking (frame-ancestors is ignored when delivered via <meta>).

Pages generated by generate_*.py already carry these; this covers the rest.
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(os.path.dirname(__file__)))

CSP = (
    "default-src 'self'; "
    "script-src 'self' 'unsafe-inline' https://pagead2.googlesyndication.com "
    "https://*.googlesyndication.com https://*.doubleclick.net https://*.google.com "
    "https://*.googletagservices.com https://*.adtrafficquality.google "
    "https://*.gstatic.com https://*.googleapis.com; "
    "style-src 'self' 'unsafe-inline' https://*.googlesyndication.com; "
    "img-src 'self' data: https://*.googlesyndication.com https://*.doubleclick.net "
    "https://*.google.com https://*.gstatic.com https://*.adtrafficquality.google; "
    "font-src 'self'; "
    "connect-src 'self' https://*.googlesyndication.com https://*.doubleclick.net "
    "https://*.google.com https://*.adtrafficquality.google https://*.googleapis.com; "
    "frame-src 'self' https://*.googlesyndication.com https://*.doubleclick.net "
    "https://*.google.com https://*.adtrafficquality.google; "
    "object-src 'none'; base-uri 'self'; form-action 'self'; "
    "upgrade-insecure-requests"
)

CSP_META = f'<meta http-equiv="Content-Security-Policy" content="{CSP}">'
REFERRER_META = '<meta name="referrer" content="strict-origin-when-cross-origin">'
FRAME_BUSTER = (
    '<script>if(self!==top){try{top.location=self.location;}'
    'catch(e){document.documentElement.style.display="none";}}</script>'
)


def harden(path):
    with open(path, encoding="utf-8") as fh:
        c = fh.read()
    original = c

    # The frame-buster must run before anything renders.
    if "self!==top" not in c:
        m = re.search(r"<meta charset=[^>]*>", c, re.I)
        if m:
            c = c[:m.end()] + FRAME_BUSTER + c[m.end():]

    add = ""
    if "Content-Security-Policy" not in c:
        add += CSP_META
    if 'name="referrer"' not in c:
        add += REFERRER_META
    if add:
        c = c.replace("</head>", add + "</head>", 1)

    if c != original:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(c)
        return True
    return False


def main():
    os.chdir(ROOT)
    targets = sorted(glob.glob("*.html")) + sorted(glob.glob("es/*.html")) + sorted(glob.glob("fr/*.html"))
    n = sum(1 for p in targets if harden(p))
    print(f"hardened {n} of {len(targets)} pages")


if __name__ == "__main__":
    sys.exit(main())
