"""Refine the owning rules instead of appending a competing stylesheet."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1]
p=R/'tools/market-system.css';s=p.read_text(encoding='utf-8')
def swap(a,b):
 global s
 assert a in s,a[:90]
 s=s.replace(a,b)
swap('--radius:20px;', '--radius:16px;--space-1:4px;--space-2:8px;--space-3:12px;--space-4:16px;--space-6:24px;--space-8:32px;--space-12:48px;--control-compact:36px;--control-height:48px;')
swap('column-gap:24px;width:min(1424px','column-gap:24px;width:min(1424px')
swap('.nav-utility{display:flex;', '.nav-utility{grid-column:3;justify-self:end;display:flex;')
swap('gap:55px;','gap:48px;')
swap('width:380px;padding:24px;','width:336px;padding:12px;')
swap('min-height:46px;','min-height:var(--control-height);')
swap('min-height:48px;margin-top:7px;', 'min-height:var(--control-height);height:var(--control-height);margin-top:8px;')
swap('textarea{min-height:150px;', 'textarea{height:auto;min-height:150px;')
swap('box-shadow:0 3px 0 color-mix(in srgb,var(--green),black 18%)','box-shadow:none')
swap('box-shadow:0 4px 12px #172d2412','background:color-mix(in srgb,var(--surface),var(--green) 8%)')
swap('.quiet-button,.quiet-link{background:none!important;border:0!important;box-shadow:none!important;', '.quiet-button,.quiet-link{background:none;border:0;box-shadow:none;')
swap('.units-toggle button{min-height:38px;padding:8px 14px;', '.units-toggle button{min-height:var(--control-compact);height:var(--control-compact);padding:6px 12px;')
swap('.radio-row label{padding:10px;', '.radio-row label{min-height:var(--control-height);padding:10px;')
swap('.market-welcome{text-align:center;padding-block:52px 28px}', '.market-welcome{text-align:center;padding-block:32px 24px}')
swap('.market-welcome h1{font-size:clamp(3rem,5vw,4.8rem)', '.market-welcome h1{font-size:clamp(2.8rem,4.5vw,4.4rem)')
swap('margin:22px 0}', 'margin:8px 0 16px}')
swap('.market-feature-copy{padding:48px;background:var(--soft);align-self:start;min-height:450px;border-radius:0 20px 20px 0;', '.market-feature-copy{padding:32px 48px;align-self:stretch;')
swap('.market-feature{display:grid;grid-template-columns:1.2fr 1fr;gap:0;margin-block:45px}', '.market-feature{display:grid;grid-template-columns:1.2fr 1fr;gap:0;margin-block:32px;align-items:start}')
swap('border-radius:20px 0 0 20px','border-radius:var(--radius)')
swap('.filter-panel-head h2{font-size:1.2rem;margin-bottom:20px}', '.filter-panel-head h2{font-size:1.2rem;margin-bottom:16px}')
swap('.filter-panel-head [data-close-filters]{display:none}', '.filter-deck .filter-panel-head{display:none}.filter-panel-head [data-close-filters]{display:none}')
swap('gap:30px;align-items:end}.filter-primary', 'gap:24px;align-items:end}.filter-primary')
swap('.restaurant-picker summary{padding:12px 16px}', '.restaurant-picker summary{min-height:46px;padding:10px 16px;line-height:1.4}')
swap('.restaurant-picker[open] .restaurant-checks{', '.restaurant-picker[open] .restaurant-checks{overscroll-behavior:contain;')
swap('.finder-choice:has(:checked){background:var(--highlight)}', '.finder-choice:has(:checked){background:var(--highlight)}.finder-choice:hover{background:var(--soft)}.restaurant-checks .finder-choice{gap:12px;padding:8px}.restaurant-checks .restaurant-mark{width:28px;height:28px;flex-basis:28px}')
swap('.order-ticket{display:flex;flex-direction:column;border-top:3px solid var(--green);background:var(--surface);box-shadow:0 0 0 1px var(--line);border-radius:0 0 16px 16px;padding:24px 28px;min-width:0}', '.order-ticket{display:grid;grid-template-rows:subgrid;grid-row:span 5;row-gap:0;border:1px solid var(--line);background:var(--surface);border-radius:var(--radius);padding:24px;min-width:0}')
swap('margin-bottom:20px}.order-identity>a', 'margin-bottom:16px}.order-identity>a')
swap('.order-identity>a{font-weight:', '.order-identity>a{display:flex;gap:10px;align-items:center;min-width:0;line-height:1.35;color:var(--ink);font-weight:')
swap('font-size:1.55rem;line-height:1.2;margin-bottom:12px;', 'font-size:1.4rem;line-height:1.3;margin-bottom:8px;')
swap('padding-block:18px;margin:4px 0 20px;border-block:1px solid var(--line)', 'padding-block:16px;margin:0 0 16px;border-block:1px solid var(--line)')
swap('.order-actions{display:flex;align-items:start;', '.order-actions{display:flex;align-items:start;')
swap('.page-category{font-size:.8rem;font-weight:600;color:var(--green);padding-top:9px;border-top:3px solid var(--green);align-self:start}', '.page-category{font-size:.8rem;font-weight:600;color:var(--green);padding-top:8px;align-self:start}')
swap('.page-intro-content h1{max-width:24ch;margin-bottom:24px}', '.page-intro-content h1{max-width:24ch;margin-bottom:16px}')
swap('.reading-contents{background:var(--soft);padding:0 22px;border:0;border-radius:12px;margin-bottom:35px}', '.reading-contents{padding:0;border-block:1px solid var(--line);margin-bottom:32px}')
start=s.index('.calculation-workbench .compact-macro-form{');end=s.index('.calculation-workbench>.results{',start)
s=s[:start]+'''.calculation-workbench .compact-macro-form{display:grid;gap:24px;padding:0;background:none;border:0;border-radius:0}.compact-macro-form .macro-details{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px;margin:0}.compact-macro-form .field{margin:0;min-width:0}.compact-macro-form .field>label,.field-heading{display:flex;align-items:center;justify-content:space-between;gap:8px;min-height:40px;margin:0 0 8px;font-size:.87rem;font-weight:600}.field-heading label{margin:0}.field-heading .units-toggle{margin:0;flex-wrap:nowrap;gap:4px}.compact-macro-form input,.compact-macro-form select{margin-top:0}.height-pair{flex-wrap:nowrap}.height-pair label{position:relative;margin:0}.height-pair input{padding-right:32px}.input-unit{position:absolute;right:12px;top:12px;color:var(--muted);font-size:.85rem;pointer-events:none}.macro-explanations{display:grid;grid-template-columns:1fr 1fr;gap:24px}.macro-explanations details{margin:0}.compact-macro-form .publication-calculator-note{margin:0;max-width:none}.results.empty:empty{display:none}.compact-macro-form>.calc-submit{justify-self:start;min-width:240px}
'''+s[end:]
swap('.calculation-workbench{width:min(1100px,calc(100% - 96px));margin:40px auto;display:block}', '.calculation-workbench{width:min(1100px,100%);margin:0 auto;display:block}')
swap('.market-search-head .search-box{padding:30px;background:var(--soft);border-radius:20px}', '.market-search-head .search-box{padding:0}')
swap('.chain-finder-section{background:var(--soft)}', '.chain-finder-section{border-bottom:1px solid var(--line)}')
swap('.food-panel h2{padding-bottom:18px;border-bottom:2px solid var(--green)}', '.food-panel h2{padding-bottom:16px;border-bottom:1px solid var(--line)}')
swap('.filter-deck .filter-reset button{font-size:.75rem}', '.filter-deck .filter-reset button{font-size:.8rem}')
swap('.results-grid{grid-template-columns:1fr;gap:20px}', '.results-grid{grid-template-columns:1fr;gap:16px}.order-ticket{grid-row:auto;grid-template-rows:auto;display:flex;flex-direction:column}')
swap('.order-heading h2{font-size:1.5rem}', '.order-heading h2{font-size:1.35rem}')
swap('font-size:2.5rem}.order-nutrition>div', 'font-size:2.1rem}.order-nutrition>div')
swap('.market-feature figcaption{padding:10px;background:var(--soft);font-size:.7rem}', '.market-feature figcaption{padding:8px 0;font-size:.7rem}')
swap('.market-feature-copy{min-height:0;border-radius:0 0 18px 18px;padding:26px}', '.market-feature-copy{padding:24px 0 0}')
swap('.market-feature img{height:270px;border-radius:18px 18px 0 0}', '.market-feature img{height:260px;border-radius:var(--radius)}')
swap('.market-feature h2{font-size:2.5rem}', '.market-feature h2{font-size:2rem}')
swap('.market-search-head .search-box{padding:20px;margin-top:25px}', '.market-search-head .search-box{padding:0;margin-top:24px}')
# Delete superseded fieldset positioning and duplicate shortcut styling.
s=re.sub(r'\.compact-macro-form>fieldset[^{}]*\{[^{}]*\}','',s)
s=s.replace('.calculation-workbench .compact-macro-form{grid-template-columns:1fr 1fr}', '.compact-macro-form .macro-details{grid-template-columns:1fr 1fr}')
s=s.replace('.calculation-workbench .compact-macro-form{grid-template-columns:1fr}', '.compact-macro-form .macro-details,.macro-explanations{grid-template-columns:1fr}.compact-macro-form>.calc-submit{width:100%;min-width:0}')
s=re.sub(r'\.brand-caption\{[^}]*\}|\.back-to-top\{[^}]*\}|\.restaurant-initial\{[^}]*\}', '',s)
s=s.replace('margin-bottom:30px','margin-bottom:32px').replace('gap:30px','gap:32px').replace('gap:35px','gap:32px').replace('gap:65px','gap:64px')
p.write_text(s,encoding='utf-8')

p=R/'tools/market-content.css';s=p.read_text(encoding='utf-8')
s=s.replace('.submission-sources,.source-box,.sources-box{background:var(--soft);padding:24px;border-radius:0;border-left:3px solid var(--green);', '.submission-sources,.source-box,.sources-box{padding:24px 0;border-top:1px solid var(--line);')
s=s.replace('.publication-example,.practical-example{padding:26px;background:var(--soft);border-radius:var(--radius);margin-block:26px}', '.publication-example,.practical-example{padding:24px 0;margin-block:24px;border-top:1px solid var(--line)}')
s=s.replace('.example-grid>*,.advice-card{padding:20px;background:var(--surface);border-radius:var(--radius)}', '.example-grid>*,.advice-card{padding:16px 0}.example-grid>*+*,.advice-grid>*+*{border-left:1px solid var(--line);padding-left:24px}')
s=s.replace('.single-macro-card{padding:22px 0;border-top:1px solid var(--line)}', '.single-macro-card{display:grid;grid-template-rows:subgrid;grid-row:span 3;row-gap:0;padding:24px 0;border-top:1px solid var(--line)}.single-macro-form{display:flex;flex-direction:column;gap:16px}.single-macro-form .field{margin:0}.single-macro-form .field>label{display:flex;align-items:center;min-height:40px;margin:0 0 8px}.single-macro-form input,.single-macro-form select{margin-top:0}.single-macro-form>.calc-submit{margin-top:auto;width:100%}.single-macro-form .field-heading{margin-bottom:8px}')
s=s.replace('.single-card-head{display:flex;gap:12px;margin-bottom:16px}', '.single-card-head{display:flex;gap:12px;margin-bottom:16px}.single-card-head h3{margin:0}')
s=s.replace('.single-macro-result{margin-top:18px;padding:16px;background:var(--soft);border-radius:var(--radius)}', '.single-macro-result{margin-top:16px;padding:16px 0;border-top:1px solid var(--line)}')
s=s.replace('.comparison-basis{padding:14px;background:var(--surface);margin-bottom:18px}', '.comparison-basis{margin-bottom:24px}')
s=s.replace('.clear-tool-card{display:flex;gap:18px;align-items:center;', '.clear-tool-card{display:flex;gap:16px;align-items:start;')
s=s.replace('.clear-tool-card h3{margin-bottom:5px}', '.clear-tool-card h3{margin-bottom:8px}.clear-tool-card:after{content:"→";margin-left:auto;align-self:center;color:var(--green)}.clear-tool-card:hover h3{text-decoration:underline;text-underline-offset:4px}')
s=s.replace('.chain-card{padding:25px 0;', '.chain-card{padding:24px 0;')
s=s.replace('grid-template-columns:44px minmax(0,1fr);gap:4px 15px;', 'grid-template-columns:48px minmax(0,1fr);gap:4px 16px;')
s=s.replace('.directory-logo{width:42px;height:42px;margin-bottom:14px}', '.directory-logo{width:48px;height:48px;margin:0;flex-shrink:0}')
s=s.replace('.contact-address{padding:25px;background:var(--surface);border-radius:var(--radius);margin-top:24px}', '.contact-address{padding:0;margin-top:24px}')
s=s.replace('.clear-about-source{background:var(--soft)}','')
s=re.sub(r'\.back-to-top[^{}]*\{[^{}]*\}|\.restaurant-initial\{[^}]*\}', '',s)
s=s.replace('.publication-example,.practical-example{padding:20px}', '.publication-example,.practical-example{padding:24px 0}')
s=s.replace('.contact-address{padding:21px}', '')
s=s.replace('.single-macro-grid{grid-template-columns:1fr;gap:10px}', '.single-macro-grid{grid-template-columns:1fr;gap:24px}.single-macro-card{display:block;grid-row:auto}.single-card-head{margin-bottom:16px}.example-grid>*+*,.advice-grid>*+*{border-left:0;border-top:1px solid var(--line);padding:16px 0 0}')
s=s.replace('@media(max-width:640px){}','').replace('@media(max-width:1050px){}','')
# Keep only the owning focused metric rules and one no-script nav definition.
s=re.sub(r'\.focused-metrics\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\);gap:18px\}', '',s)
s=re.sub(r'\.focused-metric\{padding:14px;background:var\(--surface\);border-radius:var\(--radius\)\}', '',s)
s=re.sub(r'\.no-script-nav\{[^}]*\}', '',s)
p.write_text(s,encoding='utf-8')
print('Owning Market layout rules replaced')
