from pathlib import Path
p=Path('tools/test-market-flows.cjs');s=p.read_text().replace("await localAssets(p);const errors", "await localAssets(p);await p.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.reject(new Error('Unavailable'))}}));const errors").replace("assert.ok(await p.locator('#contact-copy-status').innerText())", "await p.waitForFunction(()=>document.querySelector('#contact-copy-status').textContent.length>0);assert.equal(await p.locator('#contact-copy-text').inputValue(),'getmacros.net@outlook.com')");p.write_text(s)
p=Path('tools/rebuild_publication.py');s=p.read_text(encoding='utf-8');a=s.index(" options=''.join(");b=s.index(" links=''.join",a);s=s[:a]+s[b:];a=s.index(' # Only display recorded values.');b=s.index(' return (ROOT/',a);s=s[:a]+s[b:];s=s.replace(".replace('__RESTAURANT_OPTIONS__',options)", '').replace(".replace('__FEATURED_MEALS__',''.join(featured))",'');p.write_text(s,encoding='utf-8')
p=Path('images/README.md');s=p.read_text(encoding='utf-8');s=s.replace('`tools/edition-blog.inc`','`tools/market-blog.inc`');s+='\n## Market presentation, 23 September 2026\n\nThe four-petal mark in `botanical-mark.svg`, `favicon.svg`, the current header and footer is original repository-native vector artwork. `tools/render-botanical-brand.cjs` creates its app icons and social image. Older sprout and scene assets are not used by the new homepage. The meal finder intentionally uses no food photographs; no generic photograph is represented as an exact restaurant order. The retained salad photograph remains credited beside the image and in the licence record above.\n';p.write_text(s,encoding='utf-8')
root=Path('.').resolve()
obsolete=['edition-foundation.css','edition-families.css','edition-workspaces.css','edition-home.inc','edition-blog.inc','editorial-header.inc','editorial-footer.inc','calibrate_reference.py','finish_reference.py','refine_edition.py','migrate_edition_styles.py','migrate_market_build.py']
for name in obsolete:
 p=(root/'tools'/name).resolve();assert p.parent==root/'tools'
 if p.exists():p.unlink()
print('Removed obsolete presentation sources and their retired one-time migration scripts.')
